Query_S3_Bucket_Logging_Is_Disabled_CloudTrail
Checkmarx/kics pull request #1009
Opened 2020-12-16 10:22 UTC by pedropereiraaa

Closes #1001

2020-12-22 18:16 UTC, rogeriopeixotocx requested changes
Almost good.

2020-12-22 18:16 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/BucketPolicyEnabled/test/negative.yaml
> +                "Fn::Join":
Linter is complaining about this, Try removing the surrounding double quotes: `Fn::Join`

2020-12-22 18:16 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/BucketPolicyEnabled/test/negative.yaml
> +          "Fn::GetAtt":
Linter is complaining about this, Try removing the surrounding double quotes: `Fn::GetAtt`

2020-12-22 18:16 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/BucketPolicyEnabled/test/negative.yaml
> +                    - "Fn::Join":
Linter is complaining about this, Try removing the surrounding double quotes: `Fn::Join`

2020-12-22 18:16 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/BucketPolicyEnabled/test/negative.yaml
> +              'Fn::Join':
Linter is complaining about this, Try removing the surrounding quotes: `Fn::Join`

2020-12-22 18:16 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/BucketPolicyEnabled/test/positive.yaml
> +          "Fn::GetAtt":
Linter is complaining about this, Try removing the surrounding double quotes: `Fn::GetAtt`

2020-12-22 18:16 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/BucketPolicyEnabled/test/positive.yaml
> +                "Fn::Join":
Linter is complaining about this, Try removing the surrounding double quotes: `Fn::Join`

2020-12-22 18:16 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/BucketPolicyEnabled/test/positive.yaml
> +                    - "Fn::Join":
Linter is complaining about this, Try removing the surrounding double quotes: `Fn::Join`

2020-12-22 18:16 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/BucketPolicyEnabled/test/negative.yaml
> +        DestinationBucketName: !Ref LoggingBucket
Since `LoggingBucket `is not declared in this sample. Remove the `!Ref`, leaving only the string.

2020-12-22 18:16 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/BucketPolicyEnabled/query.rego
> +                "keyExpectedValue": sprintf("'Resources.%s.Properties' has property 'LoggingConfiguration'", [name]),
`S3 bucket '%s' should have LoggingConfiguration enabled`

2020-12-22 18:16 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/BucketPolicyEnabled/query.rego
> +                "keyActualValue": 	sprintf("'Resources.%s.Properties' doesn't have property 'LoggingConfiguration'", [name])
`S3 bucket '%s' doesn't have LoggingConfiguration enabled`

2020-12-23 14:29 UTC, rogeriopeixotocx commented
LGTM ✅

2020-12-23 14:54 UTC, ruigomescx approved these changes

2020-12-23 16:58 UTC, merged