Add AmazonMQ Broker W/Out EncryOptions query #1036
Checkmarx/kics pull request #1037
Opened 2020-12-16 14:48 UTC by joelcarvalhocheckmarx

AmazonMQ Broker should be Encryption Options defined

Closes #1036

2020-12-23 11:07 UTC, rogeriopeixotocx requested changes
Almost good

2020-12-23 11:07 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/amazonMQ_broker_without_encryption_options/metadata.json
> +  "queryName": "AmazonMQ Broker Without EncryptionOptions",
change query id to `amazonmq_broker_encryption_disabled`

also change the query directory name to: `amazonmq_broker_encryption_disabled`

queryName = `AmazonMQ broker encryption disabled`

2020-12-23 11:07 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/amazonMQ_broker_without_encryption_options/metadata.json
> +  "category": null,
`"category": "Encryption and Key Management",`

2020-12-23 11:07 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/amazonMQ_broker_without_encryption_options/query.rego
> +  not exists_eo
simplify this changing line 8 and 9 to:
`object.get(properties, "EncryptionOptions", "undefined") == "undefined"`

2020-12-23 15:04 UTC, rogeriopeixotocx commented
LGTM ✅

2020-12-28 10:34 UTC, joelsou5a approved these changes

2020-12-28 10:36 UTC, joelsou5a submitted a review, later dismissed

2020-12-28 10:41 UTC, merged