Query Logging_Is_Disabled_AWS
Checkmarx/kics pull request #1039
Opened 2020-12-16 15:01 UTC by pedropereiraaa

Closes #757

2020-12-22 16:04 UTC, rogeriopeixotocx requested changes
Requested some changes in the samples to make them valid.

2020-12-22 16:04 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/logging_is_disabled/test/negative.yaml
> +      DistributionConfig:
To make this sample valid. Add mandatory **DefaultCacheBehaviour** section inside **DistributionConfig** e.g:
```       
DefaultCacheBehavior:
    AllowedMethods:
    - GET
    - HEAD
    - OPTIONS
    TargetOriginId: myS3Origin
    ForwardedValues:
      QueryString: 'false'
      Cookies:
        Forward: none
    TrustedSigners:
    - 1234567890EX
    ViewerProtocolPolicy: allow-all
```

2020-12-22 16:04 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/logging_is_disabled/test/positive.yaml
> +      DistributionConfig:
To make this sample valid. Add mandatory **DefaultCacheBehaviour** section inside **DistributionConfig** e.g:
```       
DefaultCacheBehavior:
    AllowedMethods:
    - GET
    - HEAD
    - OPTIONS
    TargetOriginId: myS3Origin
    ForwardedValues:
      QueryString: 'false'
      Cookies:
        Forward: none
    TrustedSigners:
    - 1234567890EX
    ViewerProtocolPolicy: allow-all
```

2020-12-22 16:04 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/logging_is_disabled/test/positive.yaml
> +      DistributionConfig:
To make this sample valid. Add mandatory **DefaultCacheBehaviour** section inside **DistributionConfig** e.g:
```       
DefaultCacheBehavior:
    AllowedMethods:
    - GET
    - HEAD
    - OPTIONS
    TargetOriginId: myS3Origin
    ForwardedValues:
      QueryString: 'false'
      Cookies:
        Forward: none
    TrustedSigners:
    - 1234567890EX
    ViewerProtocolPolicy: allow-all
```

2020-12-22 16:04 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/logging_is_disabled/test/positive_expected_result.json
> +		"line": 5
After adding **DefaultCacheBehavior** adjust the positive lines if necessary.

2020-12-22 16:04 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/logging_is_disabled/test/positive_expected_result.json
> +		"line": 32
After adding **DefaultCacheBehavior** adjust the positive lines if necessary.

2020-12-28 14:11 UTC, ruigomescx approved these changes

2020-12-28 14:15 UTC, merged