added new query for EC2 network ACL denied traffic
Checkmarx/kics pull request #1063
Opened 2020-12-17 10:20 UTC by soniantao

Closes #1062

2020-12-23 15:24 UTC, rogeriopeixotocx requested changes
few things to fix

2020-12-23 15:24 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/ec2_network_ACL_deny_rules/metadata.json
> +  "category": null,
`"category": "Network Security",`

2020-12-23 15:24 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/ec2_network_ACL_deny_rules/metadata.json
> +}
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-23 15:24 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/ec2_network_ACL_deny_rules/query.rego
> + }
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-23 15:24 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/ec2_network_ACL_deny_rules/test/negative.yaml
> +       CidrBlock: 0.0.0.0/0
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-23 15:24 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/ec2_network_ACL_deny_rules/test/positive.yaml
> +       CidrBlock: 0.0.0.0/0
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-23 15:24 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/ec2_network_ACL_deny_rules/test/positive_expected_result.json
> +]
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-23 15:24 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/ec2_network_ACL_deny_rules/metadata.json
> +  "queryName": "EC2 network ACL denied traffic",
please change the **DIRECTORY name** and id to an all-lowercase string matching the query name: `ec2_network_acl_ineffective_denied_traffic`

change query name to: `EC2 Network ACL Ineffective Denied Traffic`

2020-12-23 15:24 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/ec2_network_ACL_deny_rules/query.rego
> +  contains(action,expectedAction)
no need to declare a variable for this constant value: `contains(action,"deny")`

2020-12-23 15:24 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/ec2_network_ACL_deny_rules/query.rego
> +  not contains(cidr,unvalidCidr)
simplify this block by replacing lines 8 and 9 with:
`not contains(cidr, "0.0.0.0/0")`

2020-12-23 15:24 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/ec2_network_ACL_deny_rules/metadata.json
> +  "descriptionText": "The deny rules defined for the selected AWS Network ACL are declared ineffective",
`"descriptionText": "Ineffective deny rules. A deny rule should be applied to all IP addresses.",`

2020-12-28 09:58 UTC, rogeriopeixotocx commented
LGTM ✅

2020-12-28 10:20 UTC, joelsou5a approved these changes

2020-12-28 10:21 UTC, merged