Added Query EMR Security Configuration Encryptions Enabled
Checkmarx/kics pull request #1072
Opened 2020-12-17 16:41 UTC by cataraujo190

Description
EMR SecurityConfiguration should enable and properly configure encryption at rest and in transit.

Close #1071

2020-12-23 14:43 UTC, rogeriopeixotocx requested changes
Almost good

2020-12-23 14:43 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/emr_security_configuration_encryptions_enabled/metadata.json
> +}
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-23 14:43 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/emr_security_configuration_encryptions_enabled/test/negative.yaml
> +           EnableAtRestEncryption: true
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-23 14:43 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/emr_security_configuration_encryptions_enabled/test/negative.yaml
> +  EMRSecurityConfiguration-01:
Remove `-` : `E3006 Resource EMRSecurityConfiguration-01 has invalid name.  Name has to be alphanumeric.`

2020-12-23 14:43 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/emr_security_configuration_encryptions_enabled/test/negative.yaml
> +  EMRSecurityConfiguration-02:
Remove `-` :
`E3006 Resource EMRSecurityConfiguration-02 has invalid name.  Name has to be alphanumeric.`

2020-12-23 14:43 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/emr_security_configuration_encryptions_enabled/test/positive.yaml
> +  EMRSecurityConfiguration-01:
Remove `-` :
`E3006 Resource EMRSecurityConfiguration-01 has invalid name.  Name has to be alphanumeric.`

2020-12-23 14:43 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/emr_security_configuration_encryptions_enabled/test/positive.yaml
> +  EMRSecurityConfiguration-03:
Remove `-` :
`E3006 Resource EMRSecurityConfiguration-03 has invalid name.  Name has to be alphanumeric.`

2020-12-23 14:43 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/emr_security_configuration_encryptions_enabled/metadata.json
> +  "category": null,
`"category": "Encryption and Key Management"`

2020-12-23 14:59 UTC, rogeriopeixotocx commented
LGTM ✅

2020-12-28 11:09 UTC, ruigomescx approved these changes

2020-12-28 11:09 UTC, merged