Add Kms Should Allow * as Principal query for CloudFormation #1075
Checkmarx/kics pull request #1076
Opened 2020-12-17 17:38 UTC by pedro-mimoso

Kms Should not allow Principal parameter to be set as * #1075

2020-12-28 11:38 UTC, rogeriopeixotocx requested changes
Few things to fix.

2020-12-28 11:38 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/kms_should_allow_principal/metadata.json
> +  "queryName": "Kms Should Allow * as Principal",
Change **query directory name** to: `kms_allows_wildcard_principal`
Change **id** to: `kms_allows_wildcard_principal`
Change **query name** to: `KMS allows wildcard principal`

2020-12-28 11:38 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/kms_should_allow_principal/metadata.json
> +  "category": null,
`Identity and Access Management`

2020-12-28 11:38 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/kms_should_allow_principal/metadata.json
> +}
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-28 11:38 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/kms_should_allow_principal/test/negative.yaml
> +          Resource: '*'
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-28 11:38 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/kms_should_allow_principal/test/positive.yaml
> +          Resource: '*'
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-28 13:34 UTC, rogeriopeixotocx commented
LGTM ✅

2020-12-29 15:06 UTC, ruigomescx approved these changes

2020-12-29 15:11 UTC, merged