Add Kms EnableKeyRotation Disabled query for CloudFormation #1077
Checkmarx/kics pull request #1078
Opened 2020-12-17 18:20 UTC by pedro-mimoso

EnableKeyRotation should not be false or undefined #1077

2020-12-21 17:48 UTC, Ruben-Silva requested changes

2020-12-21 17:48 UTC, Ruben-Silva commented on assets/queries/cloudFormation/kms_enablekeyrotation_disabled/query.rego
> +                "issueType":		"MissingValue",
"MissingAttribute" instead of "MissingValue"

2020-12-21 17:48 UTC, Ruben-Silva commented on assets/queries/cloudFormation/kms_enablekeyrotation_disabled/test/positive.yaml
> +          Resource: '*'
Add an example of when the attribute "EnableKeyRotation" is undefined

2020-12-21 17:48 UTC, Ruben-Silva commented on assets/queries/cloudFormation/kms_enablekeyrotation_disabled/test/positive_expected_result.json
> +]
Add an example of when the attribute "EnableKeyRotation" is undefined

2020-12-22 14:50 UTC, ruigomescx submitted a review, later dismissed

2020-12-22 15:15 UTC, ruigomescx approved these changes

2020-12-22 15:15 UTC, merged