Add IoT Policy Allows Action as * query for CloudFormation #1109
Checkmarx/kics pull request #1110
Opened 2020-12-18 14:12 UTC by pedro-mimoso

IoT Policy should not allow Action to be set as * #1109

2020-12-28 15:49 UTC, rogeriopeixotocx requested changes
Almost good

2020-12-28 15:49 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/iot_policy_allows_action/metadata.json
> +}
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-28 15:49 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/iot_policy_allows_action/query.rego
> +}
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-28 15:49 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/iot_policy_allows_action/test/negative.yaml
> +        PolicyName: PolicyName
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-28 15:49 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/iot_policy_allows_action/test/positive.yaml
> +        PolicyName: PolicyName
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-28 15:49 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/iot_policy_allows_action/test/positive.yaml
> +            - !GetAtt myqueue.Arn
Resource `myqueue` does not exist in this template. Remove the `GetAtt `function and leave the ARN hardcoded:

`NotResource: my-hardcoded-arn`

2020-12-28 15:49 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/iot_policy_allows_action/metadata.json
> +  "id": "iot_policy_allows_action",
Change **directory name** to: `iot_policy_allows_wildcard_action`
Change **id** to: `iot_policy_allows_wildcard_action`
Change **query name** to: `IoT Policy Allows Action as Wildcard`

2020-12-28 15:49 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/iot_policy_allows_action/metadata.json
> +  "category": null,
`Identity and Access Management`

2020-12-29 09:02 UTC, rogeriopeixotocx commented
LGTM ✅

2020-12-29 15:10 UTC, ruigomescx approved these changes

2020-12-29 15:11 UTC, merged