Add copy_from_without_from_alias_defined_previously Closes #1139
Checkmarx/kics pull request #1143
Opened 2020-12-18 17:42 UTC by rafaela-soares

For this query, it is necessary to check if the alias referenced by COPY --from (COPY --from=ALIAS ....) is a previously defined FROM alias (FROM myimage:tag as ALIAS).

To do that, we need to check if the cmd copy has an attribute 'flags' like "--from=" and keep the alias. Next, we need to check if this current alias is referenced in a previously defined FROM alias ( through attribute Values of cmd from)

Closes #1139

2020-12-23 11:42 UTC, joaoReigota1 requested changes

2020-12-23 11:42 UTC, joaoReigota1 commented on assets/queries/dockerfile/copy_from_without_from_alias_defined_previously/query.rego
> +}
COPY command with the flag '--from=0' shouldn't fail.
The COPY '--from=0' line copies just the built artifact from the previous stage into this new stage. The Go SDK and any intermediate artifacts are left behind, and not saved in the final image.

2020-12-23 11:42 UTC, joaoReigota1 commented on assets/queries/dockerfile/copy_from_without_from_alias_defined_previously/test/negative.dockerfile
> +---
remove '---' doesn't exist in docker

2020-12-23 11:42 UTC, joaoReigota1 commented on assets/queries/dockerfile/copy_from_without_from_alias_defined_previously/test/positive.dockerfile
> +---
same as before

2020-12-23 11:42 UTC, joaoReigota1 commented on assets/queries/dockerfile/copy_from_without_from_alias_defined_previously/metadata.json
> +  "queryName": "COPY --from Without FROM Alias Defined Previously",
change to "COPY '--from' Without FROM Alias Defined Previously"

2020-12-23 11:42 UTC, joaoReigota1 commented on assets/queries/dockerfile/copy_from_without_from_alias_defined_previously/metadata.json
> +  "descriptionText": "COPY --from should mention a previously defined FROM alias",
change to "COPY command with the flag '--from' should mention a previously defined FROM alias"

2020-12-28 10:39 UTC, joaoReigota1 reviewed
Approved

2020-12-28 11:02 UTC, joelsou5a approved these changes

2020-12-28 11:02 UTC, merged