Add no_platform_flag_with_from query Closes #991
Checkmarx/kics pull request #1157
Opened 2020-12-21 10:30 UTC by NunoAraujoCX

Closes #991 

Check if we are using --platform flag with FROM

2020-12-23 10:35 UTC, joaoReigota1 requested changes

2020-12-23 10:35 UTC, joaoReigota1 commented on assets/queries/dockerfile/no_platform_flag_with_from/metadata.json
> +  "queryName": "No Platform Flag With FROM",
The query name should reflect the vulnerability, not the fix

2020-12-23 10:35 UTC, joaoReigota1 commented on assets/queries/dockerfile/no_platform_flag_with_from/query.rego
> +                "keyActualValue": 	sprintf("FROM={{%s}}.{{%s}} use the flag --platform", [name, resource.Original])
Typo in 'use' change to 'FROM={{%s}}.{{%s}} uses the flag --platform'

2020-12-28 09:19 UTC, joaoReigota1 commented
Approved

2020-12-28 10:26 UTC, joelsou5a approved these changes

2020-12-28 10:26 UTC, merged