Add RDS Public Virtual Interface query for AWS CloudFormation
Checkmarx/kics pull request #1170
Opened 2020-12-21 11:34 UTC by Ruben-Silva

Adding RDS Public Virtual Interface query for AWS CloudFormation, that checks if the IP Address in its Security Group matchs prefixes advertised by Amazon.

Closes #1168

2020-12-29 10:18 UTC, rogeriopeixotocx requested changes
Requested changes

2020-12-29 10:18 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/rds_public_virtual_interface/test/positive.yaml
> +        Ref: DBName
`E1012 Ref DBName not found as a resource or parameter`

2020-12-29 10:18 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/rds_public_virtual_interface/test/positive.yaml
> +        Ref: MultiAZDatabase
`E1012 Ref MultiAZDatabase not found as a resource or parameter`

2020-12-29 10:18 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/rds_public_virtual_interface/test/positive.yaml
> +        Ref: DBUser
`E1012 Ref DBUser not found as a resource or parameter`

2020-12-29 10:18 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/rds_public_virtual_interface/test/positive.yaml
> +        Ref: DBClass
`E1012 Ref DBClass not found as a resource or parameter`

2020-12-29 10:18 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/rds_public_virtual_interface/test/positive.yaml
> +        Ref: DBAllocatedStorage
`E1012 Ref DBAllocatedStorage not found as a resource or parameter`

2020-12-29 10:18 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/rds_public_virtual_interface/test/positive.yaml
> +        Ref: DBPassword
`E1012 Ref DBPassword not found as a resource or parameter`

2020-12-29 10:18 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/rds_public_virtual_interface/test/positive.yaml
> +      SecurityGroupEgress:
`E2521 Property VpcId should exist with SecurityGroupEgress for Resources/DBEC2SecurityGroup2/Properties`

2020-12-29 10:18 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/rds_public_virtual_interface/test/positive.yaml
> +      SecurityGroupEgress:
`E2521 Property VpcId should exist with SecurityGroupEgress for Resources/DBEC2SecurityGroup/Properties`

2020-12-29 10:18 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/rds_public_virtual_interface/test/negative.yaml
> +      SecurityGroupEgress:
`E2521 Property VpcId should exist with SecurityGroupEgress for Resources/DBEC2SecurityGroup/Properties`

2020-12-29 10:18 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/rds_public_virtual_interface/test/positive.yaml
> +  DBInstance:
`W3011 Both UpdateReplacePolicy and DeletionPolicy are needed to protect Resources/DBinstance from deletion`

```
DeletionPolicy: Retain
UpdateReplacePolicy: Retain
```

2020-12-29 10:18 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/rds_public_virtual_interface/test/negative.yaml
> +  DBInstance:
`W3011 Both UpdateReplacePolicy and DeletionPolicy are needed to protect Resources/DBinstance from deletion`

```
DeletionPolicy: Retain
UpdateReplacePolicy: Retain
```

2020-12-29 10:18 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/rds_public_virtual_interface/test/positive.yaml
> +  DBinstance2:
`W3011 Both UpdateReplacePolicy and DeletionPolicy are needed to protect Resources/DBinstance2 from deletion`

```
UpdateReplacePolicy: Retain
```

2020-12-29 10:18 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/rds_public_virtual_interface/test/positive.yaml
> +  DBInstance3:
`W3011 Both UpdateReplacePolicy and DeletionPolicy are needed to protect Resources/DBinstance3 from deletion`

```
DeletionPolicy: Retain
UpdateReplacePolicy: Retain
```

2021-01-15 11:17 UTC, Ruben-Silva commented
This query can't be done through static analysis so its being removed.

2021-01-15 11:17 UTC, closed without merging