Add Filter&Alarm !Exists For Network Gateways
Checkmarx/kics pull request #1176
Opened 2020-12-21 11:39 UTC by fabioGoncalvesCx

Added new query for AWS CloudFormation.

Provide a CloudFormation resource and a resource to ensure that Network Gateways changes are catched by a log metric filter and an alarm
Closes #1173

2020-12-29 10:29 UTC, rogeriopeixotocx requested changes
Requesting changes

2020-12-29 10:29 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/filter_and_alarm_exist_for_for_changes_to_network_gateways/metadata.json
> +}
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-29 10:29 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/filter_and_alarm_exist_for_for_changes_to_network_gateways/query.rego
> +}
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-29 10:29 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/filter_and_alarm_exist_for_for_changes_to_network_gateways/test/negative.yaml
> +          MetricName: IAMPolicyEventCount
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-29 10:29 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/filter_and_alarm_exist_for_for_changes_to_network_gateways/test/positive.yaml
> +          MetricName: IAMPolicyEventCount
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-29 10:29 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/filter_and_alarm_exist_for_for_changes_to_network_gateways/query.rego
> +checkTopic(resourceAlarm, nameSNS) = true {
This function is only being used once and should not be declared, replace it for a direct comparison

2020-12-29 10:29 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/filter_and_alarm_exist_for_for_changes_to_network_gateways/query.rego
> +checkAlarm(metricFilter, resourceAlarm) = true {
This function is only being used once and should not be declared, replace it for a direct comparison

2020-12-29 10:29 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/filter_and_alarm_exist_for_for_changes_to_network_gateways/test/negative.yaml
> +        - Ref: SnsTopic
Either remove the reference (intrinsic function `Ref`) to Resource that doesn't exists or add it as a [Parameter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html) to the header of the template

2020-12-29 10:29 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/filter_and_alarm_exist_for_for_changes_to_network_gateways/metadata.json
> +  "queryName": "Filter And Alarm Not Exists For Changes To Network Gateways",
Change **directory name** and **id** to: `network_gateway_changes_without_alarms`
Change **query name** to: `Network Gateway Changes Without Alarms`

2020-12-29 11:00 UTC, rogeriopeixotocx commented
Fix the unit tests @fabioGoncalvesCx

2020-12-30 19:43 UTC, markmishaevcx commented
Scan submitted to Checkmarx

2020-12-30 19:48 UTC, markmishaevcx commented
![Logo](https://user-images.githubusercontent.com/23239410/92153465-ff743900-ee2c-11ea-9c8d-8141e38feb41.png)<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 4 vulnerabilities<br />![High](https://user-images.githubusercontent.com/23239410/92157087-97285600-ee32-11ea-988f-0aca12c4c126.png)&nbsp;**0 High**<br />![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3 Medium**<br />![Low](https://user-images.githubusercontent.com/23239410/92157091-98598300-ee32-11ea-8498-19bd7d62019b.png)&nbsp;**1 Low**<br />![Info](https://user-images.githubusercontent.com/23239410/92157090-97c0ec80-ee32-11ea-9b2e-aa6b32b03d54.png)&nbsp;**0 Info**<br />
### Violation Summary
![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049055&projectid=726)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[30](https://github.com/Checkmarx/kics/blob/feature/filter_and_alarm_exist_for_changes_to_network_gateways/cmd/builder/main.go#L30) |Medium|Path_Traversal|cmd/builder/main.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049055&projectid=726&pathid=3)
[80](https://github.com/Checkmarx/kics/blob/feature/filter_and_alarm_exist_for_changes_to_network_gateways/test/main_test.go#L80) |Medium|Denial_Of_Service_Resource_Exhaustion|test/main_test.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049055&projectid=726&pathid=2)
[52](https://github.com/Checkmarx/kics/blob/feature/filter_and_alarm_exist_for_changes_to_network_gateways/pkg/kics/service.go#L52) |Medium|Denial_Of_Service_Resource_Exhaustion|pkg/kics/service.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049055&projectid=726&pathid=1)

2020-12-31 13:52 UTC, rogeriopeixotocx approved these changes
LGTM

2020-12-31 13:52 UTC, merged