Add y_switch_avoid_manual_input query Closes #1088
Checkmarx/kics pull request #1182
Opened 2020-12-21 12:13 UTC by NunoAraujoCX

Closes #1088 
Check if we are using -y to avoid manual input 'yum install -y <package>'

2020-12-22 17:48 UTC, joaoReigota1 requested changes

2020-12-22 17:48 UTC, joaoReigota1 commented on assets/queries/dockerfile/y_switch_avoid_manual_input/query.rego
> +  contains(resource.Value[j], "yum install")
Need to check for "yum groupinstall", "yum localinstall" as well

2020-12-22 17:48 UTC, joaoReigota1 commented on assets/queries/dockerfile/y_switch_avoid_manual_input/query.rego
> +  not contains(resource.Value[j], "-y")
Need to check for flag "--assumeyes" as well

2020-12-22 17:48 UTC, joaoReigota1 commented on assets/queries/dockerfile/y_switch_avoid_manual_input/metadata.json
> +  "queryName": "Y Switch Avoid Manual Input",
The query name should reflect the vulnerability in an easy and comprehensible way
"yum_install_allows_manual_input"

2020-12-28 09:25 UTC, joaoReigota1 reviewed
Approved

2020-12-28 10:22 UTC, joelsou5a approved these changes

2020-12-28 10:22 UTC, merged