Add _ yum_update_disabled query Closes #1090
Checkmarx/kics pull request #1202
Opened 2020-12-21 14:13 UTC by NunoAraujoCX

Closes #1090 
Check if we are using yum update

2020-12-22 17:35 UTC, joaoReigota1 requested changes

2020-12-22 17:35 UTC, joaoReigota1 commented on assets/queries/dockerfile/yum_update_disabled/query.rego
> +}
Need to check for "yum update-to", "yum upgrade", "yum upgrade-to" as well

2020-12-22 17:35 UTC, joaoReigota1 commented on assets/queries/dockerfile/yum_update_disabled/metadata.json
> +  "descriptionText": "Do not use yum update",
Change description to explain the vulnerability

2020-12-28 10:07 UTC, joaoReigota1 commented
Approved

2020-12-28 11:07 UTC, ruigomescx approved these changes

2020-12-28 11:08 UTC, merged