Add SNS Topic Subscription Not Setted query
Checkmarx/kics pull request #1227
Opened 2020-12-21 16:01 UTC by fabioGoncalvesCx

Added new query for AWS CloudFormation.

Provide a CloudFormation resource and a resource to ensure that appropriate subscribers are setted to each SNS topic
Closes #1224

2020-12-29 11:22 UTC, rogeriopeixotocx requested changes
Requesting changes

2020-12-29 11:22 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/sns_topic_subscription_not_setted/metadata.json
> +}
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-29 11:22 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/sns_topic_subscription_not_setted/test/negative.yaml
> +      TopicName: alarm-action
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-29 11:22 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/sns_topic_subscription_not_setted/test/positive.yaml
> +      TopicName: alarm-action
[As a good POSIX practice](https://unix.stackexchange.com/a/18789) add end-of-file newline

2020-12-29 11:22 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/sns_topic_subscription_not_setted/metadata.json
> +  "queryName": "SNS Topic Subscription Not Setted",
Change **directory name** and **id** to: `sns_topic_without_subscriber`
Change **query name** to: `SNS Topic Without Subscriber`

2020-12-30 20:05 UTC, markmishaevcx commented
Scan submitted to Checkmarx

2020-12-30 20:10 UTC, markmishaevcx commented
![Logo](https://user-images.githubusercontent.com/23239410/92153465-ff743900-ee2c-11ea-9c8d-8141e38feb41.png)<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 4 vulnerabilities<br />![High](https://user-images.githubusercontent.com/23239410/92157087-97285600-ee32-11ea-988f-0aca12c4c126.png)&nbsp;**0 High**<br />![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3 Medium**<br />![Low](https://user-images.githubusercontent.com/23239410/92157091-98598300-ee32-11ea-8498-19bd7d62019b.png)&nbsp;**1 Low**<br />![Info](https://user-images.githubusercontent.com/23239410/92157090-97c0ec80-ee32-11ea-9b2e-aa6b32b03d54.png)&nbsp;**0 Info**<br />
### Violation Summary
![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049059&projectid=730)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[30](https://github.com/Checkmarx/kics/blob/feature/sns_topic_subscription_not_setted/cmd/builder/main.go#L30) |Medium|Path_Traversal|cmd/builder/main.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049059&projectid=730&pathid=3)
[52](https://github.com/Checkmarx/kics/blob/feature/sns_topic_subscription_not_setted/pkg/kics/service.go#L52) |Medium|Denial_Of_Service_Resource_Exhaustion|pkg/kics/service.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049059&projectid=730&pathid=1)
[81](https://github.com/Checkmarx/kics/blob/feature/sns_topic_subscription_not_setted/test/main_test.go#L81) |Medium|Denial_Of_Service_Resource_Exhaustion|test/main_test.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049059&projectid=730&pathid=2)

2020-12-31 14:07 UTC, rogeriopeixotocx approved these changes
LGTM

2020-12-31 14:07 UTC, merged