Add S3 Bucket Rules W/Master Key Null query #1246
Checkmarx/kics pull request #1248
Opened 2020-12-21 17:01 UTC by joelcarvalhocheckmarx

If algorithm is AES256 then the master key is null, empty or undefined, otherwise the master key is required

Closes #1246

2020-12-29 16:10 UTC, joaomartinscx requested changes

2020-12-29 16:10 UTC, joaomartinscx commented on assets/queries/ansible/s3_bucket_rules_with_awskms/query.rego
> +   check_key_id(s3_bucket)
The query description leads me to think that when the encryption algorithm is AES256, the master key should be empty/undefined, but you are not verifying it. Should you be?

2020-12-31 09:31 UTC, markmishaevcx commented
Scan submitted to Checkmarx

2020-12-31 09:36 UTC, markmishaevcx commented
![Logo](https://user-images.githubusercontent.com/23239410/92153465-ff743900-ee2c-11ea-9c8d-8141e38feb41.png)<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 4 vulnerabilities<br />![High](https://user-images.githubusercontent.com/23239410/92157087-97285600-ee32-11ea-988f-0aca12c4c126.png)&nbsp;**0 High**<br />![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3 Medium**<br />![Low](https://user-images.githubusercontent.com/23239410/92157091-98598300-ee32-11ea-8498-19bd7d62019b.png)&nbsp;**1 Low**<br />![Info](https://user-images.githubusercontent.com/23239410/92157090-97c0ec80-ee32-11ea-9b2e-aa6b32b03d54.png)&nbsp;**0 Info**<br />
### Violation Summary
![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049087&projectid=735)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[30](https://github.com/Checkmarx/kics/blob/feature/add_query_ansible_s3_bucket_rules_with_awskms/cmd/builder/main.go#L30) |Medium|Path_Traversal|cmd/builder/main.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049087&projectid=735&pathid=3)
[80](https://github.com/Checkmarx/kics/blob/feature/add_query_ansible_s3_bucket_rules_with_awskms/test/main_test.go#L80) |Medium|Denial_Of_Service_Resource_Exhaustion|test/main_test.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049087&projectid=735&pathid=2)
[52](https://github.com/Checkmarx/kics/blob/feature/add_query_ansible_s3_bucket_rules_with_awskms/pkg/kics/service.go#L52) |Medium|Denial_Of_Service_Resource_Exhaustion|pkg/kics/service.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049087&projectid=735&pathid=1)

2020-12-31 14:46 UTC, joaomartinscx approved these changes
Everything looks okay, good job!

2020-12-31 14:46 UTC, merged