Add KMS Key With Vulnerable Policy query #1257
Checkmarx/kics pull request #1275
Opened 2020-12-22 08:52 UTC by joelcarvalhocheckmarx

Checks if the policy is vulnerable and needs updating.

Closes #1257

2020-12-29 17:04 UTC, joaomartinscx requested changes

2020-12-29 17:04 UTC, joaomartinscx commented on assets/queries/ansible/aws/kms_key_with_vulnerable_policy/query.rego
> +            "keyActualValue": sprintf("name=%s.{{community.aws.aws_kms}}.policy is incorrect", [task.name]),
The correctness of the policy here is not clear, could you specify what is or is not expected in the resource?

2020-12-31 09:42 UTC, markmishaevcx commented
Scan submitted to Checkmarx

2020-12-31 09:47 UTC, markmishaevcx commented
![Logo](https://user-images.githubusercontent.com/23239410/92153465-ff743900-ee2c-11ea-9c8d-8141e38feb41.png)<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 4 vulnerabilities<br />![High](https://user-images.githubusercontent.com/23239410/92157087-97285600-ee32-11ea-988f-0aca12c4c126.png)&nbsp;**0 High**<br />![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3 Medium**<br />![Low](https://user-images.githubusercontent.com/23239410/92157091-98598300-ee32-11ea-8498-19bd7d62019b.png)&nbsp;**1 Low**<br />![Info](https://user-images.githubusercontent.com/23239410/92157090-97c0ec80-ee32-11ea-9b2e-aa6b32b03d54.png)&nbsp;**0 Info**<br />
### Violation Summary
![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049089&projectid=736)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[30](https://github.com/Checkmarx/kics/blob/feature/add_query_ansible_kms_key_with_vulnerable_policy/cmd/builder/main.go#L30) |Medium|Path_Traversal|cmd/builder/main.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049089&projectid=736&pathid=3)
[52](https://github.com/Checkmarx/kics/blob/feature/add_query_ansible_kms_key_with_vulnerable_policy/pkg/kics/service.go#L52) |Medium|Denial_Of_Service_Resource_Exhaustion|pkg/kics/service.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049089&projectid=736&pathid=1)
[82](https://github.com/Checkmarx/kics/blob/feature/add_query_ansible_kms_key_with_vulnerable_policy/test/main_test.go#L82) |Medium|Denial_Of_Service_Resource_Exhaustion|test/main_test.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049089&projectid=736&pathid=2)

2020-12-31 14:42 UTC, joaomartinscx approved these changes
Everything looks okay, good job!

2020-12-31 14:43 UTC, merged