Add use_json_in_cmd_and_entrypoint_arguments query Closes #1083
Checkmarx/kics pull request #1277
Opened 2020-12-22 09:39 UTC by NunoAraujoCX

Closes #1083
Check if we are using JSON arguments in CMD and ENTRYPOINT arguments

2020-12-22 15:23 UTC, joaoReigota1 requested changes

2020-12-22 15:23 UTC, joaoReigota1 commented on assets/queries/dockerfile/use_json_in_cmd_and_entrypoint_arguments/metadata.json
> +  "queryName": "Use JSON In CMD And ENTRYPOINT Arguments",
The query name should reflect the vulnerability not the fix

2020-12-28 10:14 UTC, joaoReigota1 reviewed
Approved

2020-12-28 10:16 UTC, joelsou5a approved these changes

2020-12-28 10:17 UTC, merged