Added New Query  IAM_Password_Without_Valid_Minimum_Length
Checkmarx/kics pull request #1292
Opened 2020-12-22 10:35 UTC by cataraujo190

Check if IAM account password policy enforces a minimum length and if that minimum is sufficient. Closes #1290

2020-12-29 11:19 UTC, Ruben-Silva requested changes

2020-12-29 11:19 UTC, Ruben-Silva commented on assets/queries/ansible/aws/iam_password_mininum_length/metadata.json
> +  "category": "IAM",
Change the category to "Network Security", and do the same in the corresponding Terraform query, please.

2020-12-29 11:19 UTC, Ruben-Silva commented on assets/queries/ansible/aws/iam_password_mininum_length/query.rego
> +}
The attribute 'min_pw_length' has an alias 'minimum_password_length'. Change these queries or add new ones to use when the alias is present.

2020-12-29 11:19 UTC, Ruben-Silva commented on assets/queries/ansible/aws/iam_password_mininum_length/test/positive.yaml
> +    pw_expire: false
Add samples with the alias "minimum_password_length", just to be more complete.

2020-12-30 10:28 UTC, rogeriopeixotocx approved these changes
LGTM

2020-12-30 10:29 UTC, rogeriopeixotocx reviewed
change directory name

2020-12-30 10:30 UTC, rogeriopeixotocx requested changes
directory name is wrong

2020-12-30 10:37 UTC, rogeriopeixotocx approved these changes
LGTM (for real now)

2020-12-30 10:37 UTC, merged