Add User Data Shell Script Is Encoded query #1413
Checkmarx/kics pull request #1414
Opened 2020-12-23 15:00 UTC by joelcarvalhocheckmarx

User Data Shell Script must be encoded

Closes #1413

2020-12-30 16:26 UTC, markmishaevcx commented
Scan submitted to Checkmarx

2020-12-30 16:31 UTC, markmishaevcx commented
![Logo](https://user-images.githubusercontent.com/23239410/92153465-ff743900-ee2c-11ea-9c8d-8141e38feb41.png)<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 4 vulnerabilities<br />![High](https://user-images.githubusercontent.com/23239410/92157087-97285600-ee32-11ea-988f-0aca12c4c126.png)&nbsp;**0 High**<br />![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3 Medium**<br />![Low](https://user-images.githubusercontent.com/23239410/92157091-98598300-ee32-11ea-8498-19bd7d62019b.png)&nbsp;**1 Low**<br />![Info](https://user-images.githubusercontent.com/23239410/92157090-97c0ec80-ee32-11ea-9b2e-aa6b32b03d54.png)&nbsp;**0 Info**<br />
### Violation Summary
![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049026&projectid=713)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[30](https://github.com/Checkmarx/kics/blob/feature/add_query_ansible_user_data_shell_script_encoded/cmd/builder/main.go#L30) |Medium|Path_Traversal|cmd/builder/main.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049026&projectid=713&pathid=3)
[52](https://github.com/Checkmarx/kics/blob/feature/add_query_ansible_user_data_shell_script_encoded/pkg/kics/service.go#L52) |Medium|Denial_Of_Service_Resource_Exhaustion|pkg/kics/service.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049026&projectid=713&pathid=1)
[83](https://github.com/Checkmarx/kics/blob/feature/add_query_ansible_user_data_shell_script_encoded/test/main_test.go#L83) |Medium|Denial_Of_Service_Resource_Exhaustion|test/main_test.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049026&projectid=713&pathid=2)

2020-12-30 16:47 UTC, joaomartinscx requested changes

2020-12-30 16:47 UTC, joaomartinscx commented on assets/queries/ansible/aws/user_data_shell_script_is_encoded/test/positive_expected_result.json
> +		"line": 1
Despite this being correct with the engine, the line that should be identified should be 9, where `user_data` is present

2020-12-31 14:36 UTC, joaomartinscx commented
The search key needs the resource name to distinguish different resources of the same type

2021-01-04 10:14 UTC, joaomartinscx approved these changes
Everything looks good to me, good job!

2021-01-04 10:15 UTC, merged