Add cloudtrail_logging_disabled query Closes #1575
Checkmarx/kics pull request #1579
Opened 2020-12-29 12:37 UTC by NunoAraujoCX

Closes #1575 
This query checks if the logging has been enabled

2020-12-30 14:54 UTC, joaoReigota1 requested changes

2020-12-30 14:54 UTC, joaoReigota1 commented on assets/queries/ansible/aws/cloudtrail_logging_disabled/query.rego
> +    task["community.aws.cloudtrail"].enable_logging == false
Ansible also allows "false" and "no" we should check for these issues using 
isAnsibleFalse(answer) {
     lower(answer) == "no"
} else {
     lower(answer) == "false"
} else {
     answer == false
}

2020-12-30 14:54 UTC, joaoReigota1 commented on assets/queries/ansible/aws/cloudtrail_logging_disabled/metadata.json
> +  "descriptionText": "Enables Logging for the trail",
The query description should point out the vulnerability being address or how to fix it

2020-12-31 09:44 UTC, markmishaevcx commented
Scan submitted to Checkmarx

2020-12-31 09:51 UTC, markmishaevcx commented
![Logo](https://user-images.githubusercontent.com/23239410/92153465-ff743900-ee2c-11ea-9c8d-8141e38feb41.png)<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 4 vulnerabilities<br />![High](https://user-images.githubusercontent.com/23239410/92157087-97285600-ee32-11ea-988f-0aca12c4c126.png)&nbsp;**0 High**<br />![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3 Medium**<br />![Low](https://user-images.githubusercontent.com/23239410/92157091-98598300-ee32-11ea-8498-19bd7d62019b.png)&nbsp;**1 Low**<br />![Info](https://user-images.githubusercontent.com/23239410/92157090-97c0ec80-ee32-11ea-9b2e-aa6b32b03d54.png)&nbsp;**0 Info**<br />
### Violation Summary
![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049090&projectid=737)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[30](https://github.com/Checkmarx/kics/blob/feature/ansible_enable_cloudtrail_logging/cmd/builder/main.go#L30) |Medium|Path_Traversal|cmd/builder/main.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049090&projectid=737&pathid=3)
[83](https://github.com/Checkmarx/kics/blob/feature/ansible_enable_cloudtrail_logging/test/main_test.go#L83) |Medium|Denial_Of_Service_Resource_Exhaustion|test/main_test.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049090&projectid=737&pathid=2)
[52](https://github.com/Checkmarx/kics/blob/feature/ansible_enable_cloudtrail_logging/pkg/kics/service.go#L52) |Medium|Denial_Of_Service_Resource_Exhaustion|pkg/kics/service.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049090&projectid=737&pathid=1)

2020-12-31 09:57 UTC, markmishaevcx commented
Scan not submitted to Checkmarx due to existing Active scan for the same project.

2020-12-31 09:59 UTC, joaoReigota1 approved these changes

2020-12-31 10:01 UTC, merged