Add S3 Bucket Without Encryption query #1624
Checkmarx/kics pull request #1626
Opened 2020-12-31 10:44 UTC by joelcarvalhocheckmarx

S3 bucket should have encryption defined

Closes #1624

2020-12-31 10:44 UTC, markmishaevcx commented
Scan submitted to Checkmarx

2020-12-31 10:49 UTC, joelsou5a requested changes

2020-12-31 10:49 UTC, joelsou5a commented on assets/queries/ansible/aws/s3_bucket_without_encryption/query.rego
> +}
I think the encryption is disabled only if you set it to "none" check the link bellow.

"Describes the default server-side encryption to apply to new objects in the bucket. **In order to remove the server-side encryption, the encryption needs to be set to 'none' explicitly**." Source:
https://docs.ansible.com/ansible/latest/collections/amazon/aws/s3_bucket_module.html#parameter-encryption

2020-12-31 10:51 UTC, markmishaevcx commented
![Logo](https://user-images.githubusercontent.com/23239410/92153465-ff743900-ee2c-11ea-9c8d-8141e38feb41.png)<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 4 vulnerabilities<br />![High](https://user-images.githubusercontent.com/23239410/92157087-97285600-ee32-11ea-988f-0aca12c4c126.png)&nbsp;**0 High**<br />![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3 Medium**<br />![Low](https://user-images.githubusercontent.com/23239410/92157091-98598300-ee32-11ea-8498-19bd7d62019b.png)&nbsp;**1 Low**<br />![Info](https://user-images.githubusercontent.com/23239410/92157090-97c0ec80-ee32-11ea-9b2e-aa6b32b03d54.png)&nbsp;**0 Info**<br />
### Violation Summary
![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049109&projectid=743)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[30](https://github.com/Checkmarx/kics/blob/feature/add_query_ansible_s3_bucket_without_encryption/cmd/builder/main.go#L30) |Medium|Path_Traversal|cmd/builder/main.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049109&projectid=743&pathid=3)
[83](https://github.com/Checkmarx/kics/blob/feature/add_query_ansible_s3_bucket_without_encryption/test/main_test.go#L83) |Medium|Denial_Of_Service_Resource_Exhaustion|test/main_test.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049109&projectid=743&pathid=2)
[52](https://github.com/Checkmarx/kics/blob/feature/add_query_ansible_s3_bucket_without_encryption/pkg/kics/service.go#L52) |Medium|Denial_Of_Service_Resource_Exhaustion|pkg/kics/service.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049109&projectid=743&pathid=1)

2021-01-08 16:27 UTC, ruigomescx approved these changes

2021-01-08 16:28 UTC, ruigomescx approved these changes

2021-01-08 16:29 UTC, merged