Add storage_account_tls_version query for Ansible
Checkmarx/kics pull request #1643
Opened 2020-12-31 12:32 UTC by mcarvalhox

This query evaluates if the latest version of TLS encryption (i.e. TLS1_2) is being used. 
Closes #1636

2020-12-31 12:32 UTC, markmishaevcx commented
Scan submitted to Checkmarx

2020-12-31 12:39 UTC, markmishaevcx commented
![Logo](https://user-images.githubusercontent.com/23239410/92153465-ff743900-ee2c-11ea-9c8d-8141e38feb41.png)<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 4 vulnerabilities<br />![High](https://user-images.githubusercontent.com/23239410/92157087-97285600-ee32-11ea-988f-0aca12c4c126.png)&nbsp;**0 High**<br />![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3 Medium**<br />![Low](https://user-images.githubusercontent.com/23239410/92157091-98598300-ee32-11ea-8498-19bd7d62019b.png)&nbsp;**1 Low**<br />![Info](https://user-images.githubusercontent.com/23239410/92157090-97c0ec80-ee32-11ea-9b2e-aa6b32b03d54.png)&nbsp;**0 Info**<br />
### Violation Summary
![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**3** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049140&projectid=758)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[30](https://github.com/Checkmarx/kics/blob/feature/storage_account_tls_version/cmd/builder/main.go#L30) |Medium|Path_Traversal|cmd/builder/main.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049140&projectid=758&pathid=3)
[52](https://github.com/Checkmarx/kics/blob/feature/storage_account_tls_version/pkg/kics/service.go#L52) |Medium|Denial_Of_Service_Resource_Exhaustion|pkg/kics/service.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049140&projectid=758&pathid=1)
[83](https://github.com/Checkmarx/kics/blob/feature/storage_account_tls_version/test/main_test.go#L83) |Medium|Denial_Of_Service_Resource_Exhaustion|test/main_test.go|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1049140&projectid=758&pathid=2)

2021-01-04 10:49 UTC, joaomartinscx requested changes

2021-01-04 10:49 UTC, joaomartinscx commented on assets/queries/ansible/azure/storage_account_tls_version/query.rego
> +}
How does this else enforce that the minimum tls version to be used is the latest? Keep in mind that the default value is tls1_0

2021-01-04 10:49 UTC, joaomartinscx commented on assets/queries/ansible/azure/storage_account_tls_version/metadata.json
> +  "queryName": "Storage Account TLS Version",
The query name should identify the vulnerability or fault, in this case, something like: "Storage Account Is Not Using Latest TLS Encryption Version"

2021-01-04 10:49 UTC, joaomartinscx commented on assets/queries/ansible/azure/storage_account_tls_version/metadata.json
> +  "category": "Storage",
Refactor category name according to the list given

2021-01-04 12:07 UTC, joaomartinscx approved these changes
Everything looks good to me, good job!

2021-01-04 12:07 UTC, merged