Added Rego Generic Functions
Checkmarx/kics pull request #1779
Opened 2021-01-11 13:38 UTC by joelsou5a

2021-01-12 12:02 UTC, rogeriopeixotocx approved these changes
~LGTM~

2021-01-15 14:28 UTC, rogeriopeixotocx commented
Although integration tests are passing, no queries are being loaded, I have a fix for that and I'm going to push to this branch.

![image](https://user-images.githubusercontent.com/75368139/104738850-f3cf4200-573d-11eb-8923-fa79f88c9fa9.png)

2021-01-15 14:30 UTC, rogeriopeixotocx requested changes

2021-01-15 14:30 UTC, rogeriopeixotocx commented on pkg/engine/query/source.go
> +	var genericPath = filepath.Join(basepath, basePath)
There's an issue here that is causing no queries to be loaded in integration tests.

2021-01-15 17:27 UTC, ruigomescx approved these changes

2021-01-15 17:28 UTC, merged