Improve logging to record scan elapsed time
Checkmarx/kics pull request #1834
Opened 2021-01-22 18:24 UTC by rogeriopeixotocx

Signed-off-by: Rogério Peixoto <rogerio.peixoto@checkmarx.com>

Closes #1805

**Proposed Changes**
- Logs and stdout now outputs the scan time duration in order to provide additional info

2021-01-25 18:29 UTC, felipe-avelar approved these changes
LGTM

2021-01-26 11:12 UTC, ruigomescx requested changes

2021-01-26 11:12 UTC, ruigomescx commented on internal/console/scan.go
> +	elapsedStrFormat := "Scan duration %v\n"
just add ':' to end of duration

2021-01-26 15:34 UTC, rogeriopeixotocx commented on internal/console/scan.go
> +	elapsedStrFormat := "Scan duration %v\n"
done!

2021-01-26 16:10 UTC, ruigomescx approved these changes

2021-01-26 16:10 UTC, merged