update docs with releases page and query development help
Checkmarx/kics pull request #1906
Opened 2021-01-29 18:34 UTC by ruigomescx

**Proposed Changes**

- added query development info
- releases page
- minor fixes / updates to docs

2021-01-29 18:37 UTC, nunoocx commented on docs/releases.md
> +- MINOR versions will new include functionality that is backwards compatible. This should have a monthly cadence.
will include

2021-01-29 18:38 UTC, nunoocx commented on docs/releases.md
> +If waiting for a the new release it's not enough, we also provide with nightly builds that include the latest changes.
for a new

2021-01-29 18:42 UTC, nunoocx requested changes
Review ...

2021-01-29 18:46 UTC, nunoocx approved these changes

2021-01-30 12:59 UTC, IgorMarkov approved these changes

2021-01-30 12:59 UTC, merged