Update labels and rules in 'StatefulSet Without PodDisruptionBudget' and 'Deployment Without PodDisruptionBudget'
Checkmarx/kics pull request #1960
Opened 2021-02-02 18:35 UTC by mcarvalhox

Closes #1957

**Proposed Changes**

- Added verification to ensure the number of replicas is higher than 1
- Added `spec.selector.matchLabels` to the searchKey, as it was not picking up the correct line in some samples
- The query was only comparing the matchLabels with key: app, now any key-value pair can be matched
- Changed the labels in negative.yaml, so that the PodDisruptionBudget only targets the workload from the same file

2021-02-03 15:49 UTC, joaoReigota1 requested changes

2021-02-03 15:49 UTC, joaoReigota1 commented on assets/queries/k8s/deployment_without_pod_disruption_budget/query.rego
>  	pdbs := [pdb | documents[index].kind == "PodDisruptionBudget"; pdb = documents[index]]
Don't iterate through every document, the query should look for PodDisruptionBudget inside the same document to prevent timeouts

2021-02-03 15:49 UTC, joaoReigota1 commented on assets/queries/k8s/statefulset_without_pod_disruption_budget/query.rego
>  	pdbs := [pdb | documents[index].kind == "PodDisruptionBudget"; pdb = documents[index]]
Don't iterate through every document, the query should look for PodDisruptionBudget inside the same document to prevent timeouts

2021-02-03 15:49 UTC, joaoReigota1 commented on assets/queries/k8s/deployment_without_pod_disruption_budget/query.rego
> +	array[a].spec.selector.matchLabels[_] == label[_]
CheckIFPdbExists is used in both 'deployment_without_pod_disruption_budget' and 'statefulset_without_pod_disruption_budget' to clear duplication pass this function to libraries/k8s/library.rego and import the function in both queries

2021-02-03 16:27 UTC, mcarvalhox commented on assets/queries/k8s/service_does_not_target_pod/test/positive.yaml
> +      targetPort: 8088
What's wrong with the indentation?

2021-02-18 11:52 UTC, ruigomescx requested changes

2021-02-18 11:52 UTC, ruigomescx commented on assets/libraries/k8s/library.rego
> +}
This function should not be in the generic libraries as it's too specific for a query. Also please change the name to a more appropriate name like "isPodDisruptionBudget"

2021-02-18 12:41 UTC, ruigomescx approved these changes

2021-02-18 12:41 UTC, merged