Fixed terraform queries with 'MissingAttribute' missing. Closes #1929
Checkmarx/kics pull request #1973
Opened 2021-02-04 12:59 UTC by joaomartinscx

Closes #1929

**Proposed Changes**

| Query Changed | Changes |
|-----------------|--------------|
| Auto Minor Version Upgrade Is Set To False | Add verification when the attribute is missing instead of incorrect |
| IAM Database Auth Not Enabled | Add verification when the attribute is missing instead of incorrect |
| DB Instance Storage Not Encrypted |  Add verification when the attribute is missing instead of incorrect and improve attribute retrieval with *object.get()* |
| Volume Snapshot Not Encrypted | Add verification when the attribute is missing instead of incorrect |
| EFS Is Not Encrypted | Add verification when the attribute is missing instead of incorrect. Fixed *searchKey* and expected result line |
| Launch Configuration Is Not Encrypted |  Add verification when the attribute is missing instead of incorrect. Fixed *searchKey*, positive sample and expected results line |
| Unprotected SQS Queue | Refactired result to present MissingAttribute instead of IncorrectValue and fixed expected result |
| Key Vault Soft Delete is Enabled | Add verification when the attribute is missing instead of incorrect. Refactored keyExpected/Actual values |
| Compute disk is not encrypted | Add verification when the attribute is missing instead of incorrect |
| Google project with default network | Add verification when the attribute is missing instead of incorrect.  Refactored keyExpected/Actual values |
| Project-wide SSH Keys Are Enabled In VM Instances | Add verification when the attribute is missing instead of incorrect |

2021-02-05 15:08 UTC, jorge-cruz requested changes

2021-02-08 10:15 UTC, joaomartinscx commented on assets/queries/terraform/aws/db_instance_auto_minor_version_upgrade_is_disabled/query.rego
> +}
Addressed requests

2021-02-09 14:54 UTC, jorge-cruz approved these changes

2021-02-12 17:21 UTC, ruigomescx approved these changes

2021-02-12 17:21 UTC, merged