Update Pod Is Not Targeted Net.Policy query #1975
Checkmarx/kics pull request #1976
Opened 2021-02-04 13:33 UTC by joelcarvalhocheckmarx

Closes #

**Proposed Changes**

- Refactor Query
- The query has many false positives, this is because the query never detects if the Pod or the NetworkPolicy is defined.
- Solution: Finds NetworkPolicy and Pod, if exists should be targeted.

2021-02-04 16:10 UTC, joaomartinscx requested changes

2021-02-04 16:10 UTC, joaomartinscx commented on assets/queries/k8s/pod_network_policy_not_configured/query.rego
> +    result := {
Fix indentation

2021-02-04 16:10 UTC, joaomartinscx commented on assets/queries/k8s/pod_network_policy_not_configured/query.rego
> +		"keyExpectedValue": "Pod is defined",
Try to be more clear on the expected value e.g. the deleted expectedValue

2021-02-04 16:10 UTC, joaomartinscx commented on assets/queries/k8s/pod_network_policy_not_configured/query.rego
> +		"keyActualValue": sprintf("metadata.name=%s should target at least one Pod", [metadata.name])
The ActualValue mentions what values the resource has that are faulty, so the message should reflect that, and not what there should be

2021-02-08 10:30 UTC, joaomartinscx approved these changes
Everything looks good to me, good job!

2021-02-17 13:12 UTC, rogeriopeixotocx commented
Sample coverage is not good yet:

![image](https://user-images.githubusercontent.com/75368139/108208808-6d819380-7121-11eb-9839-4dc68c9564bd.png)

we need to be mindful of performance and integration tests issues when iterating over all documents, lines:
https://github.com/Checkmarx/kics/pull/1976/files#diff-e0f0779359c491ebbe5def5c81a7cfa599340fedb4c8584e8e6c6a209a564fe3R47
https://github.com/Checkmarx/kics/pull/1976/files#diff-e0f0779359c491ebbe5def5c81a7cfa599340fedb4c8584e8e6c6a209a564fe3R42

I'll suggest an improvment.

cc: @joelcarvalhocheckmarx @ruigomescx

2021-03-05 14:59 UTC, ruigomescx approved these changes

2021-03-05 14:59 UTC, merged