Update unknown_port_exposed_to_internet Closes #2017
Checkmarx/kics pull request #2018
Opened 2021-02-08 17:00 UTC by NunoAraujoCX

Closes #2017 

**Proposed Changes**

- Query now checks for positives in queries with multiple ingresses
- Fixed query giving a false positive in the 'fully_open_ingress' positive file

2021-02-09 14:45 UTC, joaomartinscx requested changes

2021-02-09 14:45 UTC, joaomartinscx commented on assets/queries/terraform/aws/unknown_port_exposed_to_internet/query.rego
> +	]
Use library to address these known ports

2021-02-09 14:45 UTC, joaomartinscx commented on assets/queries/terraform/aws/unknown_port_exposed_to_internet/query.rego
> +	resource := input.document[i].resource.aws_security_group[name].ingress[x]
Tip: you could have just one check for the ingress, where you call a function like *getIngressList* where you check the type of variable, if it is an array, return the variable, if it is an object, return an array with the object inside. This way you can reuse the code and save a couple of lines.

2021-02-12 10:46 UTC, joaomartinscx approved these changes
Everything looks good to me, good job!

2021-02-12 17:30 UTC, ruigomescx approved these changes

2021-02-12 17:30 UTC, merged