Correcting inconsistencies and formatting in query names and folders Closes #1893
Checkmarx/kics pull request #2041
Opened 2021-02-10 12:19 UTC by rafaela-soares

Closes #1893

2021-02-12 16:40 UTC, jorge-cruz requested changes

2021-02-12 16:40 UTC, jorge-cruz commented on assets/queries/terraform/aws/cloudwatch_metrics_not_enabled/metadata.json
> +  "queryName": "CloudWatch Metrics Not enabled",
```suggestion
  "queryName": "CloudWatch Metrics Not Enabled",
```

2021-02-12 16:40 UTC, jorge-cruz commented on assets/queries/terraform/aws/eks_cluster_has_public_access/metadata.json
> +  "queryName": "EKS cluster Has Public Access",
```suggestion
  "queryName": "EKS Cluster Has Public Access",
```

2021-02-12 16:40 UTC, jorge-cruz commented on assets/queries/terraform/aws/eks_cluster_has_public_access_cidrs/metadata.json
> +  "queryName": "EKS cluster Has Public Access CIDRs",
```suggestion
  "queryName": "EKS Cluster Has Public Access CIDRs",
```

2021-02-12 16:40 UTC, jorge-cruz commented on assets/queries/terraform/aws/google_kms_crypto_key_rotation_period_not_recommended/metadata.json
> +  "descriptionText": "Make sure Encryption keys changes after 90 days",
```suggestion
  "descriptionText": "Make sure Encryption keys change after 90 days",
```

2021-02-12 16:40 UTC, jorge-cruz commented on assets/queries/terraform/aws/iam_policies_allow_all_in_policy_statement/metadata.json
> +  "queryName": "IAM Policies Allows All ('*') In Policy Statement",
```suggestion
  "queryName": "IAM Policy Allows All ('*') In Policy Statement",
```

2021-02-12 16:40 UTC, jorge-cruz commented on assets/queries/terraform/aws/neptune_cluster_not_encrypted/metadata.json
> +  "descriptionText": "Check if Neptune Cluster Storage is securely encypted",
```suggestion
  "descriptionText": "Check if Neptune Cluster Storage is securely encrypted",
```

2021-02-12 16:40 UTC, jorge-cruz commented on assets/queries/terraform/aws/sqs_with_sse_disabled/metadata.json
> +  "queryName": "SQS With SSE disabled",
```suggestion
  "queryName": "SQS With SSE Disabled",
```

2021-02-12 16:40 UTC, jorge-cruz commented on assets/queries/terraform/azure/postgre_sql_server_without_connection_throttling/metadata.json
> +  "descriptionText": "Make sure that for PostgreSQL server, Connection Throttling is set",
```suggestion
  "descriptionText": "Ensure that Connection Throttling is set for the PostgreSQL server",
```

2021-02-19 12:03 UTC, jorge-cruz submitted a review, later dismissed

2021-02-19 12:43 UTC, rogeriopeixotocx commented
I used this script to rename all query dirs to lowercase and life is good:

```
#!/usr/bin/env python3
import glob
import os

def joinp(*arr):
  return os.sep.join(arr)

glob_result = []
glob_result = glob.glob(joinp("assets","queries","ansible","**", "*"))
glob_result.extend(glob.glob(joinp("assets","queries","terraform","**", "*")))
glob_result.extend(glob.glob(joinp("assets","queries","cloudFormation","**")))
glob_result.extend(glob.glob(joinp("assets","queries","dockerfile","**")))
glob_result.extend(glob.glob(joinp("assets","queries","k8s","**")))
dirs = [path for path in glob_result if os.path.isdir(path)]
for directory in dirs:
  base_dir = os.sep.join(directory.split(os.sep)[:3])
  query_dir = os.sep.join(directory.split(os.sep)[3:])
  if any(x.isupper() for x in query_dir):
    lower_query_dir = joinp(base_dir, query_dir.lower())
    print(f"renaming {directory} to {lower_query_dir}")
    os.rename(directory, lower_query_dir)
```
cc: @ruigomescx @rafaela-soares

2021-02-19 15:00 UTC, jorge-cruz approved these changes

2021-02-19 16:51 UTC, merged