Update roadmap.md
Checkmarx/kics pull request #2079
Opened 2021-02-14 07:02 UTC by oribendetcx

Closes #

**Proposed Changes**
Added hard-coded keys task
-
-
-
I submit this contribution under Apache-2.0 license.

2021-02-15 23:45 UTC, rogeriopeixotocx requested changes

2021-02-15 23:45 UTC, rogeriopeixotocx commented on docs/roadmap.md
> +| Completed | Hard-coded secrects key detection |  |
"secret keys"

2021-02-16 19:33 UTC, IgorMarkov approved these changes

2021-02-16 19:35 UTC, IgorMarkov approved these changes

2021-02-16 19:35 UTC, IgorMarkov approved these changes

2021-02-16 19:59 UTC, merged