Revised documentation files
Checkmarx/kics pull request #2109
Opened 2021-02-19 15:29 UTC by nunoocx

Closes #2091

**Proposed Changes**

- Complete revision of documentation
- Revised Integrations section
- Added integration section for Azure Pipelines

I submit this contribution under Apache-2.0 license.

2021-02-19 15:41 UTC, ruigomescx requested changes

2021-02-19 15:41 UTC, ruigomescx commented on README.md
> +Setting up and using KICS is super-easy.
This sentence is repeated

2021-02-19 16:51 UTC, rogeriopeixotocx requested changes

2021-02-19 16:51 UTC, rogeriopeixotocx commented on docs/integrations_azurepipelines.md
> +          if [
missing if condition

2021-02-19 16:51 UTC, rogeriopeixotocx commented on docs/integrations_azurepipelines.md
> +  # variables: # several syntaxes, see specific section
this comment is not needed

2021-02-19 16:51 UTC, rogeriopeixotocx commented on docs/integrations_azurepipelines.md
> +if [
missing if condition

2021-02-19 16:51 UTC, rogeriopeixotocx commented on docs/integrations_azurepipelines.md
> +          TOTAL_SEVERITY_COUNTER=`grep '"totalCounter"':' ' kics-results.json | awk {'print $2'}`
`"total_counter"`

2021-02-19 16:51 UTC, rogeriopeixotocx commented on docs/integrations_gitlabci.md
> +    - export TOTAL_SEVERITY_COUNTER=`grep '"totalCounter"':' ' kics-results.json | awk {'print $2'}`
`"total_counter"`

2021-02-19 16:51 UTC, rogeriopeixotocx commented on docs/integrations_azurepipelines.md
> +TOTAL_SEVERITY_COUNTER=`grep '"totalCounter"':' ' kics-results.json | awk {'print $2'}`
`"total_counter"`

2021-02-19 16:51 UTC, rogeriopeixotocx commented on docs/integrations_azurepipelines.md
> +if [
`if [ "$SEVERITY_COUNTER_HIGH" -ge "1" ]; then`

2021-02-19 16:51 UTC, rogeriopeixotocx commented on docs/integrations_azurepipelines.md
> +          if [
`if [ "$SEVERITY_COUNTER_HIGH" -ge "1" ]; then`

2021-02-19 16:51 UTC, rogeriopeixotocx commented on docs/integrations_gitlabci.md
> +    - export TOTAL_SEVERITY_COUNTER=`grep '"totalCounter"':' ' kics-results.json | awk {'print $2'}`
`"total_counter"`

2021-02-19 17:09 UTC, ruigomescx commented
Codacy is reporting the following issues:
https://app.codacy.com/gh/Checkmarx/kics/pullRequest?prid=6982531

2021-02-21 07:30 UTC, IgorMarkov approved these changes

2021-02-21 09:02 UTC, IgorMarkov approved these changes

2021-02-21 09:03 UTC, IgorMarkov approved these changes

2021-02-22 08:53 UTC, rogeriopeixotocx approved these changes
LGTM

2021-02-22 08:55 UTC, merged