Added exclude-categories flag
Checkmarx/kics pull request #2190
Opened 2021-03-08 11:23 UTC by felipe-avelar

Closes #2161 

**Proposed Changes**

- Now it is possible to exclude queries by its category
I submit this contribution under Apache-2.0 license.

2021-03-09 14:28 UTC, rogeriopeixotocx commented
@felipe-avelar please resolve conflicts

2021-03-12 16:35 UTC, rogeriopeixotocx requested changes

2021-03-12 16:35 UTC, rogeriopeixotocx commented on internal/console/scan.go
> +		"exclude categories by providing its name\n"+
... `providing it's name\n`

2021-03-12 16:37 UTC, rogeriopeixotocx approved these changes
LGTM

2021-03-12 17:51 UTC, joaoReigota1 approved these changes
LGTM

2021-03-12 17:55 UTC, ruigomescx approved these changes

2021-03-12 18:01 UTC, merged