Add "GuardDuty Detector Disabled" query for CloudFormation #2297
Checkmarx/kics pull request #2299
Opened 2021-03-18 16:14 UTC by pedro-mimoso

Closes #2297 

Make sure that Amazon GuardDuty is Enabled.

2021-03-22 14:40 UTC, Ruben-Silva requested changes

2021-03-22 14:40 UTC, Ruben-Silva commented on assets/queries/cloudFormation/guardduty_detector_disabled/query.rego
> +		"keyActualValue": "GuardDuty Detector is not Enabled",
Change to:

"keyExpectedValue": sprintf("Resources.%s.Properties.Enable" is set to true, [name]),
		"keyActualValue": sprintf("Resources.%s.Properties.Enable" is set to false, [name]),

2021-03-22 14:40 UTC, Ruben-Silva commented on assets/queries/cloudFormation/guardduty_detector_disabled/test/negative2.json
> +        "mydetector": {
Change "mydetector" to "mydetector2"

2021-03-22 14:40 UTC, Ruben-Silva commented on assets/queries/cloudFormation/guardduty_detector_disabled/test/positive1.yaml
> +  mydetector:
Change "mydetector" to "mydetector3"

2021-03-22 14:40 UTC, Ruben-Silva commented on assets/queries/cloudFormation/guardduty_detector_disabled/test/positive2.json
> +    "mydetector": {
Change "mydetector" to "mydetector4"

2021-03-22 15:18 UTC, Ruben-Silva approved these changes
Looks good to me!

2021-03-23 12:16 UTC, ruigomescx approved these changes

2021-03-23 12:17 UTC, merged