Add "API Gateway With Open Access" query for Terraform
Checkmarx/kics pull request #2310
Opened 2021-03-18 17:42 UTC by mcarvalhox

Closes #2307

**Proposed Changes**

- Add support in Terraform for a query with the same name already implemented in CloudFormation.
- The query checks if the authorization type is restricted in API Gateway Method resource (therefore being different from `NONE`). The authorization type can only be `NONE` when the http method is `OPTIONS`.

2021-03-22 10:18 UTC, Ruben-Silva requested changes

2021-03-22 10:18 UTC, Ruben-Silva commented on assets/queries/terraform/aws/api_gateway_with_open_access/query.rego
> +		"searchKey": sprintf("aws_api_gateway_method[%s].authorization", [name]),
Should be "http_method" instead of "authorization"?

"searchKey": sprintf("aws_api_gateway_method[%s].http_method", [name]),

2021-03-22 10:18 UTC, Ruben-Silva commented on assets/queries/terraform/aws/api_gateway_with_open_access/test/negative.tf
> +resource "aws_api_gateway_method" "positive1" {
Resource name is "positive1" in negative sample. Use "negative1" instead.

2021-03-22 13:53 UTC, Ruben-Silva approved these changes
Looks good to me!

2021-03-23 12:22 UTC, ruigomescx approved these changes

2021-03-23 12:23 UTC, merged