Add "API Gateway Stage Without API Gateway UsagePlan Associated" query for Terraform
Checkmarx/kics pull request #2341
Opened 2021-03-19 16:05 UTC by mcarvalhox

Closes #2340

**Proposed Changes**

- Add support for query "API Gateway Stage Without API Gateway UsagePlan Associated".
- The query checks if there's an API Gateway UsagePlan resource that references an API Gateway Stage, through attributes `stage` and `api_id`, that should be same as `stage_name` and `rest_api_id`.

I submit this contribution under Apache-2.0 license.

2021-03-22 14:36 UTC, Ruben-Silva requested changes

2021-03-22 14:36 UTC, Ruben-Silva commented on assets/queries/terraform/aws/api_gateway_stage_without_api_gateway_usage_plan_associated/test/positive.tf
> +resource "aws_api_gateway_usage_plan" "positive3" {
Add another `aws_api_gateway_stage` that is actually connected to the `aws_api_gateway_usage_plan`.

2021-03-22 16:26 UTC, Ruben-Silva approved these changes
Looks good to me!

2021-03-24 12:08 UTC, ruigomescx approved these changes

2021-03-24 12:08 UTC, merged