Add "GitHub Repository Set To Public" query for CloudFormation Closes #2342
Checkmarx/kics pull request #2343
Opened 2021-03-19 16:40 UTC by rafaela-soares

Closes #2342

**Proposed Changes**

- Support "GitHub Repository Set To Public" query for CloudFormation (same as "GitHub Repository Set To Public" for Terraform). It is necessary to check if the attribute `isPrivate` is set to true

I submit this contribution under Apache-2.0 license.

2021-03-22 11:03 UTC, Ruben-Silva requested changes

2021-03-22 11:03 UTC, Ruben-Silva commented on assets/queries/cloudFormation/github_repository_set_to_public/test/negative1.yaml
> +  MyRepo:
Change the name of the resources between the files, please.

2021-03-22 11:54 UTC, Ruben-Silva approved these changes
Looks good to me!

2021-03-23 16:44 UTC, ruigomescx approved these changes

2021-03-23 16:44 UTC, merged