Add "IAM Role Allows All Principals To Assume" query for CloudFormation Closes #2351
Checkmarx/kics pull request #2353
Opened 2021-03-22 09:22 UTC by rafaela-soares

Closes #2351

**Proposed Changes**

- Support "IAM Role Allows All Principals To Assume" query for CloudFormation (same as "IAM Role Allows All Principals To Assume" for Terraform and Ansible). It is necessary to check if IAM role denies "arn:aws:iam::root" principal.
- Add "allowsAllPrincipalsToAssume" to common library

I submit this contribution under Apache-2.0 license.

2021-03-22 11:22 UTC, Ruben-Silva submitted a review, later dismissed
Looks good to me!

2021-03-23 16:37 UTC, ruigomescx requested changes

2021-03-23 16:37 UTC, ruigomescx commented on assets/libraries/common/library.rego
> +
can we add a comment before the function to briefly explain what it does?

2021-03-23 16:53 UTC, ruigomescx requested changes

2021-03-23 16:53 UTC, ruigomescx commented on assets/libraries/common/library.rego
> +}
can we add a comment before the function to briefly explain what it does?

2021-03-23 17:36 UTC, ruigomescx approved these changes

2021-03-23 17:37 UTC, merged