Add "PSP With Added Capabilities" query for Terraform Closes #2355
Checkmarx/kics pull request #2357
Opened 2021-03-22 09:41 UTC by rafaela-soares

Closes #2355

**Proposed Changes**

- Support "PSP With Added Capabilities" query for Terraform (same as "PSP With Added Capabilities" for Kubernetes). It is necessary to check if the attribute `allowed_capabilities` is set 

I submit this contribution under Apache-2.0 license.

2021-03-22 11:27 UTC, Ruben-Silva requested changes

2021-03-22 11:27 UTC, Ruben-Silva commented on assets/queries/terraform/kubernetes_pod/psp_with_added_capabilities/test/positive.tf
> +resource "kubernetes_pod_security_policy" "example" {
Change the name of the resources between samples, please.

2021-03-22 11:50 UTC, Ruben-Silva approved these changes
Looks good to me!

2021-03-23 15:32 UTC, ruigomescx approved these changes

2021-03-23 15:33 UTC, merged