Add API Gateway Without SSL Certificate query for CloudFormation #2358
Checkmarx/kics pull request #2359
Opened 2021-03-22 10:05 UTC by pedro-mimoso

Closes #2358 

Add query API Gateway Without SSL Certificate, that checks if SSL Client Certificate exists.

I submit this contribution under Apache-2.0 license.

2021-03-22 11:31 UTC, Ruben-Silva requested changes

2021-03-22 11:31 UTC, Ruben-Silva commented on assets/queries/cloudFormation/api_gateway_without_ssl_certificate/test/negative1.yaml
> +  ProdApiGatewayStage:
Change the names of the resource between the different samples, please.

2021-03-22 14:08 UTC, Ruben-Silva approved these changes
Looks good to me!

2021-03-23 15:34 UTC, ruigomescx approved these changes

2021-03-23 16:04 UTC, ruigomescx approved these changes

2021-03-23 16:04 UTC, merged