Add "API Gateway X-Ray Disabled" query for CloudFormation #2365
Checkmarx/kics pull request #2366
Opened 2021-03-22 12:21 UTC by pedro-mimoso

Closes #2365 

**Proposed Changes**

Add "API Gateway X-Ray Disabled" query for CloudFormation

I submit this contribution under Apache-2.0 license.

2021-03-22 14:28 UTC, Ruben-Silva requested changes

2021-03-22 14:28 UTC, Ruben-Silva commented on assets/queries/cloudFormation/api_gateway_xray_disabled/query.rego
> +		"keyActualValue": sprintf("Resources.%s.Properties.TracingEnabled is true", [name]),
Swapped keyExpected and keyActual? Should be:

"keyExpectedValue": sprintf("Resources.%s.Properties.TracingEnabled is true", [name]),
		"keyActualValue": sprintf("Resources.%s.Properties.TracingEnabled is false", [name]),

2021-03-22 14:28 UTC, Ruben-Silva commented on assets/queries/cloudFormation/api_gateway_xray_disabled/test/negative2.json
> +    "ProdNeg": {
Change "ProdNeg" to "ProdNeg2"

2021-03-22 14:28 UTC, Ruben-Silva commented on assets/queries/cloudFormation/api_gateway_xray_disabled/test/positive3.json
> +    "ProdPos1": {
Change "ProdPos1" to "ProdPos3"

2021-03-22 14:28 UTC, Ruben-Silva commented on assets/queries/cloudFormation/api_gateway_xray_disabled/test/positive4.json
> +    "ProdPos2": {
Change "ProdPos2" to "ProdPos4"

2021-03-22 15:24 UTC, Ruben-Silva submitted a review, later dismissed
Looks good to me!

2021-03-23 15:39 UTC, ruigomescx approved these changes

2021-03-23 16:03 UTC, ruigomescx approved these changes

2021-03-23 16:04 UTC, merged