Add "CloudWatch Metrics Disabled" query for CloudFormation #2544
Checkmarx/kics pull request #2545
Opened 2021-03-29 09:49 UTC by pedro-mimoso

Closes #2544 

**Proposed Changes**

- Add "CloudWatch Metrics Disabled" query for CloudFormation;
- Change Terraform "CloudWatch Metrics Not Enabled" query name to "CloudWatch Metrics Disabled";

I submit this contribution under Apache-2.0 license.

2021-03-29 16:17 UTC, Ruben-Silva approved these changes
Looks good to me!

2021-03-30 09:05 UTC, rogeriopeixotocx requested changes
let's improve the description

2021-03-30 09:05 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/cloudwatch_metrics_disabled/metadata.json
> +  "descriptionText": "See if CloudWatch Metrics is Enabled",
`"Checks if..."`

2021-03-30 09:05 UTC, rogeriopeixotocx commented on assets/queries/cloudFormation/cloudwatch_metrics_disabled/metadata.json
> +  "descriptionText": "See if CloudWatch Metrics is Enabled",
`"Checks if..."`

2021-03-30 14:15 UTC, rogeriopeixotocx approved these changes
LGTM

2021-03-30 14:15 UTC, merged