Add "User Data Shell Script Is Encoded"query for CloudFormation #2618
Checkmarx/kics pull request #2620
Opened 2021-03-30 14:29 UTC by jorge-cruz

Closes #2618 

**Proposed Changes**

- Add "User Data Shell Script Is Encoded" query for CloudFormation

I submit this contribution under Apache-2.0 license.

2021-03-30 14:57 UTC, joaomartinscx commented
I think the CloudFormation resource you should be looking for is this one: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html#cfn-as-launchconfig-userdata

In addition, you forgot to update the query name in terraform with the unified name.

2021-03-30 14:57 UTC, joaomartinscx requested changes
I think the CloudFormation resource you should be looking for is this one: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html#cfn-as-launchconfig-userdata

In addition, you forgot to update the query name in terraform with the unified name.

2021-03-31 14:02 UTC, joaomartinscx approved these changes
Looks good to me, good job!

2021-03-31 14:07 UTC, ruigomescx approved these changes

2021-03-31 14:07 UTC, merged