Added "Global security array has an empty object" query
Checkmarx/kics pull request #2828
Opened 2021-04-14 15:48 UTC by felipe-avelar

Closes #2818 

**Proposed Changes**
- Added "Global security array has an empty object" query for Open API

I submit this contribution under Apache-2.0 license.

2021-04-15 11:10 UTC, joaoReigota1 submitted a review, later dismissed
LGTM

2021-04-15 12:58 UTC, rogeriopeixotocx requested changes

2021-04-15 12:58 UTC, rogeriopeixotocx commented on assets/queries/openAPI/security_empty_object_definition/query.rego
> +	openAPILib.checkOpenAPI(doc) != "undefined"
```suggestion
	openAPILib.check_openapi(doc) != "undefined"
```

2021-04-15 12:58 UTC, rogeriopeixotocx commented on assets/queries/openAPI/security_empty_object_definition/query.rego
> +	openAPILib.checkOpenAPI(doc) != "undefined"
```suggestion
	openAPILib.check_openapi(doc) != "undefined"
```

2021-04-16 08:50 UTC, joaoReigota1 approved these changes
LGTM

2021-04-16 13:57 UTC, rogeriopeixotocx approved these changes

2021-04-16 13:58 UTC, merged