feat(query): "Invalid Global External Documentation URL" for OpenAPI (#2999)
Checkmarx/kics pull request #3000
Opened 2021-04-26 11:54 UTC by rafaela-soares

Signed-off-by: Rafaela Soares rafaela.soares@checkmarx.com

Closes #2999

**Proposed Changes**
- Added "Invalid Global External Documentation URL" query for OpenAPI (it checks if 'externalDocs.url' is not a valid URL)

I submit this contribution under Apache-2.0 license.

2021-04-28 12:47 UTC, rogeriopeixotocx requested changes

2021-04-28 12:47 UTC, rogeriopeixotocx commented on assets/queries/openAPI/invalid_global_external_documentation_url/test/negative2.yaml
> +  url: http://docs.my-api.com/store-orders.htm
`.htm` is accepted?

2021-04-28 14:15 UTC, rafaela-soares commented on assets/queries/openAPI/invalid_global_external_documentation_url/test/negative2.yaml
> +  url: http://docs.my-api.com/store-orders.htm
Yes, https://regex101.com/r/URNBdA/1

2021-05-04 19:17 UTC, rogeriopeixotocx approved these changes

2021-05-04 19:18 UTC, merged