feat(query): "Encoding Header 'Content-Type' Improperly Defined" for OpenAPI (#3024)
Checkmarx/kics pull request #3025
Opened 2021-04-27 15:20 UTC by rafaela-soares

Signed-off-by: Rafaela Soares rafaela.soares@checkmarx.com

Closes #3024

**Proposed Changes**
- Added "Encoding Header 'Content-Type' Improperly Defined" query for OpenAPI. It checks if  'encoding[e]' defines 'Content-Type' in the 'headers' field

**Considerations**:
- The Media Type Object exists in Content.
- The Content exists in Responses Object and Request Body Object.
- The Responses Object exists in Component Object and Operation Object.
- The Request Body Object exists in Components Object and Operation Object.

I submit this contribution under Apache-2.0 license.

2021-04-30 10:50 UTC, felipe-avelar requested changes
Please, check comments

2021-04-30 10:50 UTC, felipe-avelar commented on assets/queries/openAPI/encoding_header_content_type_improperly_defined/query.rego
> +	header := doc.paths[path][operation].responses[r].content[c].encoding[e].headers[h]
I think `.content[c].encoding[e].headers[h]` is duplicated in too many lines... Shouldn't be better create a function `check_content_header` and make checks inside this function?

2021-05-03 09:21 UTC, felipe-avelar approved these changes
LGTM

2021-05-03 11:27 UTC, rogeriopeixotocx approved these changes
LGTM

2021-05-03 11:28 UTC, merged