feat(query): "API Key Exposed" for OpenAPI
Checkmarx/kics pull request #3332
Opened 2021-05-14 18:42 UTC by rafaela-soares

Signed-off-by: Rafaela Soares rafaela.soares@checkmarx.com

**Proposed Changes**
- Added "API Key Exposed" query for OpenAPI. It checks if the API Key is transported over the network header, cookie or query parameters

I submit this contribution under Apache-2.0 license.

2021-05-17 16:13 UTC, felipe-avelar requested changes
Check comment, please

2021-05-17 16:13 UTC, felipe-avelar commented on assets/queries/openAPI/api_key_exposed_in_global_security/query.rego
> +	doc.components.securitySchemes[s].in == ins[z]
Since the problem is using `apiKey` type, I think we could check `doc.components.securitySchemes[s].type == "apiKey`, no?

2021-05-18 15:42 UTC, felipe-avelar approved these changes
LGTM

2021-05-19 07:52 UTC, rogeriopeixotocx approved these changes
LGTM

2021-05-19 07:52 UTC, merged