fix(query): fixed issue container_ruuiing_as_root#3412
Checkmarx/kics pull request #3422
Opened 2021-05-24 13:32 UTC by mukeshpilaniya

**This is a fix of issue#3412:Containers_running_as_root query failed to evaluate**

_Added one more corner case_ and fixed already existing issue#3412
<pre>
#if pod runAsNonRoot==true and container runAsNonRoot==true (container not runs as root)
#if pod runAsNonRoot==true and container runAsNonRoot==false 
							#if container runAsUser>0 (container not runs as root)
							#if container runAsUser<=0 (container runs as root) //new added corner case
</pre>

2021-05-24 13:54 UTC, kaplanlior commented
Hi @mukeshpilaniya , first welcome to KICS, we're happy to get a PR from you :+1: 

A bit on the OCD side, but can you fix the typo in the PR/commit? container_ruuiing_as_root -> containers_running_as_root and to close the issue it refers (see [this](https://docs.github.com/en/github/managing-your-work-on-github/managing-your-work-with-issues-and-pull-requests/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) ).

Thanks (:

2021-05-24 15:41 UTC, felipe-avelar requested changes
In general, I think the query changes looks good, I would like just to ask to you to add positive and negative samples covering your new edge case.
If you need some help with this, don't hesitate to ask by @ us at this thread, using gitter or kics@checkmarx.com

2021-05-24 15:41 UTC, felipe-avelar commented on assets/queries/k8s/containers_running_as_root/query.rego
> +}
Please add a new line here

2021-05-25 08:15 UTC, rogeriopeixotocx approved these changes
LGTM, thank you @mukeshpilaniya

2021-05-25 09:53 UTC, rogeriopeixotocx commented
This PR should fix the integration tests issue https://github.com/Checkmarx/kics/pull/3430

2021-05-25 13:38 UTC, rogeriopeixotocx commented
Hi @mukeshpilaniya, now that https://github.com/Checkmarx/kics/pull/3430 is merged can you please update your branch to the master so we can run the PR checks again?

2021-05-25 14:16 UTC, mukeshpilaniya commented
> Hi @mukeshpilaniya, now that #3430 is merged can you please update your branch to the master so we can run the PR checks again?

@rogeriopeixotocx, I updated my branch to the master branch. now you can run the Integration test again.

2021-05-25 16:40 UTC, joaoReigota1 commented
> > Hi @mukeshpilaniya, now that #3430 is merged can you please update your branch to the master so we can run the PR checks again?
> 
> @rogeriopeixotocx, I updated my branch to the master branch. now you can run the Integration test again.

Hi @mukeshpilaniya, I think you forgot to pull the latest changes in the master branch, can you pull and then merge?

2021-05-25 21:24 UTC, rogeriopeixotocx approved these changes
LGTM

2021-05-25 21:24 UTC, merged

2021-05-25 21:25 UTC, rogeriopeixotocx commented
@mukeshpilaniya thank you for your contribution