feat(query): Added Path Parameter With No Corresponding Template Path (v2) query to Swagger 2.0
Checkmarx/kics pull request #3582
Opened 2021-06-08 08:50 UTC by joaoReigota1

**Proposed Changes**
- Added Path Parameter With No Corresponding Template Path (v2) query to Swagger 2.0

I submit this contribution under the Apache-2.0 license.

2021-06-08 14:19 UTC, joaoReigota1 commented
LGTM

2021-06-08 16:56 UTC, felipe-avelar requested changes
Needs to add "(v3)" to `queryName`

2021-06-08 17:15 UTC, rogeriopeixotocx submitted a review, later dismissed

2021-06-08 17:15 UTC, rogeriopeixotocx commented on assets/queries/openAPI/general/path_parameter_with_no_corresponding_template_path/test/positive_expected_result.json
> +    "queryName": "Path Parameter With No Corresponding Template Path",
v3 missing

2021-06-11 14:39 UTC, felipe-avelar approved these changes
LGTM

2021-06-11 14:40 UTC, merged