feat(query): moved 'Global Security Field Is Undefined' to general
Checkmarx/kics pull request #3594
Opened 2021-06-08 13:25 UTC by rafaela-soares

Signed-off-by: Rafaela Soares <rafaela.soares@checkmarx.com>

**Proposed Changes**
- Moved "Global Security Field Is Undefined" query to general

I submit this contribution under the Apache-2.0 license.

2021-06-08 16:14 UTC, felipe-avelar requested changes
Please, check comments

2021-06-08 16:14 UTC, felipe-avelar commented on assets/queries/openAPI/general/global_security_field_undefined/query.rego
> +		"keyActualValue": "A default security scheme is not defined",
I think we could use "security property" instead "security scheme", since security scheme is an object from 3.0

2021-06-09 14:26 UTC, rogeriopeixotocx commented
@rafaela-soares can you please update your branch with the current master?

2021-06-11 10:05 UTC, felipe-avelar approved these changes
LGTM

2021-06-11 10:05 UTC, merged