Add "Storage Share File Allows All ACL Permissions" query for Terraform (Closes #3655)
Checkmarx/kics pull request #3656
Opened 2021-06-15 10:07 UTC by cosmicgirl97

Closes #3655

**Proposed Changes**
- Add "Storage Share File Allows All ACL Permissions" query for Terraform (ensure least privileges)

I submit this contribution under the Apache-2.0 license.

2021-06-17 10:01 UTC, joaoReigota1 requested changes

2021-06-17 10:01 UTC, joaoReigota1 commented on assets/queries/terraform/azure/storage_share_file_allows_all_acl_permissions/query.rego
> +		"searchKey": sprintf("azurerm_storage_share_file[%s].storage_share_id", [name]),
maybe here is better to point to `azurerm_storage_share[%s].acl.access_policy.permissions` since it is here that changes need to be made.

2021-06-18 08:56 UTC, joaoReigota1 approved these changes
LGTM

2021-06-18 09:07 UTC, rogeriopeixotocx approved these changes
LGTM

2021-06-18 09:07 UTC, merged