feat(query): Added Global Schema Definition Not Being Used query to Swagger
Checkmarx/kics pull request #3698
Opened 2021-06-18 08:45 UTC by joaoReigota1

Signed-off-by: João Reigota <joao.reigota@checkmarx.com>

Closes #

**Proposed Changes**
- Added Global Schema Definition Not Being Used query to Swagger

All global schemas definitions should be in use

I submit this contribution under the Apache-2.0 license.

2021-06-18 09:19 UTC, rogeriopeixotocx requested changes

2021-06-18 09:19 UTC, rogeriopeixotocx commented on assets/libraries/openapi/library.rego
> +check_defenitions(doc, object, name) {
```suggestion
check_definitions(doc, object, name) {
```
small typo

2021-06-18 09:19 UTC, rogeriopeixotocx commented on assets/queries/openAPI/2.0/unused_schema_definition/query.rego
> +	openapi_lib.check_defenitions(doc, "definitions", name)
```suggestion
	openapi_lib.check_definitions(doc, "definitions", name)
```

2021-06-21 13:42 UTC, rafaela-soares requested changes

2021-06-21 13:42 UTC, rafaela-soares commented on assets/queries/openAPI/2.0/unused_schema_definition/test/negative1.json
> +            "desc": {
`desc` is not a valid value. Maybe we could delete it. The same happens in the other samples

2021-06-22 11:59 UTC, rogeriopeixotocx approved these changes
LGTM

2021-06-22 11:59 UTC, merged