feat(query): added 'Unknown Property' for openAPI 2.0
Checkmarx/kics pull request #3716
Opened 2021-06-21 13:29 UTC by rafaela-soares

Signed-off-by: Rafaela Soares <rafaela.soares@checkmarx.com>

**Proposed Changes**
- Added 'Unknown Property' for openAPI 2.0

I submit this contribution under the Apache-2.0 license.

2021-06-21 16:54 UTC, felipe-avelar requested changes
Please, check comments

2021-06-21 16:54 UTC, felipe-avelar commented on assets/queries/openAPI/2.0/unknown_property/query.rego
> +	path[minus(count(path), 1)] == o
I think here `o` could be changed to something more clear, since there is a comparison with path...

2021-06-21 16:54 UTC, felipe-avelar commented on assets/queries/openAPI/2.0/unknown_property/query.rego
> +	v := value[x]
I think `v` is not necessary here...
```suggestion
	value[x]
```

2021-06-21 16:54 UTC, felipe-avelar commented on assets/queries/openAPI/2.0/unknown_property/query.rego
> +	path[minus(count(path), 1)] == o
Same comment as above, also I think, maybe, it is interesting to extract a method of this two lines...

2021-06-21 16:54 UTC, felipe-avelar commented on assets/queries/openAPI/2.0/unknown_property/query.rego
> +	field := value[x][v]
Like above, I think `field` is not necessary here...
```suggestion
	value[x][v]
```

2021-06-21 16:54 UTC, felipe-avelar commented on assets/queries/openAPI/2.0/unknown_property/query.rego
> +	path[minus(count(path), 2)] == o
Same as above, maybe extracting a method preventing code replication

2021-06-21 16:54 UTC, felipe-avelar commented on assets/queries/openAPI/2.0/unknown_property/query.rego
> +	not known_field(object, x)
Same as above...
```suggestion
	value[x]
	not known_field(object, x)
```

2021-06-23 10:09 UTC, rogeriopeixotocx approved these changes
LGTM

2021-06-23 15:36 UTC, merged