initial commit on url handler
Checkmarx/kics pull request #3745
Opened 2021-06-23 11:36 UTC by rogeriopeixotocx

Signed-off-by: Rogério Peixoto <rogerio.peixoto@checkmarx.com>

Closes #

**Proposed Changes**
-
-
-

I submit this contribution under the Apache-2.0 license.

2021-07-09 16:21 UTC, felipe-avelar requested changes
Please, check comments

2021-07-09 16:21 UTC, felipe-avelar commented on pkg/engine/provider/extract.go
> +	return returnStr, nil
I think variables here could be a little more clear. Think `dst` or `st` does not represents anything in a clear way...

2021-07-09 16:21 UTC, felipe-avelar commented on pkg/engine/provider/extract.go
> +		err = os.RemoveAll(destination)
I think we could change this to guarantee a unique name, like a timestamp, for example, instead of trying to remove if it exists...

2021-07-09 16:21 UTC, felipe-avelar commented on pkg/model/summary.go
> +func cleanQueryPath(path, splitted string) string {
I think this could be renamed to `removeQueryParameters`, what do you think?

2021-07-12 08:43 UTC, felipe-avelar reviewed
Besides CxSAST vulnerabilities, this looks good to me. 🙂

2021-07-12 10:09 UTC, rogeriopeixotocx commented on internal/console/scan.go
> +		PathExtractionMap: extractedPaths.ExtrectionMap,
```suggestion
		PathExtractionMap: extractedPaths.ExtractionMap,
```

2021-07-12 10:16 UTC, rogeriopeixotocx commented on pkg/engine/provider/extract.go
> +// ExtrectionMap is a map that correlates the temporary path to the givven path
```suggestion
// ExtractionMap is a map that correlates the temporary path to the givven path
```

2021-07-12 10:16 UTC, rogeriopeixotocx commented on pkg/engine/provider/extract.go
> +	ExtrectionMap map[string]model.ExtractedPathObject
```suggestion
	ExtractionMap map[string]model.ExtractedPathObject
```

2021-07-12 14:17 UTC, felipe-avelar approved these changes
LGTM

2021-07-12 16:19 UTC, merged