feat(docs): Added 'Query Development Tutorial' section in creating-queries.md
Checkmarx/kics pull request #3747
Opened 2021-06-23 13:20 UTC by rafaela-soares

Signed-off-by: Rafaela Soares <rafaela.soares@checkmarx.com>

**Proposed Changes**
- Added 'Query Development Tutorial' section in creating-queries.md

I submit this contribution under the Apache-2.0 license.

2021-06-23 21:13 UTC, rogeriopeixotocx commented
This is something that I would like to get input from @kaplanlior

2021-06-28 15:45 UTC, rogeriopeixotocx requested changes

2021-06-28 15:45 UTC, rogeriopeixotocx commented on docs/creating-queries.md
> +Keep in mind that all the positive and negative files should contain only one breaking point case. This way, the results are more clear. As a best practice, the test folder should contain all the [ex
```suggestion
Keep in mind that all the positive and negative files should contain only one breaking point case. This way, the results are more clear. As a best practice, the test folder should contain all the [extensions available](https://docs.kics.io/latest/platforms/) by the platform.
```

2021-06-28 15:46 UTC, rogeriopeixotocx approved these changes

2021-06-28 16:31 UTC, felipe-avelar requested changes
Pleas, check comments

2021-06-28 16:31 UTC, joaoReigota1 approved these changes
LGTM

2021-06-28 16:31 UTC, felipe-avelar commented on docs/creating-queries.md
> +<img alt="RegoPlayground" src="img/rego_playground_example_tf.PNG">
I think this image source link is wrong

2021-06-28 16:31 UTC, felipe-avelar commented on docs/creating-queries.md
> +
I think it is missing `override` keyword

2021-06-28 16:59 UTC, felipe-avelar approved these changes
LGTM

2021-06-28 17:03 UTC, rogeriopeixotocx approved these changes

2021-06-28 17:12 UTC, merged