docs: updating docs css colors
Checkmarx/kics pull request #3813
Opened 2021-07-05 11:52 UTC by rogeriopeixotocx

I submit this contribution under the Apache-2.0 license.

2021-07-05 14:08 UTC, felipe-avelar requested changes
Check comments, please

2021-07-05 14:08 UTC, felipe-avelar commented on docs/css/custom.css
> +  color: #212529 !important;
I think here should be `#ffbc42`, since outlined buttons use border color as color too on material
```suggestion
  color: #ffbc42 !important;
```

2021-07-05 14:08 UTC, felipe-avelar commented on docs/css/custom.css
> +  color: #212529 !important;
This will be dark gray or white?

2021-07-05 15:31 UTC, rogeriopeixotocx commented on docs/css/custom.css
> +  color: #212529 !important;
dark gray

2021-07-06 13:40 UTC, felipe-avelar approved these changes
LGTM

2021-07-06 14:23 UTC, merged