fix(cli): fixing bug related to flag -q + adding new cli flag related to library path
Checkmarx/kics pull request #3900
Opened 2021-07-24 14:14 UTC by rafaela-soares

Closes #3895

**Proposed Changes**
- Fixing bug related to cli flag `-q` (`--queries-path`)
- Adding new cli flag `-b` (`--library`):  path to directory with libraries (default "./assets/libraries"). it assumes users pass a directory with libraries named as <platform.rego>

TODO: correct E2E tests and add more tests (I am back on Wednesday)

I submit this contribution under the Apache-2.0 license.

2021-08-02 13:22 UTC, rogeriopeixotocx requested changes
@rafaela-soares shouldn't we move our libraries from this path format: `/assets/libraries/platform/library.rego` to this format: `/assets/libraries/platform.rego`?

Also, I don't see the documentation additions that we discussed.

2021-08-02 13:22 UTC, rogeriopeixotocx commented on pkg/engine/inspector.go
> +			} else {
should we check if platform-specific queries are not available too with `platformGeneralQuery != ""`

2021-08-02 13:36 UTC, felipe-avelar requested changes
Please, check comments

2021-08-02 13:36 UTC, felipe-avelar commented on test/main_test.go
> +	pathToLib := source.GetPathToLibrary(platform, "../", "./assets/libraries")
Please, use `filepath.FromSlash` here to prevent cross OS issues

2021-08-02 13:36 UTC, felipe-avelar commented on pkg/engine/inspector_test.go
> +	pathToLib := source.GetPathToLibrary(platform, currentWorkdir, "./assets/libraries")
Please, use `filepath.FromSlash` here to prevent cross OS issues

2021-08-02 13:36 UTC, felipe-avelar commented on pkg/engine/inspector_test.go
> +	sources := source.NewFilesystemSource(m.Source, []string{""}, []string{""}, "./assets/libraries")
Please, use `filepath.FromSlash` here to prevent cross OS issues

2021-08-02 13:36 UTC, felipe-avelar commented on pkg/engine/inspector_test.go
> +	querySource := source.NewFilesystemSource(queryPath, []string{""}, []string{""}, "./assets/libraries")
Please, use `filepath.FromSlash` here to prevent cross OS issues

2021-08-02 13:36 UTC, felipe-avelar commented on internal/console/scan.go
> +		"./assets/libraries",
Please, use `filepath.FromSlash` here to prevent cross OS issues

2021-08-13 18:20 UTC, rogeriopeixotocx submitted a review, later dismissed

2021-08-13 18:32 UTC, rogeriopeixotocx approved these changes

2021-08-13 18:32 UTC, merged