feat(query): Added Email Notifications Set Off query to ARM
Checkmarx/kics pull request #3916
Opened 2021-07-27 13:51 UTC by joaoReigota1

Signed-off-by: João Reigota <joao.reigota@checkmarx.com>

**Proposed Changes**
- Added Email Notifications Set Off query to ARM

I submit this contribution under the Apache-2.0 license.

2021-07-29 07:57 UTC, rogeriopeixotocx requested changes

2021-07-29 07:57 UTC, rogeriopeixotocx commented on assets/queries/azureResourceManager/email_notifications_set_off/query.rego
> +	object.get(resource.properties, emailType[x], "undefined") == "undefined"
```suggestion
	not commonLib.valid_key(resource.properties, emailType[x])
```

2021-07-29 07:57 UTC, rogeriopeixotocx commented on assets/queries/azureResourceManager/email_notifications_set_off/query.rego
> +	object.get(resource.properties[emailType[x]], "state", "undefined") == "undefined"
```suggestion
    not commonLib.valid_key(resource.properties[emailType[x]], "state")
```

2021-07-29 07:57 UTC, rogeriopeixotocx commented on assets/queries/azureResourceManager/email_notifications_set_off/query.rego
> +
```suggestion
import data.generic.common as commonLib
```

2021-07-30 08:19 UTC, rafaela-soares requested changes

2021-07-30 08:19 UTC, rafaela-soares commented on assets/queries/azureResourceManager/email_notifications_set_off/query.rego
> +	emailType := ["alertNotifications", "notificationsByRole"]
maybe you could define `emailType := ["alertNotifications", "notificationsByRole"]` outside of the rule in order to prevent code repetition

2021-07-30 11:21 UTC, rogeriopeixotocx approved these changes
LGTM

2021-07-30 13:38 UTC, rafaela-soares approved these changes
LGTM

2021-07-30 13:42 UTC, merged