feat(query): Added Secret Without Expiration Date query for ARM
Checkmarx/kics pull request #3919
Opened 2021-07-27 15:08 UTC by joaoReigota1

Signed-off-by: João Reigota <joao.reigota@checkmarx.com>

**Proposed Changes**
- Added Secret Without Expiration Date query for ARM

All Secrets must have an expiration date defined

I submit this contribution under the Apache-2.0 license.

2021-07-29 08:07 UTC, rogeriopeixotocx requested changes

2021-07-29 08:07 UTC, rogeriopeixotocx commented on assets/queries/azureResourceManager/secret_without_expiration_date/query.rego
> +
```suggestion
import data.generic.common as commonLib
```

2021-07-29 08:07 UTC, rogeriopeixotocx commented on assets/queries/azureResourceManager/secret_without_expiration_date/query.rego
> +	object.get(resource.properties, "attributes", "undefined") == "undefined"
```suggestion
	not commonLib.valid_key(resource.properties, "attributes")
```

2021-07-29 08:07 UTC, rogeriopeixotocx commented on assets/queries/azureResourceManager/secret_without_expiration_date/query.rego
> +	object.get(resource.properties.attributes, "exp", "undefined") == "undefined"
```suggestion
    not commonLib.valid_key(resource.properties, "exp")
```

2021-07-30 08:23 UTC, rafaela-soares requested changes

2021-07-30 08:23 UTC, rafaela-soares commented on assets/queries/azureResourceManager/secret_without_expiration_date/metadata.json
> +  "cloudProvider": "common",
`"cloudProvider": "common"`

2021-07-30 13:50 UTC, rogeriopeixotocx approved these changes
LGTM

2021-07-30 13:55 UTC, rafaela-soares approved these changes
LGTM

2021-07-30 13:56 UTC, merged