feat(query): Added SQL Server Database With Alerts Disabled query for ARM
Checkmarx/kics pull request #3926
Opened 2021-07-28 10:30 UTC by joaoReigota1

Signed-off-by: João Reigota <joao.reigota@checkmarx.com>

**Proposed Changes**
- Added SQL Server Database With Alerts Disabled query for ARM

All Alerts should be enabled in SQL Database Server SecurityAlerts Policy Properties

I submit this contribution under the Apache-2.0 license.

2021-07-29 08:22 UTC, rogeriopeixotocx requested changes

2021-07-29 08:22 UTC, rogeriopeixotocx commented on assets/queries/azureResourceManager/sql_server_database_with_alerts_disabled/query.rego
> +		"issueType": "RedundantAttribute",
should we label as `IncorrectValue` ?

2021-07-30 08:25 UTC, rafaela-soares requested changes

2021-07-30 08:25 UTC, rafaela-soares commented on assets/queries/azureResourceManager/sql_server_database_with_alerts_disabled/metadata.json
>    "cloudProvider": "common",
`"cloudProvider": "azure"`

2021-07-30 13:51 UTC, rogeriopeixotocx approved these changes
LGTM

2021-07-30 13:52 UTC, merged