feat(query): Added SQL Database Server Firewall Allows All IPS query for ARM
Checkmarx/kics pull request #3933
Opened 2021-07-28 14:36 UTC by joaoReigota1

Signed-off-by: João Reigota <joao.reigota@checkmarx.com>

**Proposed Changes**
- Added SQL Database Server Firewall Allows All IPS query for ARM

SQL Database Server Firewall endIpAddress should not be '255.255.255.255' when startIpAddress is '0.0.0.0' since this allows all IPS

I submit this contribution under the Apache-2.0 license.

2021-07-29 09:09 UTC, rogeriopeixotocx requested changes

2021-07-29 09:09 UTC, rogeriopeixotocx commented on assets/queries/azureResourceManager/sql_database_server_firewall_allows_all_ips/query.rego
> +	types := ["Microsoft.Sql/servers/firewallRules", "firewallRules", "firewallrules"]
please add a sample with firewallRules inside a Microsoft.Sql/servers

2021-07-30 10:14 UTC, rafaela-soares commented
LGTM

2021-07-30 13:57 UTC, rafaela-soares approved these changes

2021-07-30 14:01 UTC, rogeriopeixotocx approved these changes
LGTM

2021-07-30 14:02 UTC, merged