feat(query): Refactoring 'object.get' function for cloudFormation
Checkmarx/kics pull request #4001
Opened 2021-08-05 15:04 UTC by tiagocruz20

Signed-off-by: Tiago Cruz tiago.cruz@checkmarx.com

**Proposed Changes**
- refactoring `object.get` function to `valid.key` function

I submit this contribution under the Apache-2.0 license.

2021-08-09 15:58 UTC, rogeriopeixotocx submitted a review, later dismissed

2021-08-09 17:10 UTC, rafaela-soares requested changes
Good job, @tiagocruz20! 🚀 

Overall, LGTM. I suggest small changes related to cases when it is unnecessary to check if a key is valid. These cases are related to key value comparison. For example, if we want to compare if `properties.Encrypted == false`, it is unnecessary to check if ` common_lib.valid_key(properties, "Encrypted")` since the comparison itself already assumes that the key is defined and not null

2021-08-09 17:10 UTC, rafaela-soares commented on assets/queries/cloudFormation/stack_retention_disabled/query.rego
> +	common_lib.valid_key(resource.Properties, "AutoDeployment")
`common_lib.valid_key(resource.Properties, "AutoDeployment")` is unnecessary. Same for lines 45 and 81

2021-08-11 12:05 UTC, rafaela-soares approved these changes
LGTM

2021-08-11 14:29 UTC, merged