feat(query): added "CloudTrail Log Files S3 Bucket Logging Disabled" for Terraform
Checkmarx/kics pull request #4041
Opened 2021-08-13 11:07 UTC by rafaela-soares

**Proposed Changes**
- Added "CloudTrail Log Files S3 Bucket Logging Disabled" for Terraform (missing severity and severity)

I submit this contribution under the Apache-2.0 license.

2021-08-13 11:20 UTC, rogeriopeixotocx commented
This is pending severity and category that will be added soon

2021-08-17 10:00 UTC, rogeriopeixotocx requested changes

2021-08-17 10:00 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/metadata.json
> +  "severity": "",
```suggestion
  "severity": "HIGH",
```

2021-08-17 10:00 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/metadata.json
> +  "category": "",
```suggestion
  "category": "Observability",
```

2021-08-17 10:06 UTC, rogeriopeixotocx requested changes

2021-08-17 10:06 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/test/positive_expected_result.json
> +    "severity": "",
```suggestion
    "severity": "HIGH",
```

2021-08-17 15:22 UTC, joaoReigota1 approved these changes
LGTM

2021-08-18 09:52 UTC, rogeriopeixotocx approved these changes

2021-08-18 09:52 UTC, merged