Feature/terraform
Checkmarx/kics pull request #4049
Opened 2021-08-16 10:46 UTC by tiagocruz20

Closes #

**Proposed Changes**
- refactoring object.get function to valid_key function
-
-

I submit this contribution under the Apache-2.0 license.

2021-08-17 12:02 UTC, rafaela-soares requested changes
Good job, @tiagocruz20!  

Overall, LGTM. I suggest the following small changes:

2021-08-17 12:02 UTC, rafaela-soares commented on assets/queries/terraform/aws/db_instance_storage_not_encrypted/query.rego
>  	not resource.storage_encrypted
`resource.storage_encrypted == false`

2021-08-17 13:23 UTC, rafaela-soares requested changes

2021-08-17 13:23 UTC, rafaela-soares commented on assets/queries/terraform/aws/elasticsearch_logs_disabled/query.rego
>  	result := {
```
"keyExpectedValue": "'log_publishing_options' is defined and not null",
"keyActualValue": "'log_publishing_options' is undefined or null",
```

2021-08-18 10:13 UTC, rogeriopeixotocx approved these changes
LGTM

2021-08-18 10:13 UTC, rafaela-soares approved these changes

2021-08-18 10:14 UTC, merged