feat(query): add azure app service client certificates disabled for t…
Checkmarx/kics pull request #4054
Opened 2021-08-16 17:05 UTC by tiagocruz20

…erraform

**Proposed Changes**
- added a query to check if client certificates enabled is true for azure app service resource
-
-

I submit this contribution under the Apache-2.0 license.

2021-08-17 10:02 UTC, rogeriopeixotocx commented
Pending **Severity** and **Category** review

2021-08-20 09:01 UTC, rogeriopeixotocx requested changes
format rego query either using `opa fmt` [link](https://github.com/open-policy-agent/opa/blob/c6344d05256c2ceb6ad4db3feb88922d44649862/cmd/fmt.go) or by using vscode OPA extension and enabling format on save on settings

2021-08-20 09:01 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/azure_app_service_client_certificate_disabled/metadata.json
> +  "category": "",
```suggestion
  "category": "Insecure Configurations",
```

2021-08-20 09:04 UTC, rogeriopeixotocx requested changes

2021-08-20 09:04 UTC, rogeriopeixotocx commented on payload.json
> +{
Remove this file.

2021-08-20 09:05 UTC, rogeriopeixotocx requested changes

2021-08-20 09:05 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/azure_app_service_client_certificate_disabled/query.rego
> +package Cx
Format this file using opa fmt or vscode extension for OPA

2021-08-20 09:05 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/azure_app_service_client_certificate_disabled/test/negative.tf
> +    "SOME_KEY" = "some-value"
```suggestion
    SOME_KEY = "some-value"
```

2021-08-20 09:05 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/azure_app_service_client_certificate_disabled/test/positive1.tf
> +    "SOME_KEY" = "some-value"
```suggestion
    SOME_KEY = "some-value"
```

2021-08-20 09:05 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/azure_app_service_client_certificate_disabled/test/positive2.tf
> +    "SOME_KEY" = "some-value"
```suggestion
    SOME_KEY = "some-value"
```

2021-08-20 09:05 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/azure_app_service_client_certificate_disabled/test/positive_expected_result.json
> +    "severity": "",
```suggestion
    "severity": "HIGH",
```

2021-08-20 09:05 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/azure_app_service_client_certificate_disabled/test/positive_expected_result.json
> +    "severity": "",
```suggestion
    "severity": "HIGH",
```

2021-08-20 19:07 UTC, rogeriopeixotocx commented
@tiagocruz20 please address the requested changes

2021-08-24 09:53 UTC, rafaela-soares approved these changes
LGTM

2021-08-24 11:03 UTC, rogeriopeixotocx approved these changes
LGTM

2021-08-24 11:04 UTC, merged