feat(query): add SQL Server alert email disabled for Terraform
Checkmarx/kics pull request #4060
Opened 2021-08-17 15:40 UTC by tiagocruz20

**Proposed Changes**
- added a query to check if alert email enabled is true for sql server resource
-
-

I submit this contribution under the Apache-2.0 license.

2021-08-18 08:40 UTC, rogeriopeixotocx commented
We need to review category and severity

2021-08-20 09:04 UTC, rogeriopeixotocx requested changes

2021-08-20 09:04 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/sql_server_alert_email_disabled/metadata.json
> +  "severity": "",
```suggestion
  "severity": "INFO",
```

2021-08-20 09:04 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/sql_server_alert_email_disabled/metadata.json
> +  "category": "",
```suggestion
  "category": "Best Practices",
```

2021-08-20 09:04 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/sql_server_alert_email_disabled/test/positive_expected_result.json
> +    "severity": "",
```suggestion
    "severity": "INFO",
```

2021-08-20 09:04 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/sql_server_alert_email_disabled/test/positive_expected_result.json
> +    "severity": "",
```suggestion
    "severity": "INFO",
```

2021-08-20 09:04 UTC, rogeriopeixotocx commented on payload.json
> +{
Remove this file

2021-08-24 09:58 UTC, rafaela-soares approved these changes
LGTM

2021-08-24 11:01 UTC, rogeriopeixotocx approved these changes
LGTM

2021-08-24 11:02 UTC, merged