feat(query): add "EC2 Instance Using API Keys" for Terraform
Checkmarx/kics pull request #4070
Opened 2021-08-18 14:34 UTC by rogeriopeixotocx

**Proposed Changes**
- EC2 instance without associated role using AWS API keys

I submit this contribution under the Apache-2.0 license.

2021-08-20 14:44 UTC, joaoReigota1 requested changes

2021-08-20 14:44 UTC, joaoReigota1 commented on assets/queries/terraform/aws/ec2_instance_using_api_keys/query.rego
> +		"searchKey": sprintf("aws_instance[%s]", [name]),
```suggestion
		"searchKey": sprintf("aws_instance[%s].provisioner", [name]),
```

2021-08-20 14:44 UTC, joaoReigota1 commented on assets/queries/terraform/aws/ec2_instance_using_api_keys/query.rego
> +		"searchKey": sprintf("aws_instance[%s]", [name]),
```suggestion
		"searchKey": sprintf("aws_instance[%s].provisioner", [name]),
```

2021-08-20 14:46 UTC, rafaela-soares submitted a review, later dismissed

2021-08-20 14:46 UTC, rafaela-soares commented on assets/queries/terraform/aws/ec2_instance_using_api_keys/query.rego
> +		"keyActualValue": sprintf("aws_instance[%s] should be using iam_instance_profile to assign a role with permissions", [name]),
```
"keyExpectedValue": sprintf("aws_instance[%s] should be using iam_instance_profile to assign a role with permissions", [name]),
"keyActualValue": sprintf("aws_instance[%s].user_data is being used to configure AWS API keys", [name]),
```

The same applies for the rules below

2021-08-23 13:32 UTC, felipe-avelar approved these changes
LGTM

2021-08-23 13:33 UTC, joaoReigota1 approved these changes
LGTM

2021-08-23 13:34 UTC, merged