feat(query): add EKS Node Group Remote Access Disabled for Terraform
Checkmarx/kics pull request #4086
Opened 2021-08-20 10:04 UTC by tiagocruz20

**Proposed Changes**
- added a query to check if remote access is disabled for ESK Node Group resource

I submit this contribution under the Apache-2.0 license.

2021-08-23 17:58 UTC, rogeriopeixotocx requested changes

2021-08-23 17:58 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/eks_node_group_remote_access_disabled/metadata.json
> +  "severity": "",
```suggestion
  "severity": "HIGH",
```

2021-08-23 17:58 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/eks_node_group_remote_access_disabled/metadata.json
> +  "category": "",
```suggestion
  "category": "Networking and Firewall",
```

2021-08-23 17:58 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/eks_node_group_remote_access_disabled/test/positive_expected_result.json
> +    "severity": "",
```suggestion
    "severity": "HIGH",
```

2021-08-24 10:19 UTC, rafaela-soares approved these changes
LGTM

2021-08-24 10:58 UTC, rogeriopeixotocx approved these changes
LGTM

2021-08-24 10:58 UTC, merged