feat(query): added EFS Volumes Not Encrypted for Terraform
Checkmarx/kics pull request #4158
Opened 2021-09-03 16:16 UTC by tiagocruz20

**Proposed Changes**
- added a query to check if "encryption" is enabled for EFS Volumes
- **category and severity are provisory**

I submit this contribution under the Apache-2.0 license.

2021-09-03 16:24 UTC, felipe-avelar requested changes
I think this could have another positive sample, when `transit_encryption = "DISABLED"`

2021-09-03 16:24 UTC, felipe-avelar commented on assets/queries/terraform/aws/efs_volumes_not_encrypted/query.rego
> +		"keyActualValue": "aws_ecs_task_definition.volume.efs_volume_configuration' is undefined or null",
I think `searchLine` is missing

2021-09-03 16:24 UTC, felipe-avelar commented on assets/queries/terraform/aws/efs_volumes_not_encrypted/query.rego
> +		"keyActualValue": "aws_ecs_task_definition.volume.efs_volume_configuration.transit_encryption' is undefined or null",
I think `searchLine` is missing

2021-09-06 13:01 UTC, rogeriopeixotocx commented
@tiagocruz20 please check query https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/aws/ecs_task_definition_volume_not_encrypted/query.rego

2021-09-06 14:39 UTC, rogeriopeixotocx commented
@tiagocruz20 please check query https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/aws/ecs_task_definition_volume_not_encrypted/query.rego

2021-09-06 14:39 UTC, closed without merging