feat(query): added "Glue Security Configuration Encryption Disabled" for Terraform
Checkmarx/kics pull request #4159
Opened 2021-09-03 16:42 UTC by rafaela-soares

**Proposed Changes**
- Added "Glue Security Configuration Encryption Disabled" for Terraform
- **Category and Severity are provisory**

I submit this contribution under the Apache-2.0 license.

2021-09-06 15:26 UTC, rogeriopeixotocx requested changes

2021-09-06 15:26 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/glue_security_configuration_encryption_disabled/query.rego
> +		"keyActualValue": sprintf("aws_glue_security_configKeyiguration[%s].%s has '%s' undefined or null", [name, configKey, configValue]),
missing searchLine

2021-09-06 15:26 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/glue_security_configuration_encryption_disabled/query.rego
> +		"keyActualValue": sprintf("aws_glue_security_configuration[%s].%s has 'kms_key_arn' undefined or null", [name, config]),
missing searchLine

2021-09-06 15:26 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/glue_security_configuration_encryption_disabled/query.rego
> +		"keyActualValue": searchKeyInfo.keyActualValue,
missing searchLine

2021-09-06 15:26 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/glue_security_configuration_encryption_disabled/metadata.json
> +  "descriptionUrl": "https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_resource_policy#policy",
```suggestion
  "descriptionUrl": "https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_security_configuration",
```

2021-09-06 15:26 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/glue_security_configuration_encryption_disabled/metadata.json
> +  "severity": "MEDIUM",
```suggestion
  "severity": "HIGH",
```

2021-09-06 15:33 UTC, JoaoDuarteGomes reviewed
I agree with the category selection and with the change suggested by @rogeriopeixotocx for the severity.

2021-09-06 15:33 UTC, JoaoDuarteGomes commented on assets/queries/terraform/aws/glue_security_configuration_encryption_disabled/metadata.json
> +  "severity": "MEDIUM",
I agree with this suggestion.

2021-09-09 09:12 UTC, rogeriopeixotocx approved these changes

2021-09-09 09:12 UTC, merged