feat(query): added Autoscaling Groups Supply Tags for Terraform
Checkmarx/kics pull request #4164
Opened 2021-09-06 17:43 UTC by tiagocruz20

**Proposed Changes**
- added a query to check if Autoscaling Groups supply tags to launch configurations

I submit this contribution under the Apache-2.0 license.

2021-09-07 08:28 UTC, rogeriopeixotocx approved these changes
LGTM

2021-09-09 09:19 UTC, rogeriopeixotocx commented
@rjegoncalves @JoaoDuarteGomes please approve the category and severity

2021-09-09 09:42 UTC, JoaoDuarteGomes requested changes
The category needs to be reviewed.

2021-09-09 09:42 UTC, JoaoDuarteGomes commented on assets/queries/terraform/aws/autoscaling_groups_supply_tags/metadata.json
> +  "category": "Encryption",
This query does not fit this category. This should be in the "Availability" category.

2021-09-09 09:42 UTC, JoaoDuarteGomes commented on assets/queries/terraform/aws/autoscaling_groups_supply_tags/metadata.json
> +  "descriptionUrl": "https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#launch_configuration",
Please review this link to ensure it is correct.

2021-09-09 09:54 UTC, rogeriopeixotocx requested changes

2021-09-09 09:54 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/autoscaling_groups_supply_tags/metadata.json
> +  "descriptionUrl": "https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#launch_configuration",
```suggestion
  "descriptionUrl": "https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#tag-and-tags",
```

2021-09-09 09:54 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/autoscaling_groups_supply_tags/metadata.json
> +  "category": "Encryption",
```suggestion
  "category": "Availability",
```

2021-09-09 11:10 UTC, JoaoDuarteGomes approved these changes
LGTM.

2021-09-10 17:02 UTC, rogeriopeixotocx approved these changes

2021-09-13 08:52 UTC, merged