feat(query): added ALB Deletion Protection Disabled for Terraform
Checkmarx/kics pull request #4165
Opened 2021-09-07 12:11 UTC by tiagocruz20

**Proposed Changes**
- added a query to check if deletion_protection is enabled in Application Load Balancer (ALB)

I submit this contribution under the Apache-2.0 license.

2021-09-07 16:58 UTC, rogeriopeixotocx requested changes

2021-09-07 16:58 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/alb_deletion_protection_disabled/test/positive.tf
> +resource "aws_lb" "positive" {
name the file positive1.tf
```suggestion
resource "aws_lb" "positive1" {
```

2021-09-07 16:58 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/alb_deletion_protection_disabled/test/positive_expected_result.json
> +    "fileName": "positive.tf"
```suggestion
    "fileName": "positive1.tf"
```

2021-09-07 16:58 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/alb_deletion_protection_disabled/metadata.json
> +  "id": "8bbb242f-6e38-4127-86d4-d8f0b2687ae2",
Create an unique query ID, see unit tests error:
```
   === RUN   TestUniqueQueryIDs
      queries_test.go:62: 
          	Error Trace:	queries_test.go:62
          	Error:      	Should be false
          	Test:       	TestUniqueQueryIDs
          	Messages:   	
          	            	non unique queryID found uuid: 8bbb242f-6e38-4127-86d4-d8f0b2687ae2
          	            	queryDir: ..\assets\queries\terraform\aws\ami_not_encrypted
          	            	duplicateDir: ..\assets\queries\terraform\aws\alb_deletion_protection_disabled
```

2021-09-07 16:58 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/alb_deletion_protection_disabled/metadata.json
> +  "descriptionID": "248fe368",
Create a unique description ID for the new query.

2021-09-09 09:04 UTC, rafaela-soares requested changes

2021-09-09 09:04 UTC, rafaela-soares commented on assets/queries/terraform/aws/alb_deletion_protection_disabled/query.rego
> +	lb := input.document[i].resource.aws_lb[name]
Maybe we can also include the resource `aws_alb`

2021-09-13 09:21 UTC, rogeriopeixotocx approved these changes

2021-09-13 09:21 UTC, merged