feat(query): added Security Contact Email for Terraform
Checkmarx/kics pull request #4171
Opened 2021-09-08 14:22 UTC by tiagocruz20

**Proposed Changes**
- added a query to check if email is set in Security Contact

I submit this contribution under the Apache-2.0 license.

2021-09-09 10:07 UTC, rogeriopeixotocx requested changes
Since the email field is required by Terraform.
Don't think it makes sense to have a query to check if this email field is missing.

Opinions? @JoaoDuarteGomes @felipe-avelar @rafaela-soares

2021-09-09 10:08 UTC, felipe-avelar commented
> Since the email field is required by Terraform.
> Don't think it makes sense to have a query to check if this email field is missing.
> 
> Opinions? @JoaoDuarteGomes @felipe-avelar @rafaela-soares

I agree with you, for me doesn't makes sense either...

2021-09-09 11:08 UTC, JoaoDuarteGomes commented
It's up to you whether you want the query or not.
If this is an issue that can both be correctly detected statically and prevents the plan from being built, this is a legitimate query.

2021-09-13 09:28 UTC, rogeriopeixotocx approved these changes

2021-09-13 09:28 UTC, merged