feat(query): added PostgreSQL Server Infrastructure Encryption for Te…
Checkmarx/kics pull request #4173
Opened 2021-09-08 15:53 UTC by tiagocruz20

…rraform

**Proposed Changes**
- added a query to check if infrastructure encryption is enabled in PostgreSQL Server

I submit this contribution under the Apache-2.0 license.

2021-09-09 09:11 UTC, rafaela-soares requested changes

2021-09-09 09:11 UTC, rafaela-soares commented on assets/queries/terraform/azure/postgre_sql_server_infrastructure_encryption/metadata.json
> +  "queryName": "PostgreSQL Server Infrastructure Encryption",
Maybe we can rename it for something more intuitive like `"queryName": "PostgreSQL Server Infrastructure Encryption Disabled"`

2021-09-09 09:28 UTC, felipe-avelar requested changes
Please, check comments

2021-09-09 09:28 UTC, felipe-avelar commented on assets/queries/terraform/azure/postgre_sql_server_infrastructure_encryption/query.rego
> +		"keyActualValue": sprintf("'azurerm_postgresql_server[%s].infrastructure_encryption_enabled' is not set to true", [name]),
```suggestion
		"keyActualValue": sprintf("'azurerm_postgresql_server[%s].infrastructure_encryption_enabled' is false", [name]),
```

2021-09-09 09:28 UTC, felipe-avelar commented on assets/queries/terraform/azure/postgre_sql_server_infrastructure_encryption_disabled/query.rego
> +		"keyActualValue": sprintf("'azurerm_postgresql_server[%s].infrastructure_encryption_enabled' is not set to true", [name]),
```suggestion
		"keyActualValue": sprintf("'azurerm_postgresql_server[%s].infrastructure_encryption_enabled' is set to false", [name]),
```

2021-09-09 09:28 UTC, felipe-avelar commented on assets/queries/terraform/azure/postgre_sql_server_infrastructure_encryption_disabled/query.rego
> +		"keyExpectedValue": sprintf("'azurerm_postgresql_server[%s].infrastructure_encryption_enabled' is defined and not null", [name]),
```suggestion
		"keyExpectedValue": sprintf("'azurerm_postgresql_server[%s].infrastructure_encryption_enabled' is defined and set to true", [name]),
```

2021-09-10 10:56 UTC, rafaela-soares requested changes

2021-09-10 10:56 UTC, rafaela-soares commented on assets/queries/terraform/azure/postgre_sql_server_infrastructure_encryption_disabled/query.rego
> +		"keyActualValue": sprintf("'azurerm_postgresql_server[%s].infrastructure_encryption_enabled' is undefined or set to false", [name]),
I think we should maintain `"keyActualValue": sprintf("'azurerm_postgresql_server[%s].infrastructure_encryption_enabled' is undefined or null", [name]),`

2021-09-14 08:31 UTC, rogeriopeixotocx approved these changes

2021-09-14 08:32 UTC, merged