feat(query): added Azure Active Directory Authentication for Terraform
Checkmarx/kics pull request #4180
Opened 2021-09-09 16:30 UTC by tiagocruz20

**Proposed Changes**
- added a query to check if Azure Active Directory is defined for authentication for Service Fabric

I submit this contribution under the Apache-2.0 license.

2021-09-09 16:43 UTC, rafaela-soares requested changes

2021-09-09 16:43 UTC, rafaela-soares commented on assets/queries/terraform/azure/azure_active_directory_authentication/query.rego
> +package Cx
We could include a rule to check if `azure_active_directory` is undefined

2021-09-09 17:30 UTC, rafaela-soares requested changes

2021-09-09 17:30 UTC, rafaela-soares commented on assets/queries/terraform/azure/azure_active_directory_authentication/query.rego
> +	result := {
Missing searchLine

2021-09-09 17:31 UTC, rafaela-soares submitted a review, later dismissed

2021-09-09 17:31 UTC, rafaela-soares commented on assets/queries/terraform/azure/azure_active_directory_authentication/query.rego
> +	result := {
Missing searchLine

2021-09-13 15:44 UTC, felipe-avelar approved these changes
LGTM

2021-09-14 08:43 UTC, rogeriopeixotocx approved these changes
LGTM

2021-09-14 08:44 UTC, merged