Feature/network interfaces ip forwarding enabled
Checkmarx/kics pull request #4190
Opened 2021-09-13 16:41 UTC by tiagocruz20

**Proposed Changes**
- added a query to check if enable_ip_forwarding is enabled for Network Interfaces

I submit this contribution under the Apache-2.0 license.

2021-09-14 08:43 UTC, felipe-avelar requested changes
Please, check comments

2021-09-14 08:43 UTC, felipe-avelar commented on assets/queries/terraform/azure/network_interfaces_ip_forwarding_enable/query.rego
> +}
I think this check is not necessary, since the default value is `false`

2021-09-14 08:43 UTC, felipe-avelar commented on assets/queries/terraform/azure/network_interfaces_ip_forwarding_enable/test/positive2.tf
> +}
I think this file should be a negative, since the default value for `enable_ip_forwarding` is `false`

2021-09-14 08:54 UTC, rogeriopeixotocx commented
@tiagocruz20 fix pull request name and make sure all PR checks are passing

2021-09-15 08:24 UTC, rafaela-soares requested changes

2021-09-15 08:24 UTC, rafaela-soares commented on assets/queries/terraform/azure/network_interfaces_ip_forwarding_enable/query.rego
> +		"keyExpectedValue": sprintf("'azurerm_network_interface[%s].enable_ip_forwarding' is set to false", [name]),
Here, we could indicate `is set to false or undefined` (since the default value is false)

2021-09-15 09:01 UTC, felipe-avelar approved these changes
LGTM

2021-09-15 11:01 UTC, rogeriopeixotocx approved these changes

2021-09-15 11:03 UTC, rafaela-soares approved these changes
LGTM

2021-09-15 11:38 UTC, rogeriopeixotocx approved these changes

2021-09-15 11:38 UTC, merged