feat(query): added "PSP With Unrestricted Access to Host Path" for Kubernetes
Checkmarx/kics pull request #4252
Opened 2021-09-22 16:29 UTC by rafaela-soares

**Proposed Changes**
- Added "PSP With Unrestricted Access to Host Path" for Kubernetes
- In draft until severity and category confirm
- In draft until until the searchLine is modified

I submit this contribution under the Apache-2.0 license.

2021-09-22 17:23 UTC, JoaoDuarteGomes requested changes
The category needs to be changed, the severity is more of a recommendation.

2021-09-22 17:23 UTC, JoaoDuarteGomes commented on assets/queries/k8s/psp_with_unrestricted_access_to_host_path/metadata.json
> +  "category": "Access Control",
This should be categorized as "Resource Management".

2021-09-22 17:23 UTC, JoaoDuarteGomes commented on assets/queries/k8s/psp_with_unrestricted_access_to_host_path/metadata.json
> +  "severity": "MEDIUM",
I would bump this up to High severity.

2021-09-23 07:40 UTC, JoaoDuarteGomes approved these changes
Category and Severity LGTM.

2021-09-24 10:47 UTC, rogeriopeixotocx approved these changes
LGTM

2021-09-24 10:47 UTC, merged