feat(Query): added "Pod or Container Without ResourceQuota" for Kubernetes
Checkmarx/kics pull request #4258
Opened 2021-09-24 08:36 UTC by rafaela-soares

**Proposed Changes**
- Added "Pod or Container Without ResourceQuota" for Kubernetes

I submit this contribution under the Apache-2.0 license.

2021-09-24 11:56 UTC, rogeriopeixotocx requested changes

2021-09-24 11:56 UTC, rogeriopeixotocx commented on assets/queries/k8s/pod_or_container_without_resource_quota/query.rego
> +	document.kind != "Pod"
I believe we need to check for templated types too (Deployments, DaemonSets, etc...)

2021-09-24 13:12 UTC, rogeriopeixotocx approved these changes

2021-09-24 15:42 UTC, merged

2022-04-01 17:56 UTC, Magier commented
Hi, sorry for activating an already merged feature but I don't really understand the goal of this check.
ResourceQuotas (RQ) and LimitRanges (LR) are defined at namespace level. At Pod level you only define resource limits and requests.
So, the semantic of defining a RQ at a pod or container level - as the name of this query suggests - is wrong.

Enforcing the presence of RQ/LR would make only sense, if an entire namespace including it's workloads are configured in a single file. In the more common case where there is a manifest per workload (at least as judging by what I've seen so far) this leads to countless false-positives.

Maybe you could help me understand the reasoning for this check or is it actually an issue?

Thanks!