feat(query): support of Terraform modules for "Auto Scaling Group Wit…
Checkmarx/kics pull request #4267
Opened 2021-09-24 11:20 UTC by rogeriopeixotocx

…h No Associated ELB"

**Check why this is failing in unit tests**

I submit this contribution under the Apache-2.0 license.

2021-09-27 13:34 UTC, rogeriopeixotocx commented
@tiagocruz20 this query was reverted and reopened as PR due to failing checks.

Please add a new `OR` check in the policy, verifying if the `aws_autoscaling_group` has load_balancers > 0: 
```
count(resource.load_balancers) > 0
```

2021-09-28 14:30 UTC, felipe-avelar requested changes
Please, check suggestions. Also, first rule is missing `searchLine`

2021-09-28 14:30 UTC, felipe-avelar commented on assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/query.rego
> +		"searchLine": common_lib.build_search_line(["module", name, "load_balancers"], []),
```suggestion
		"searchLine": common_lib.build_search_line(["module", name], []),
```

2021-09-28 14:30 UTC, felipe-avelar commented on assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/query.rego
> +		"searchKey": sprintf("module[%s].load_balancers", [name]),
```suggestion
		"searchKey": sprintf("module[%s]", [name]),
```

2021-09-28 14:30 UTC, felipe-avelar commented on assets/queries/terraform/aws/auto_scaling_group_with_no_associated_elb/query.rego
> +		"issueType": "MissingAttribute",
```suggestion
		"issueType": "IncorrectValue",
```

2021-09-28 14:46 UTC, joaoReigota1 approved these changes
LGTM

2021-09-28 14:49 UTC, merged