feat(query): support of Terraform modules for "Cloudtrail_Log_Files_S…
Checkmarx/kics pull request #4279
Opened 2021-09-24 15:05 UTC by tiagocruz20

…3_Bucket_With_Logging_Disabled"

**Proposed Changes**
- support of Terraform modules for "Cloudtrail_Log_Files_S3_Bucket_With_Logging_Disabled"

I submit this contribution under the Apache-2.0 license.

2021-09-27 11:32 UTC, felipe-avelar requested changes
Please, check comments

2021-09-27 11:32 UTC, felipe-avelar commented on assets/queries/terraform/aws/cloudtrail_log_files_s3_bucket_with_logging_disabled/query.rego
> +	keyToCheck := common_lib.get_module_equivalent_key("aws", module.source, "aws_s3_bucket", "logging")
I think this is not necessary, since it is not used...

2021-09-28 13:16 UTC, felipe-avelar approved these changes
LGTM

2021-09-28 14:40 UTC, rogeriopeixotocx approved these changes
LGTM

2021-09-28 14:40 UTC, merged