feat(query): support of Terraform modules for "SQS With SSE Disabled"
Checkmarx/kics pull request #4282
Opened 2021-09-24 16:53 UTC by rafaela-soares

**Proposed Changes**
- Support of Terraform modules for "SQS With SSE Disabled"

I submit this contribution under the Apache-2.0 license.

2021-09-27 11:12 UTC, felipe-avelar submitted a review, later dismissed
LGTM

2021-09-27 16:26 UTC, rogeriopeixotocx requested changes

2021-09-27 16:26 UTC, rogeriopeixotocx commented on assets/queries/terraform/aws/sqs_with_sse_disabled/query.rego
> +		"keyActualValue": "'kms_master_key_id' is undefined or null",
```suggestion
		"keyExpectedValue": "'kms_master_key_id' is not empty",
		"keyActualValue": "'kms_master_key_id' is not empty",
```

2021-09-28 15:43 UTC, rogeriopeixotocx approved these changes

2021-09-28 16:15 UTC, merged