fix(parser): terraform parser now looks into .tfvars for passwords and secrets
Checkmarx/kics pull request #4291
Opened 2021-09-27 13:48 UTC by joaoReigota1

Signed-off-by: João Reigota <joao.reigota@checkmarx.com>

Closes #3581

**Proposed Changes**

- terraform parser now looks into .tfvars for passwords and secrets
- new regex to look for generic access keys

I submit this contribution under the Apache-2.0 license.

2021-09-27 17:07 UTC, felipe-avelar submitted a review, later dismissed
LGTM

2021-09-28 08:45 UTC, rogeriopeixotocx requested changes

2021-09-28 08:45 UTC, rogeriopeixotocx commented on docs/secrets.md
> +Being the only query written in Golang, it involves several rules to cover the maximum possible cases. These rules bases on regexes.
```suggestion
Being the only query written in Golang, it involves several rules to cover the maximum possible cases. These rules are based on regexes. The default rules can be found [here](https://github.com/Checkmarx/kics/blob/master/assets/queries/common/passwords_and_secrets/regex_rules.json).
```

2021-09-28 08:46 UTC, rogeriopeixotocx approved these changes

2021-09-28 09:13 UTC, merged