feat(query): added "Function App Authentication Disabled" for Terraform
Checkmarx/kics pull request #4445
Opened 2021-10-29 14:26 UTC by rafaela-soares

**Proposed Changes**
- Added "Function App Authentication Disabled" for Terraform
- Renamed folder from assets\queries\terraform\azure\unrestricted_sql_server_acess to assets\queries\terraform\azure\unrestricted_sql_server_access

I submit this contribution under the Apache-2.0 license.

2021-11-04 10:40 UTC, JoaoDuarteGomes requested changes
Category LGTM.
Severity should be HIGH.

2021-11-04 10:48 UTC, rogeriopeixotocx requested changes

2021-11-04 10:48 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/function_app_authentication_disabled/metadata.json
> +  "severity": "INFO",
```suggestion
  "severity": "HIGH",
```

2021-11-04 11:56 UTC, JoaoDuarteGomes approved these changes
LGTM.

2021-11-10 09:12 UTC, joaoReigota1 approved these changes
LGTM

2021-11-10 09:17 UTC, merged