feat(query): added "Function App Client Certificates Unrequired" for Terraform
Checkmarx/kics pull request #4446
Opened 2021-10-29 14:46 UTC by rafaela-soares

**Proposed Changes**
- Added "Function App Client Certificates Unrequired" for Terraform

I submit this contribution under the Apache-2.0 license.

2021-11-04 10:41 UTC, JoaoDuarteGomes requested changes
Category LGTM.
Severity should be lowered to MEDIUM.

2021-11-04 10:48 UTC, rogeriopeixotocx requested changes

2021-11-04 10:48 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/function_app_client_certificates_unrequired/metadata.json
> +  "severity": "HIGH",
```suggestion
  "severity": "MEDIUM",
```

2021-11-04 11:56 UTC, JoaoDuarteGomes approved these changes
LGTM.

2021-11-10 09:14 UTC, joaoReigota1 approved these changes
LGTM

2021-11-10 09:16 UTC, merged