feat(query): added "App Service Not Using Latest TLS Encryption Version" for Terraform
Checkmarx/kics pull request #4450
Opened 2021-10-29 16:17 UTC by rafaela-soares

**Proposed Changes**
- Added "App Service Not Using Latest TLS Encryption Version" for Terraform

I submit this contribution under the Apache-2.0 license.

2021-11-03 08:58 UTC, JoaoDuarteGomes requested changes
We should bump the severity to HIGH.
The category LGTM.

2021-11-04 09:32 UTC, JoaoDuarteGomes submitted a review, later dismissed
LGTM.

2021-11-04 14:52 UTC, JoaoDuarteGomes approved these changes
LGTM.

2021-11-04 18:01 UTC, nunoocx approved these changes

2021-11-04 18:01 UTC, merged