refactor(query): Updated query Chown Flag Exists description (#3768)
Checkmarx/kics pull request #4466
Opened 2021-11-03 17:14 UTC by joaoReigota1

Signed-off-by: João Reigota <joao.reigota@checkmarx.com>

Closes #3768

**Proposed Changes**
- Updated description to be more clear on what the vulnerability implies

I submit this contribution under the Apache-2.0 license.

2021-11-04 11:31 UTC, rogeriopeixotocx approved these changes

2021-11-04 17:08 UTC, rafaela-soares requested changes

2021-11-04 17:08 UTC, rafaela-soares commented on assets/queries/dockerfile/chown_flag_exists/metadata.json
> +  "descriptionText": "It is condidered a best practice for every executable in a container to be owned by the root user even if it is executed by a non-root user, only execution permissions are requi
typo: considered

2021-11-08 12:13 UTC, felipe-avelar approved these changes
LGTM

2021-11-08 17:06 UTC, rafaela-soares approved these changes
LGTM

2021-11-08 17:07 UTC, merged