feat(query): added "App Service Managed Identity Disabled" for Terraform
Checkmarx/kics pull request #4470
Opened 2021-11-04 12:02 UTC by rafaela-soares

**Proposed Changes**
- Added "App Service Managed Identity Disabled" for Terraform

I submit this contribution under the Apache-2.0 license.

2021-11-05 15:57 UTC, felipe-avelar submitted a review, later dismissed
LGTM

2021-11-05 17:54 UTC, nunoocx submitted a review, later dismissed

2021-11-08 09:52 UTC, JoaoDuarteGomes requested changes
The category should be "Resource Management" and the severity should be "High".

2021-11-08 12:27 UTC, rogeriopeixotocx requested changes

2021-11-08 12:27 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/app_service_managed_identity_disabled/metadata.json
> +  "severity": "MEDIUM",
```suggestion
  "severity": "HIGH",
```

2021-11-08 12:27 UTC, rogeriopeixotocx commented on assets/queries/terraform/azure/app_service_managed_identity_disabled/metadata.json
> +  "category": "Insecure Configurations",
```suggestion
  "category": "Resource Management",
```

2021-11-08 12:28 UTC, JoaoDuarteGomes submitted a review, later dismissed
LGTM.

2021-11-10 09:19 UTC, joaoReigota1 approved these changes
LGTM

2021-11-10 09:20 UTC, merged