feat(query): added "MSSQL Server Public Network Access Enabled" for Terraform
Checkmarx/kics pull request #4471
Opened 2021-11-04 12:36 UTC by rafaela-soares

**Proposed Changes**
- Added "MSSQL Server Public Network Access Enabled" for Terraform

- 🚨 **CATEGORY AND SEVERITY NEEDS REVIEW**🚨

I submit this contribution under the Apache-2.0 license.

2021-11-04 14:24 UTC, JoaoDuarteGomes requested changes
Severity LGTM.
Category should be "Networking and Firewall".

2021-11-04 14:53 UTC, JoaoDuarteGomes submitted a review, later dismissed
LGTM.

2021-11-05 09:38 UTC, JoaoDuarteGomes approved these changes
LGTM.

2021-11-05 17:55 UTC, nunoocx approved these changes

2021-11-05 17:55 UTC, merged