feat(passwords and secrets): validation of query ids in custom secrets regexes
Checkmarx/kics pull request #4478
Opened 2021-11-04 18:11 UTC by rafaela-soares

Closes #4349

**Proposed Changes**
- Validation of query ids in custom secrets regexes

I submit this contribution under the Apache-2.0 license.

2021-11-05 18:06 UTC, nunoocx requested changes

2021-11-05 18:06 UTC, nunoocx commented on pkg/engine/secrets/inspector.go
> +			return fmt.Errorf("the query %s defines a invalid query ID (%s)", allRegexQueries[i].Name, allRegexQueries[i].ID)
...defines **an** invalid

2021-11-08 12:14 UTC, felipe-avelar approved these changes
LGTM

2021-11-09 12:25 UTC, joaoReigota1 approved these changes
LGTM

2021-11-09 12:45 UTC, nunoocx approved these changes
LGTM

2021-11-09 12:47 UTC, merged