feat(query): added "GKE Using Default Service Account" for Ansible and Terraform
Checkmarx/kics pull request #4515
Opened 2021-11-14 17:44 UTC by cosmicgirl97

**Proposed Changes**
- Added "GKE Using Default Service Account" for Ansible and Terraform

🚨 SEVERITY AND CATEGORY NEED REVIEW 🚨

I submit this contribution under the Apache-2.0 license.

2021-11-15 15:30 UTC, JoaoDuarteGomes approved these changes
LGTM.

2021-11-22 09:23 UTC, joaoReigota1 requested changes

2021-11-22 09:23 UTC, joaoReigota1 commented on assets/queries/ansible/gcp/gke_using_default_service_account/query.rego
> +		"keyActualValue": "'service_account' is default",
Key expected/actual value should indicate that service_account is missing

2021-11-22 10:06 UTC, JoaoDuarteGomes approved these changes
LGTM.

2021-11-23 10:10 UTC, joaoReigota1 approved these changes
LGTM

2021-11-23 10:11 UTC, merged