feat(report): added CycloneDX report
Checkmarx/kics pull request #4579
Opened 2021-12-03 15:25 UTC by rafaela-soares

**Proposed Changes**
- Now, KICS can export vulnerabilities in CycloneDX XML format

I submit this contribution under the Apache-2.0 license.

2021-12-03 15:53 UTC, felipe-avelar requested changes
Please, check comments. Also, there is a security issue about opening a file, please check this too...

2021-12-03 15:53 UTC, felipe-avelar commented on .gitignore
> +>>>>>>> master
```suggestion
cyclonedx-results.xml
junit-results.xml
```

2021-12-03 15:53 UTC, felipe-avelar commented on pkg/report/model/cyclonedx.go
> +		queryDescription = fmt.Sprintf("[CIS]: %s", query.CISDescriptionTextFormatted)
I think we could remove this tag...

2021-12-03 15:53 UTC, felipe-avelar commented on pkg/report/model/cyclonedx.go
> +	var c Component
Based on the comment in line 258, I think this could be removed

2021-12-03 15:53 UTC, felipe-avelar commented on pkg/report/model/cyclonedx.go
> +		index := 12
I think we could define this as a constant outside the loop with some name like `minShaLength`

2021-12-03 15:53 UTC, felipe-avelar commented on pkg/report/model/cyclonedx.go
> +		bom.Components.Components = append(bom.Components.Components, c)
I think we could just define this here, like following suggestion:
```suggestion
		component := Component{
			Type:    "file",
			BomRef:  purl,
			Name:    filePath,
			Version: version,
			Purl:    purl,
			Hashes: []Hash{
				{
					Alg:     "SHA-256",
					Content: sha,
				},
			},
			Vulnerabilities: vuln,
		}

		bom.Components.Components = append(bom.Components.Components, component )
```

2021-12-06 09:47 UTC, felipe-avelar submitted a review, later dismissed
LGTM

2021-12-06 16:46 UTC, joaoReigota1 commented on pkg/report/model/cyclonedx.go
> +	return vulns
I think this function could be refactored for readability, can you place from lines 163 to 189 in a separate function?

2021-12-15 14:19 UTC, joaoReigota1 approved these changes
LGTM

2021-12-15 14:20 UTC, merged