feat(terraformer): added terraformer integration
Checkmarx/kics pull request #4686
Opened 2022-01-14 17:42 UTC by joaoReigota1

**Proposed Changes**
- added terraformer integration with kics

I submit this contribution under the Apache-2.0 license.

2022-01-18 17:28 UTC, rafaela-soares requested changes
LGTM 🚀 🚀 🚀 
Only a minor suggestion:

2022-01-18 17:28 UTC, rafaela-soares commented on mkdocs.yml
> +      - Terraformer: integrations_terraformer.md
Also added it in `docs/integrations.md`

2022-01-19 08:01 UTC, nunoocx requested changes

2022-01-19 08:01 UTC, nunoocx commented on docs/integrations_terraformer.md
> +
Add an intro like so:

From version 1.5, KICS integrates with Terraformer to scan resources deployed in the cloud. The runtime information of the resources is obtained by providing a Terraformer path to KICS, via `-p` flag. The scan happens immediately after this information is obtained. In the end, results are shown as for any other KICS scan.

#### Cloud providers supported:
- AWS

2022-01-19 08:25 UTC, nunoocx approved these changes
LGTM

2022-01-19 09:08 UTC, rafaela-soares approved these changes
LGTM

2022-01-19 09:08 UTC, merged