Add cpu_limits query Closes #483
Checkmarx/kics pull request #486
Opened 2020-11-27 12:51 UTC by rafaela-soares

Since attribute 'containers' is an array, it is necessary to check if all containers have CPU limits.

Closes #483

2020-12-02 14:01 UTC, joelsou5a requested changes

2020-12-02 14:01 UTC, joelsou5a commented on assets/queries/k8s/cpu_limits/query.rego
> +package Cx
Check this implementation to a more specifiy searchKey

Attached rego query
[Uploading query.zip…]()

2020-12-02 14:01 UTC, joelsou5a requested changes

2020-12-02 14:01 UTC, joelsou5a commented on assets/queries/k8s/cpu_limits/test/positive_expected_result.json
> +		"line": 6
"line": 11

2020-12-06 22:36 UTC, joaomartinscx requested changes

2020-12-06 22:36 UTC, joaomartinscx commented on assets/queries/k8s/cpu_limits/query.rego
> +    object.get(containers[index]["resources"]["limits"], "cpu", "undefined") == "undefined"
the query should detect when either _limits_ or _resource_ are not present in the file, e.g. if you remove the limits or resources attribute in the *negative.yaml* the query is still passing, when it should not. I suggest testing these different edge cases.

2020-12-08 10:22 UTC, joaomartinscx requested changes

2020-12-08 10:22 UTC, joaomartinscx commented on assets/queries/k8s/cpu_limits/query.rego
> +                "keyExpectedValue":  sprintf("%s.containers.name=%s does have CPU limits",[specInfo.path, containers[index].name]),
Perhaps it's clearer to specify the path where the information should be added, like in this case:
sprintf("'%s.containers[%s].resources.limits.cpu' is set",[specInfo.path, index])

2020-12-09 18:59 UTC, ruigomescx approved these changes

2020-12-09 18:59 UTC, merged