update(queries): updated S3 Bucket queries for Terraform
Checkmarx/kics pull request #4872
Opened 2022-02-24 12:37 UTC by rafaela-soares

**Proposed Changes**
- Some of the S3 bucket fields (website, cors_rule, versioning, logging, lifecycle_rule, server_side_encryption_configuration, acl, ...) are now read-only from version 4.0 of the Terraform AWS Provider. Those fields affect the following queries:

  - **website**: s3_static_website_host_enabled
  - **cors_rule**: s3_bucket_with_unsecured_cors_rule
  - **versioning**: s3_bucket_without_versioning
                       s3_bucket_without_enabled_mfa_delete
  - **logging**: s3_bucket_logging_disabled
                         cloudtrail_log_files_s3_bucket_with_logging_disabled
  - **lifecycle_rule**: s3_bucket_without_enabled_mfa_delete
  - **server_side_encryption_configuration**: s3_bucket_sse_disabled
  - **acl**: cloudtrail_log_files_s3_bucket_is_publicly_accessible
           s3_bucket_acl_allows_read_or_write_to_all_users
           s3_bucket_acl_allows_read_to_any_authenticated_user
           s3_bucket_public_acl_overridden_by_public_access_block

I submit this contribution under the Apache-2.0 license.

2022-05-16 14:04 UTC, joaorufi requested changes

2022-05-16 14:04 UTC, joaorufi commented on assets/queries/terraform/aws/s3_bucket_acl_allows_read_or_write_to_all_users/query.rego
> +		"keyExpectedValue": "'acl' equals 'private'",
```suggestion
		"keyExpectedValue": "'acl' to be equal to 'private'",
```

2022-05-16 14:04 UTC, joaorufi commented on assets/queries/terraform/aws/s3_bucket_acl_allows_read_or_write_to_all_users/query.rego
> +		"keyExpectedValue": sprintf("aws_s3_bucket_acl[%s].acl is private", [name]),
```suggestion
		"keyExpectedValue": sprintf("aws_s3_bucket_acl[%s].acl to be private", [name]),
```

2022-05-16 14:04 UTC, joaorufi commented on assets/queries/terraform/aws/s3_bucket_acl_allows_read_to_any_authenticated_user/query.rego
> +		"keyExpectedValue": sprintf("aws_s3_bucket_acl[%s].acl is private", [name]),
```suggestion
		"keyExpectedValue": sprintf("aws_s3_bucket_acl[%s].acl to be private", [name]),
```

2022-05-16 14:04 UTC, joaorufi commented on assets/queries/terraform/aws/s3_bucket_logging_disabled/query.rego
> +        "keyExpectedValue": "'logging' is defined and not null",
```suggestion
        "keyExpectedValue": "'logging' to be defined and not null",
```

2022-05-16 14:04 UTC, joaorufi commented on assets/queries/terraform/aws/s3_bucket_logging_disabled/query.rego
> +        "keyExpectedValue": "'logging' is defined and not null",
```suggestion
        "keyExpectedValue": "'logging' to be defined and not null",
```

2022-05-16 14:04 UTC, joaorufi commented on assets/queries/terraform/aws/s3_bucket_without_versioning/query.rego
> +        "keyExpectedValue": "'versioning' is set to true",
```suggestion
        "keyExpectedValue": "'versioning' to be true",
```

2022-05-16 14:04 UTC, joaorufi commented on assets/queries/terraform/aws/s3_bucket_without_versioning/query.rego
> +        "keyExpectedValue": "'versioning' is set to true",
```suggestion
        "keyExpectedValue": "'versioning' to be true",
```

2022-05-16 14:04 UTC, joaorufi commented on assets/queries/terraform/aws/s3_bucket_without_versioning/query.rego
> +        "keyExpectedValue": "'versioning.enabled' is set to true",
```suggestion
        "keyExpectedValue": "'versioning.enabled' to be true",
```

2022-05-16 14:04 UTC, joaorufi commented on assets/queries/terraform/aws/s3_bucket_without_versioning/query.rego
> +        "keyExpectedValue": "'versioning.enabled' is set to true",
```suggestion
        "keyExpectedValue": "'versioning.enabled' to be true",
```

2022-05-16 14:04 UTC, joaorufi commented on assets/queries/terraform/aws/s3_bucket_without_versioning/query.rego
> +        "keyExpectedValue": "'versioning.enabled' is set to true",
```suggestion
        "keyExpectedValue": "'versioning.enabled' to be true",
```

2022-05-16 14:04 UTC, joaorufi commented on assets/queries/terraform/aws/s3_bucket_without_versioning/query.rego
> +        "keyExpectedValue": "'versioning.enabled' is set to true",
```suggestion
        "keyExpectedValue": "'versioning.enabled' to be true",
```

2022-05-16 14:04 UTC, joaorufi commented on assets/queries/terraform/aws/s3_bucket_without_versioning/query.rego
> +        "keyExpectedValue": "'versioning_configuration.status' is set to 'Enabled'",
```suggestion
        "keyExpectedValue": "'versioning_configuration.status' to be set to 'Enabled'",
```

2022-06-06 08:19 UTC, nunoocx approved these changes
LGTM

2022-06-06 09:55 UTC, merged