fix(query): Show privilege_escalation_allowed k8s alert also in case no securityContext is defined
Checkmarx/kics pull request #4885
Opened 2022-02-27 22:51 UTC by Churro

**Problem**

The `privilege_escalation_allowed` rule is rated high and, indeed, represents a very security-relevant setting. Currently, the rule does not trigger an alert in case no `securityContext` is defined with a container. There is a separate rule to check whether `securityContext` exists but the severity rating is low. Hence, alerts for a rule with high severity are only shown if a user acts upon a low severity rule. 

Therefore, I suggest to change the rule to always show the alert, regardless of the existence of `securityContext`. This is important since a report otherwise does not provide a full picture of issues that demand for action.

**Proposed Changes**

- Make the definition of `securityContext` optional, such that an alert is also shown in case `container.securityContext` is undefined

I submit this contribution under the Apache-2.0 license.

2022-03-02 12:05 UTC, rafaela-soares requested changes
Another great observation and refactor, @Churro 🚀 Thank you!

I have two request changes:

2022-03-02 12:05 UTC, rafaela-soares commented on assets/queries/k8s/privilege_escalation_allowed/query.rego
> +		"keyActualValue": sprintf("metadata.name={{%s}}.%s.%s.name={{%s}}.securityContext.allowPrivilegeEscalation is undefined", [metadata.name, specInfo.path, types[x], container.name]),
```suggestion
		"keyExpectedValue": sprintf("metadata.name={{%s}}.%s.%s.name={{%s}}.securityContext.allowPrivilegeEscalation is set and is false", [metadata.name, specInfo.path, types[x], container.name]),
		"keyActualValue": sprintf("metadata.name={{%s}}.%s.%s.name={{%s}}.securityContext.allowPrivilegeEscalation is undefined", [metadata.name, specInfo.path, types[x], container.name]),
```

2022-03-02 14:02 UTC, Churro commented
Suggestions applied, thank you for the thorough review @rafaela-soares! 👍

2022-03-15 10:48 UTC, joaoReigota1 requested changes
Hi @Churro, everything looks good to me, the only thing I would like to request here is the use of the searchLine

Thank you for your great contributions

2022-03-15 19:12 UTC, Churro commented
Hi @joaoReigota1, thank you for the review. I've now added `searchLine` and another positive testcase related to that

2022-03-16 09:16 UTC, joaoReigota1 approved these changes
LGTM 🚀

2022-03-16 09:41 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-16 09:42 UTC, merged