fix(query): Fix path to spec in root_container_not_mounted_as_read_only k8s rule
Checkmarx/kics pull request #4893
Opened 2022-02-27 23:18 UTC by Churro

**Proposed Changes**

- Fold the check for the existence of `container.securityContext` with the check for `readOnlyRootFilesystem`
- Correct the spec reference `searchKey` to the actual path

I submit this contribution under the Apache-2.0 license.

2022-03-09 14:38 UTC, rafaela-soares requested changes
Hi, @Churro! Thank you so much for another great contribution!

I only have one request:

2022-03-09 14:38 UTC, rafaela-soares commented on assets/queries/k8s/root_container_not_mounted_as_read_only/metadata.json
> +  "queryName": "Root Container Not Mounted Read-only",
Can you also update the queryName in the `positive_expected_result.json`, please?

2022-03-15 11:15 UTC, joaoReigota1 requested changes
Hi @Churro, everything looks good to me, the only thing I would like to request here is the use of the searchLine

Thank you for your great contributions

2022-03-15 19:20 UTC, Churro commented
Hi @joaoReigota1, thank you for the review. As requested, I've now added the `searchLine` attribute

2022-03-16 09:17 UTC, joaoReigota1 approved these changes

2022-03-16 09:46 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-16 09:47 UTC, merged