Add cpu_requests query Closes #487
Checkmarx/kics pull request #490
Opened 2020-11-27 13:30 UTC by rafaela-soares

Since attribute 'containers' is an array, it is necessary to check if all containers have CPU requests.

Closes #487

2020-12-02 14:27 UTC, joelsou5a requested changes

2020-12-02 14:27 UTC, joelsou5a commented on assets/queries/k8s/cpu_requests/query.rego
> +package Cx
Check the query attached, it does have a more specific searchKey

[query.zip](https://github.com/Checkmarx/kics/files/5629863/query.zip)

2020-12-02 14:27 UTC, joelsou5a commented on assets/queries/k8s/cpu_requests/test/positive_expected_result.json
> +		"line": 6
"line": 11

2020-12-06 23:02 UTC, joaomartinscx requested changes

2020-12-06 23:02 UTC, joaomartinscx commented on assets/queries/k8s/cpu_requests/query.rego
> +    object.get(containers[index]["resources"]["requests"], "cpu", "undefined") == "undefined"
In this case, when resources or requests aren't present, the query will not detect these edge cases. I suggest to test them separately.

2020-12-08 10:28 UTC, joaomartinscx requested changes

2020-12-08 10:28 UTC, joaomartinscx commented on assets/queries/k8s/cpu_requests/query.rego
> +                "keyActualValue":    sprintf("%s.containers.name=%s doesn't have CPU requests",[specInfo.path, containers[index].name])
Make clear the path where the content should be present

2020-12-11 10:24 UTC, joaomartinscx reviewed
Everything looks good to me, I recommend approval and merge of this PR.

2020-12-11 11:46 UTC, joelsou5a approved these changes

2020-12-11 11:46 UTC, merged