fix(query): Extend memory_limits_not_defined k8s rule to cover further resource kinds
Checkmarx/kics pull request #4943
Opened 2022-03-08 23:31 UTC by Churro

**Proposed Changes**

- Extend the rule to cover additional resource kinds, e.g., Deployment, DaemonSet, etc.
- New positive test case that covers `MissingAttribute` in a Deployment
- More comprehensive description about security implications

I submit this contribution under the Apache-2.0 license.

2022-03-15 11:16 UTC, joaoReigota1 requested changes
Hi @Churro, everything looks good to me, the only thing I would like to request here is the use of the searchLine

Thank you for your great contributions

2022-03-15 19:34 UTC, Churro commented
Hi @joaoReigota1, thank you for the review. As requested, I've now added the `searchLine` attribute

2022-03-16 09:20 UTC, joaoReigota1 approved these changes

2022-03-16 09:42 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-16 09:43 UTC, merged