Added Memory Requests Is Not Defined query #491
Checkmarx/kics pull request #495
Opened 2020-11-27 14:01 UTC by joelcarvalhocheckmarx

It's important to specify a memory request.

Closes #491

2020-12-02 14:49 UTC, joelsou5a requested changes

2020-12-02 14:49 UTC, joelsou5a commented on assets/queries/k8s/memory_requests_not_defined/query.rego
> +   exists_containers
redundant can be removed

2020-12-02 14:49 UTC, joelsou5a commented on assets/queries/k8s/memory_requests_not_defined/query.rego
> +   exists_containers
can be removed is redudant

2020-12-02 14:49 UTC, joelsou5a commented on assets/queries/k8s/memory_requests_not_defined/query.rego
> +   exists_resources
can be removed is redudant

2020-12-02 14:49 UTC, joelsou5a commented on assets/queries/k8s/memory_requests_not_defined/query.rego
> +   spec := input.document[i].spec
metadata := document.metadata
spec := document.spec 
containers := spec.containers

2020-12-02 14:49 UTC, joelsou5a commented on assets/queries/k8s/memory_requests_not_defined/query.rego
> +   requests := spec.containers[c].resources.requests
requests := containers[c].resources.requests

2020-12-02 14:49 UTC, joelsou5a commented on assets/queries/k8s/memory_requests_not_defined/query.rego
> +                "searchKey": 	    sprintf("spec.containers[%d].requests.memory", [c]),
"searchKey": 	    sprintf("metadata.name=%s.spec.containers.name=%s.requests.memory", [metadata.name, containers[c].name]),

2020-12-02 14:49 UTC, joelsou5a commented on assets/queries/k8s/memory_requests_not_defined/query.rego
> +                "searchKey": 	    "spec",
"searchKey": sprintf("metadata.name=%s.spec", [metadata.name]),

2020-12-02 14:49 UTC, joelsou5a commented on assets/queries/k8s/memory_requests_not_defined/query.rego
> +CxPolicy [ result ] {
document := input.document[i]

2020-12-02 14:49 UTC, joelsou5a commented on assets/queries/k8s/memory_requests_not_defined/query.rego
> +                "searchKey": 	    sprintf("spec.containers[%d]", [c]),
"searchKey": sprintf("metadata.name=%s.spec.containers.name=%s", [metadata.name, containers[c].name]),

2020-12-02 14:49 UTC, joelsou5a commented on assets/queries/k8s/memory_requests_not_defined/query.rego
> +                "searchKey": 	    sprintf("spec.containers[%d]", [c]),
"searchKey": sprintf("metadata.name=%s.spec.containers.name=%s", [metadata.name, containers[c].name]),

2020-12-02 14:49 UTC, joelsou5a commented on assets/queries/k8s/memory_requests_not_defined/test/positive_expected_result.json
> +		"line": 6
"line": 13

2020-12-02 14:59 UTC, joelsou5a requested changes

2020-12-02 14:59 UTC, joelsou5a commented on assets/queries/k8s/memory_requests_not_defined/query.rego
> +   spec := input.document[i].spec
document := input.document[i]
 spec := document.spec
metadata := document.metadata

2020-12-06 23:14 UTC, joaomartinscx submitted a review, later dismissed

2020-12-06 23:14 UTC, joaomartinscx commented on assets/queries/k8s/memory_requests_not_defined/query.rego
> +   requests := containers[c].resources.requests
The query won't detect that these attributes, *resources* and *requests*, are not present. If you wish to enforce an attribute to existing at a lower level, you should guarantee the parent exists. I suggest to test these different edge cases and present different results for each.

2020-12-07 14:22 UTC, joelsou5a approved these changes

2020-12-07 14:28 UTC, merged