Added Memory Limits Not Defined query #492
Checkmarx/kics pull request #497
Opened 2020-11-27 14:13 UTC by joelcarvalhocheckmarx

It's important to specify a memory limit.

Closes #492

2020-12-02 14:59 UTC, joelsou5a requested changes

2020-12-02 14:59 UTC, joelsou5a commented on assets/queries/k8s/memory_limits_not_defined/query.rego
> +                "searchKey": 	    sprintf("spec.containers[%d].limits.memory", [c]),
Add metadata filter:

"searchKey": sprintf("metadata.name=%s.spec.containers.name=%s.limits.memory", [metadata.name, containers[c].name]),

2020-12-02 14:59 UTC, joelsou5a commented on assets/queries/k8s/memory_limits_not_defined/query.rego
> +   spec := input.document[i].spec
document := input.document[i]
spec := document .spec
metadata := document.metadata

2020-12-02 14:59 UTC, joelsou5a commented on assets/queries/k8s/memory_limits_not_defined/query.rego
> +                "searchKey": 	    "spec",
"searchKey": sprintf("metadata.name=%s.spec", [metadata.name]),

2020-12-02 14:59 UTC, joelsou5a commented on assets/queries/k8s/memory_limits_not_defined/query.rego
> +   spec := input.document[i].spec
document := input.document[i]
spec := document.spec
metadata := document.metadata

2020-12-02 14:59 UTC, joelsou5a commented on assets/queries/k8s/memory_limits_not_defined/query.rego
> +                "searchKey": 	    sprintf("spec.containers[%d]", [c]),
Add the changes do achieve this (like the ones on the comments before)

"searchKey": sprintf("metadata.name=%s.spec.containers.name=%s", [metadata.name, containers[c].name]),

2020-12-02 14:59 UTC, joelsou5a commented on assets/queries/k8s/memory_limits_not_defined/query.rego
> +                "searchKey": 	    sprintf("spec.containers[%d]", [c]),
Add the changes do achieve this (like the ones on the comments before)

"searchKey": sprintf("metadata.name=%s.spec.containers.name=%s", [metadata.name, containers[c].name]),

2020-12-08 10:41 UTC, joaomartinscx reviewed
Everything seems okay to me, I will recommend approval and merge of this PR.

2020-12-10 16:34 UTC, ruigomescx approved these changes

2020-12-10 16:34 UTC, merged