Add containter_security_context Closes #493
Checkmarx/kics pull request #499
Opened 2020-11-27 14:21 UTC by rafaela-soares

Since security context should be applied in pods and containers, I thought in two cases:

- Pod has not a security context applied

- All or some containers have not a security context applied

Closes #493

2020-12-02 15:03 UTC, joelsou5a requested changes

2020-12-02 15:03 UTC, joelsou5a commented on assets/queries/k8s/container_security_context/query.rego
> +    specInfo := getSpecInfo(document)
Add metadata information to get a more specific searchKey
metadata := document.metadata

2020-12-02 15:03 UTC, joelsou5a commented on assets/queries/k8s/container_security_context/query.rego
> +                "searchKey": 	      sprintf("%s", [specInfo.path]),
"searchKey": sprintf("metadata.name=%s.%s", [metadata.name, specInfo.path]),

2020-12-02 15:03 UTC, joelsou5a commented on assets/queries/k8s/container_security_context/query.rego
> +                "searchKey": 	      sprintf("%s.containers", [specInfo.path]),
"searchKey": sprintf("metadata.name=%s.%s.containers", [metadata.name, specInfo.path]),

2020-12-02 15:03 UTC, joelsou5a commented on assets/queries/k8s/container_security_context/query.rego
> +    document := input.document[i]
Add metadata information to get a more specific searchKey
metadata := document.metadata

2020-12-07 14:52 UTC, joelsou5a commented on assets/queries/k8s/container_security_context/query.rego
> +    count({x | containers[x]; object.get(containers[x], "securityContext", "undefined") != "undefined" }) != lengthContainers
You could iterate over the containers and specify each of them are failing.

2020-12-08 10:49 UTC, joaomartinscx requested changes

2020-12-08 10:49 UTC, joaomartinscx commented on assets/queries/k8s/container_security_context/metadata.json
> +  "queryName": "Container Security Context",
Query name should identify the problem with the resource, like in this case, if the container or Pod doesn't have a security context defined

2020-12-11 10:22 UTC, joaomartinscx requested changes

2020-12-11 10:22 UTC, joaomartinscx commented on assets/queries/k8s/without_security_context/query.rego
> +                "keyActualValue": 	  sprintf("metadata.name=%s does not have a security context",[specInfo.path])
I think you meant **metadata.name** instead of **specInfo.path** here

2020-12-11 10:35 UTC, joaomartinscx reviewed
Everything looks good to me, I recommend approval and merge of this PR.

2020-12-11 11:44 UTC, joelsou5a approved these changes

2020-12-11 11:45 UTC, merged