Feat(Query): Kubernetes Yaml Streaming Connection Timeout Disabled
Checkmarx/kics pull request #5007
Opened 2022-03-17 10:46 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: Streaming Connection Timeout Disabled for Kubernetes Yaml

I submit this contribution under the Apache-2.0 license.

2022-03-17 14:58 UTC, rafaela-soares requested changes

2022-03-17 14:58 UTC, rafaela-soares commented on assets/queries/k8s/streaming_connection_timeout_disabled/query.rego
> +		"searchLine": common_lib.build_search_line(["metadata", "name"], []),
```suggestion
        "searchLine": common_lib.build_search_line(split(specInfo.path, "."), [types[x], j, "command"])
```

2022-03-17 15:28 UTC, rafaela-soares requested changes

2022-03-17 15:28 UTC, rafaela-soares commented on assets/queries/k8s/streaming_connection_timeout_disabled/metadata.json
> +  "queryName": "Streaming Connection Timeout Disabled",
```suggestion
       "queryName": "Kubelet Streaming Connection Timeout Disabled",
```

Please, also update the query folder name and the `positive_expected_result.json`

2022-03-17 18:09 UTC, rafaela-soares requested changes

2022-03-17 18:09 UTC, rafaela-soares commented on assets/queries/k8s/kubelet_streaming_connection_timeout_disabled/query.rego
> +		"keyExpectedValue": "--streaming-connection-idle-timeout flag is not 0 or not set",
```suggestion
        "keyExpectedValue": "--streaming-connection-idle-timeout flag is not 0",
```

2022-03-18 14:46 UTC, joaorufi requested changes

2022-03-18 14:46 UTC, joaorufi commented on assets/queries/k8s/kubelet_streaming_connection_timeout_disabled/test/positive1.yaml
> +      image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.0
Use `kubelet` docker image
```suggestion
      image: joaodanielrufino/kubelet
```

2022-03-18 14:46 UTC, joaorufi commented on assets/queries/k8s/kubelet_streaming_connection_timeout_disabled/test/negative1.yaml
> +      image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.0
```suggestion
      image: joaodanielrufino/kubelet
```

2022-03-18 14:46 UTC, joaorufi commented on assets/queries/k8s/kubelet_streaming_connection_timeout_disabled/query.rego
> +		"keyExpectedValue": "--streaming-connection-idle-timeout flag is not 0",
```suggestion
		"keyExpectedValue": "--streaming-connection-idle-timeout flag not to be 0",
```

2022-03-18 14:46 UTC, joaorufi commented on assets/queries/k8s/kubelet_streaming_connection_timeout_disabled/query.rego
> +		"keyExpectedValue": "streamingConnectionIdleTimeout is not 0s",
```suggestion
		"keyExpectedValue": "streamingConnectionIdleTimeout not to be 0s",
```

2022-03-18 15:46 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-21 11:52 UTC, rafaela-soares submitted a review, later dismissed

2022-03-21 15:27 UTC, joaorufi approved these changes

2022-03-21 16:09 UTC, merged