Feat.(Query): Kubernetes Kubelet Not Managing Ip Tables
Checkmarx/kics pull request #5009
Opened 2022-03-17 12:48 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: Kubelet Not Managing Ip Tables

I submit this contribution under the Apache-2.0 license.

2022-03-17 18:12 UTC, rafaela-soares commented on assets/queries/k8s/kubelet_not_managing_ip_tables/query.rego
> +		"keyExpectedValue": "--make-iptables-util-chains flag is true or not set",
```suggestion
        "keyExpectedValue": "--make-iptables-util-chains flag is true",
```

2022-03-17 18:31 UTC, rafaela-soares requested changes

2022-03-17 18:31 UTC, rafaela-soares commented on assets/queries/k8s/kubelet_not_managing_ip_tables/query.rego
> +		"searchKey": sprintf("kind={{%s}}.makeIPTablesUtilChains", [resource.kind]),
```suggestion
        "searchKey": "kind={{KubeletConfiguration}}.makeIPTablesUtilChains",
```

2022-03-18 14:42 UTC, joaorufi requested changes

2022-03-18 14:42 UTC, joaorufi commented on assets/queries/k8s/kubelet_not_managing_ip_tables/query.rego
> +		"keyExpectedValue": "--make-iptables-util-chains flag is true",
```suggestion
		"keyExpectedValue": "--make-iptables-util-chains flag to be true",
```

2022-03-18 14:42 UTC, joaorufi commented on assets/queries/k8s/kubelet_not_managing_ip_tables/query.rego
> +		"keyExpectedValue": "makeIPTablesUtilChains is true",
```suggestion
		"keyExpectedValue": "makeIPTablesUtilChains to be true",
```

2022-03-18 14:42 UTC, joaorufi commented on assets/queries/k8s/kubelet_not_managing_ip_tables/test/negative1.yaml
> +      image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.0
For `kubelet` commands you need to use it's docker image
```suggestion
      image: joaodanielrufino/kubelet
```

2022-03-18 14:42 UTC, joaorufi commented on assets/queries/k8s/kubelet_not_managing_ip_tables/test/negative4.yaml
> +      image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.0
```suggestion
      image: joaodanielrufino/kubelet
```

2022-03-18 14:42 UTC, joaorufi commented on assets/queries/k8s/kubelet_not_managing_ip_tables/test/positive1.yaml
> +      image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.0
```suggestion
      image: joaodanielrufino/kubelet
```

2022-03-18 15:49 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-21 15:27 UTC, joaorufi approved these changes

2022-03-21 16:12 UTC, merged