feat(query): TSL Connection Certificate Not Setup for Kubernetes
Checkmarx/kics pull request #5011
Opened 2022-03-17 17:11 UTC by cxMiguelSilva

**Proposed Changes**
- TSL Connection Certificate Not Setup for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-03-17 18:40 UTC, rafaela-soares requested changes

2022-03-18 14:39 UTC, joaorufi requested changes

2022-03-18 14:39 UTC, joaorufi commented on assets/queries/k8s/tls_connection_certificate_not_setup/test/negative3.yaml
> +      image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.0
To use `kubelet` commands you need to use kubelet docker image
```suggestion
      image: joaodanielrufino/kubelet
```

2022-03-21 17:30 UTC, joaorufi commented on assets/queries/k8s/tls_connection_certificate_not_setup/test/negative1.yaml
> +      image: joaodanielrufino/kubelet
Use the `kube-apiserver` docker image
```suggestion
      image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.0
```

2022-03-21 17:31 UTC, joaorufi commented on assets/queries/k8s/tls_connection_certificate_not_setup/test/positive1.yaml
> +      image: joaodanielrufino/kubelet
Same here
```suggestion
      image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.0
```

2022-03-21 17:41 UTC, joaorufi approved these changes

2022-03-22 09:37 UTC, merged