Feat(Query):  Kubelet Client Periodic Certificate Switch Disabled
Checkmarx/kics pull request #5016
Opened 2022-03-18 13:23 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: Kubelet Client Periodic Certificate Switch Disabled

I submit this contribution under the Apache-2.0 license.

2022-03-18 14:35 UTC, joaorufi requested changes

2022-03-18 14:35 UTC, joaorufi commented on assets/queries/k8s/kubelet_client_periodic_certificate_switch_disabled/test/negative1.yaml
> +      image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.0
This image is for `kube-apiserver`, you should use the kubelet docker image
```suggestion
      image: joaodanielrufino/kubelet
```

2022-03-18 14:35 UTC, joaorufi commented on assets/queries/k8s/kubelet_client_periodic_certificate_switch_disabled/test/positive1.yaml
> +      image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.0
Same here

2022-03-18 14:35 UTC, joaorufi commented on assets/queries/k8s/kubelet_client_periodic_certificate_switch_disabled/query.rego
> +		"keyExpectedValue": "--rotate-certificates flag is true",
```suggestion
		"keyExpectedValue": "--rotate-certificates flag to be true",
```

2022-03-18 14:35 UTC, joaorufi commented on assets/queries/k8s/kubelet_client_periodic_certificate_switch_disabled/query.rego
> +		"keyExpectedValue": "rotateCertificates is true",
```suggestion
		"keyExpectedValue": "rotateCertificates to be true",
```

2022-03-18 15:52 UTC, rafaela-soares submitted a review, later dismissed
LGTM 🚀

2022-03-21 11:53 UTC, rafaela-soares approved these changes

2022-03-21 15:26 UTC, joaorufi approved these changes

2022-03-21 16:16 UTC, merged