feat(query): Added Weak TLS Cipher Suites for Kubernetes
Checkmarx/kics pull request #5027
Opened 2022-03-22 10:43 UTC by cxMiguelSilva

**Proposed Changes**
-Added Weak TLS Cipher Suites for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-03-22 20:33 UTC, Churro commented on assets/queries/k8s/weak_tls_cipher_suites/query.rego
> +    "TLS_RSA_WITH_AES_128_GCM_SHA256",
Probably worth mentioning here if I may: these two both use RSA for key exchange, which means no support Perfect Forward Secrecy (PFS). By modern standards, they cannot be considered "strong" anymore.

2022-03-23 09:57 UTC, rafaela-soares commented on assets/queries/k8s/weak_tls_cipher_suites/query.rego
> +    "TLS_RSA_WITH_AES_128_GCM_SHA256",
All the inputs are always welcome, @Churro 😊 Thank you so much!

I took a deeper look in the CIS_Kubernetes_Benchmark_v1.6.0 documentation, and it refers to both of them as strong in **4.2.13**:

![image](https://user-images.githubusercontent.com/74001161/159672688-e1d9bc6f-e90a-416d-9f31-af7b4297a46d.png)


However, **1.2.35** does not mention them in the remediation.

![image](https://user-images.githubusercontent.com/74001161/159672392-43d51f32-372a-4bc0-8b6c-31985284b334.png)

2022-03-28 17:47 UTC, joaorufi requested changes

2022-03-30 09:13 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-30 12:27 UTC, joaorufi approved these changes

2022-03-30 12:31 UTC, merged