feat(query): Added Client Certificate Authentication Not Setup Properly for Kubernetes
Checkmarx/kics pull request #5028
Opened 2022-03-22 12:42 UTC by cxMiguelSilva

**Proposed Changes**
-Added Client Certificate Authentication Not Setup Properly for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-03-28 17:52 UTC, joaorufi requested changes

2022-03-28 17:52 UTC, joaorufi commented on assets/queries/k8s/client_certificate_authentication_not_setup_properly/query.rego
> +		"searchKey": sprintf("kind={{%s}}", ["KubeletConfiguration"]),
```suggestion
		"searchKey": "kind={{KubeletConfiguration}}",
```

2022-03-28 17:52 UTC, joaorufi commented on assets/queries/k8s/client_certificate_authentication_not_setup_properly/query.rego
> +		"searchKey": sprintf("kind={{%s}}", ["KubeletConfiguration"]),
```suggestion
		"searchKey": "kind={{KubeletConfiguration}}",
```

2022-03-29 16:09 UTC, joaorufi approved these changes

2022-03-30 08:28 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-30 08:28 UTC, merged