Feat(Query): Privileged Containers Enabled for Docker Compose
Checkmarx/kics pull request #5029
Opened 2022-03-22 14:54 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: Privileged Containers Enabled for Docker Compose

I submit this contribution under the Apache-2.0 license.

2022-03-25 18:11 UTC, rafaela-soares requested changes

2022-03-25 18:11 UTC, rafaela-soares commented on assets/queries/dockerCompose/privileged_containers_enabled/query.rego
> +    privileged := service_parameters[name2].privileged
Please, do deeper research about where the field `privileged` can be defined. I think this approach is not correct.

Observe the output of the docker-compose, please:

![image](https://user-images.githubusercontent.com/74001161/160177499-c4ed093f-fe6a-4866-8d43-9a236aaea530.png)


Probably, the best approach is the following (Please, confirm it):

```suggestion
    privileged := service_parameters.privileged
```

![image](https://user-images.githubusercontent.com/74001161/160177769-7fc833b6-2234-4d3e-9d2c-2520264286fb.png)

2022-03-28 11:46 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-28 17:52 UTC, joaorufi approved these changes

2022-03-29 11:35 UTC, merged