Feat(Query): Volume Has Sensitive Host Directory for Docker Compose
Checkmarx/kics pull request #5034
Opened 2022-03-23 12:39 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: Volume Has Sensitive Host Directory (for Docker Compose)
- Functions: isOSDir, listcontains to common_lib (by Rogério Peixoto)

I submit this contribution under the Apache-2.0 license.

2022-03-23 14:55 UTC, rafaela-soares requested changes

2022-03-23 14:55 UTC, rafaela-soares commented on assets/libraries/common.rego
> +		"/seLinux", "/srv", "/usr", "/var",
We should add "/sys" as recommended by AppSec

2022-03-23 14:55 UTC, rafaela-soares commented on assets/queries/dockerCompose/volume_has_sensitive_host_directory/query.rego
> +    host_path := split(volumes[0] ,":")
```suggestion
    volume := volumes[v]
    host_path := split(volume,":")
```

We want to check all the volumes and not the first one

2022-03-23 14:55 UTC, rafaela-soares commented on assets/queries/dockerCompose/volume_has_sensitive_host_directory/query.rego
> +		"keyActualValue": "Docker compose file has 'volumes' attribute set to a sensitive directory",
```suggestion
		"keyExpectedValue": "There is no sensitive directory mounted as a volume",
		"keyActualValue": sprintf("There is a sensitive directory (%s) mounted as a volume", [hostPath1]),
		"searchLine": common_lib.build_search_line(["services", name, "volumes", v], []),
```

2022-03-23 15:34 UTC, rafaela-soares requested changes

2022-03-23 15:34 UTC, rafaela-soares commented on assets/queries/dockerCompose/volume_has_sensitive_host_directory/query.rego
> +    host_path1 := host_path[1]
```suggestion
    host_path1 := host_path[0]
```

Please, update the samples. We should look to the left side

2022-03-25 15:35 UTC, rafaela-soares requested changes

2022-03-25 15:35 UTC, rafaela-soares commented on assets/queries/dockerCompose/volume_has_sensitive_host_directory/query.rego
> +    host_path := path[0]
```suggestion
    host_path := volume.source
```

2022-03-25 15:36 UTC, rafaela-soares requested changes

2022-03-25 15:36 UTC, rafaela-soares commented on assets/queries/dockerCompose/volume_has_sensitive_host_directory/query.rego
> +		"searchLine": common_lib.build_search_line(["services", name, "volumes", "source"], []),
```suggestion
        "searchLine": common_lib.build_search_line(["services", name, "volumes", v, "source"], []),
```

2022-03-28 17:55 UTC, joaorufi approved these changes

2022-03-29 13:33 UTC, joaorufi submitted a review, later dismissed

2022-03-29 16:11 UTC, joaorufi approved these changes

2022-03-29 17:35 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-29 17:35 UTC, merged