feat(query): ETCD Not Unique Certificate Authority for Kubernetes
Checkmarx/kics pull request #5035
Opened 2022-03-23 14:20 UTC by cx-miguel-dasilva

**Proposed Changes**
- Not Unique Certificate Authority for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-03-23 15:07 UTC, rafaela-soares commented on assets/queries/k8s/not_unique_certificate_authority/metadata.json
> +    "descriptionUrl": "https://kubernetes.io/docs/reference/using-api/deprecation-policy/",
```suggestion
    "descriptionText": "Certificate Authority should be unique for etcd",
    "descriptionUrl": "https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/",
```

2022-03-28 17:59 UTC, joaorufi requested changes

2022-03-28 17:59 UTC, joaorufi commented on assets/queries/k8s/not_unique_certificate_authority/test/positive_expected_result.json
> +]
You have 2 positive samples but only one in positive expected result

2022-03-29 11:48 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-29 14:16 UTC, merged