Feat(Query): Privileged Ports Mapped In Container for Docker Compose
Checkmarx/kics pull request #5044
Opened 2022-03-24 14:54 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: Privileged Ports Mapped In Container for Docker Compose

**Notes**
- The check of cap_drop itself being missing is done in another query.

I submit this contribution under the Apache-2.0 license.

2022-03-25 18:29 UTC, rafaela-soares requested changes

2022-03-25 18:29 UTC, rafaela-soares commented on assets/queries/dockerCompose/privileged_ports_mapped_in_container/query.rego
> +}
```suggestion
```

We should check the 'cap_drop: NET_BIND_SERVICE' in the policy below

2022-03-25 18:29 UTC, rafaela-soares commented on assets/queries/dockerCompose/privileged_ports_mapped_in_container/query.rego
> +
```suggestion
     not has_cap_drop(service_parameters)
```

```
has_cap_drop(cap_drop) {
     service_parameters.cap_drop[_] == "NET_BIND_SERVICE"
}
```

2022-03-28 18:04 UTC, joaorufi approved these changes

2022-03-29 11:42 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-29 13:37 UTC, joaorufi approved these changes

2022-03-29 13:58 UTC, merged