Feat(Query): Network Mode Host Exists for Docker Compose
Checkmarx/kics pull request #5051
Opened 2022-03-25 14:51 UTC by cxAndreFelicidade

**Proposed Changes**
- Query:
- Network Mode Host Exists

I submit this contribution under the Apache-2.0 license.

2022-03-25 18:37 UTC, rafaela-soares requested changes

2022-03-25 18:37 UTC, rafaela-soares commented on assets/queries/dockerCompose/network_mode_host_exists/metadata.json
> +    "queryName": "Network Mode Host Exists",
```suggestion
    "queryName": "Shared Host Network Namespace",
```

Please, also update the query folder name

2022-03-25 18:37 UTC, rafaela-soares commented on assets/queries/dockerCompose/network_mode_host_exists/metadata.json
> +    "descriptionText": "Check if network mode: host exists in the docker compose document.",
```suggestion
    "descriptionText": "Container should not share the host network namespace",
```

2022-03-28 17:21 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-28 18:13 UTC, joaorufi approved these changes

2022-03-29 11:35 UTC, merged