Feat(Query): Memory Not Limited for Docker Compose
Checkmarx/kics pull request #5052
Opened 2022-03-25 15:58 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: Memory Not Limited for Docker Compose

I submit this contribution under the Apache-2.0 license.

2022-03-25 18:43 UTC, rafaela-soares requested changes

2022-03-25 18:43 UTC, rafaela-soares commented on assets/queries/dockerCompose/memory_not_limited/metadata.json
> +    "descriptionText": "Check if theres is a memory limit for containers in the docker compose document.",
```suggestion
    "descriptionText": "Memory limits should be defined for each container. This prevents potential resource exhaustion by ensuring that containers consume not more than the designated amount of memory",
```

2022-03-25 18:43 UTC, rafaela-soares commented on assets/queries/dockerCompose/memory_not_limited/query.rego
> +		"searchKey": sprintf("services.%s",[name]),
```suggestion
        "searchKey": sprintf("services.%s.deploy.resources.limits",[name]),
```

2022-03-25 18:43 UTC, rafaela-soares commented on assets/queries/dockerCompose/memory_not_limited/query.rego
> +		"searchLine": common_lib.build_search_line(["services", name], []),
```suggestion
		"searchLine": common_lib.build_search_line(["services", name, "deploy", "resources", "limits"], []),
```

2022-03-28 18:14 UTC, joaorufi submitted a review, later dismissed

2022-03-29 13:38 UTC, joaorufi approved these changes

2022-03-29 15:16 UTC, joaorufi requested changes

2022-03-29 15:16 UTC, joaorufi commented on assets/queries/dockerCompose/memory_not_limited/query.rego
> +		"keyExpectedValue": "'deploy.resources.limits.memory' is defined",
```suggestion
		"issueType": "MissingAttribute",
		"keyExpectedValue": "'deploy.resources.limits.memory' to be defined",
```

2022-03-29 15:16 UTC, joaorufi commented on assets/queries/dockerCompose/memory_not_limited/query.rego
> +		"keyExpectedValue": "'deploy.resources.limits.memory' is defined",
```suggestion
		"issueType": "MissingAttribute",
		"keyExpectedValue": "'deploy.resources' to be defined",
```

2022-03-29 15:57 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-29 17:36 UTC, merged