feat(query): Added Kubelet Certificate Authority Not Set for Kubernetes
Checkmarx/kics pull request #5067
Opened 2022-03-28 13:49 UTC by cxMiguelSilva

**Proposed Changes**
-Added Kubelet Certificate Authority Not Set for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-03-28 18:20 UTC, joaorufi approved these changes

2022-03-29 09:59 UTC, rafaela-soares requested changes

2022-03-29 09:59 UTC, rafaela-soares commented on assets/queries/k8s/kubelet_certificate_authority_not_set/query.rego
> +}
In my opinion, I think this policy is unnecessary
```suggestion
```

2022-03-29 14:21 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-29 14:47 UTC, merged