feat(query): Added Authorization Mode Node Not Set for Kubernetes
Checkmarx/kics pull request #5070
Opened 2022-03-28 14:56 UTC by cxMiguelSilva

**Proposed Changes**
-Added Authorization Mode Node Not Set for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-03-28 18:22 UTC, joaorufi requested changes

2022-03-29 10:04 UTC, rafaela-soares requested changes

2022-03-29 10:04 UTC, rafaela-soares commented on assets/queries/k8s/authorization_mode_node_not_set/metadata.json
> +  "descriptionText": "The authorization-mode flag should have 'Node' mode",
```suggestion
   "descriptionText": "When using kube-apiserver command, the 'authorization-mode' flag should have 'Node' mode",
```

2022-03-29 10:04 UTC, rafaela-soares commented on assets/queries/k8s/authorization_mode_node_not_set/query.rego
> +}
If you add it, please update the query `kics/assets/queries/k8s/authorization_mode_set_to_always_allow`

2022-03-29 10:06 UTC, rafaela-soares commented on assets/queries/k8s/authorization_mode_node_not_set/query.rego
> +}
If you add it, please update` kics\assets\queries\k8s\authorization_mode_set_to_always_allow`

2022-03-29 14:28 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-03-29 15:10 UTC, merged