feat(query): Added Namespace Lifecycle Admission Control Plugin Disabled for Kubernetes
Checkmarx/kics pull request #5092
Opened 2022-03-30 14:37 UTC by cxMiguelSilva

**Proposed Changes**
- Added Namespace Lifecycle Admission Control Plugin Disabled for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-04-05 11:48 UTC, rafaela-soares submitted a review, later dismissed
LGTM 🚀

2022-04-11 15:51 UTC, joaorufi requested changes

2022-04-11 15:51 UTC, joaorufi commented on assets/queries/k8s/namespace_lifecycle_admission_control_plugin_disabled/test/positive_expected_result.json
> +        "file": "positive2.yaml"
```suggestion
        "fileName": "positive2.yaml"
```

2022-04-11 17:28 UTC, joaorufi approved these changes

2022-04-11 17:28 UTC, merged