feat(query): Added Request Timeout Not Properly Set for Kubernetes
Checkmarx/kics pull request #5106
Opened 2022-03-31 15:22 UTC by cxMiguelSilva

**Proposed Changes**
- Added Request Timeout Not Properly Set for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-04-05 13:40 UTC, joaorufi requested changes
Please, remove payload.json file

2022-04-05 14:15 UTC, rafaela-soares requested changes

2022-04-05 14:15 UTC, rafaela-soares commented on assets/queries/k8s/request_timeout_not_properly_set/query.rego
> +}
Is this policy really necessary?

2022-04-11 09:18 UTC, rafaela-soares requested changes

2022-04-11 09:18 UTC, rafaela-soares commented on assets/queries/k8s/request_timeout_not_properly_set/query.rego
> +	regex.match("^(\\d{1,3}[h])$", time)
Maybe we should not limit the number of digits

2022-04-11 10:06 UTC, rafaela-soares submitted a review, later dismissed
LGTM 🚀

2022-04-11 17:33 UTC, joaorufi approved these changes

2022-04-11 17:34 UTC, merged