feat(query): Added Service Account Key File Not Properly Set for Kubernetes
Checkmarx/kics pull request #5108
Opened 2022-03-31 17:05 UTC by cxMiguelSilva

**Proposed Changes**
- Added Service Account Key File Not Properly Set for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-04-05 13:45 UTC, joaorufi requested changes

2022-04-05 13:45 UTC, joaorufi commented on assets/queries/k8s/service_account_key_file_not_properly_set/metadata.json
> +  "descriptionText": "When using kube-apiserver command, the '--service-account-key-file' flag should be difined and set a PEM encoded file",
Misspelling the word defined
```suggestion
  "descriptionText": "When using kube-apiserver command, the '--service-account-key-file' flag should be defined and set a PEM encoded file",
```

2022-04-05 14:53 UTC, rafaela-soares requested changes

2022-04-05 14:53 UTC, rafaela-soares commented on assets/queries/k8s/service_account_key_file_not_properly_set/query.rego
> +}
```suggestion
```
I think this policy is unnecessary

2022-04-05 14:53 UTC, rafaela-soares commented on assets/queries/k8s/service_account_key_file_not_properly_set/metadata.json
> +  "descriptionText": "When using kube-apiserver command, the '--service-account-key-file' flag should be defined and set a PEM encoded file",
```suggestion
  "descriptionText": "When using kube-apiserver command, the '--service-account-key-file' flag should be defined",
```

2022-04-11 09:16 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-04-11 17:34 UTC, joaorufi submitted a review, later dismissed

2022-04-12 13:48 UTC, merged