feat(query): Added Etcd TLS Certificate Not Properly Configured for Kubernetes
Checkmarx/kics pull request #5119
Opened 2022-04-04 08:49 UTC by cxMiguelSilva

**Proposed Changes**
- Added Etcd TLS Certificate Not Properly Configured for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-04-05 13:49 UTC, joaorufi requested changes

2022-04-05 13:49 UTC, joaorufi commented on assets/queries/k8s/etcd_tls_certificate_not_properly_configured/metadata.json
> +  "descriptionText": "When using kube-apiserver commands, the '--etcd-certfile' and '--etcd-keyfile' flags should be difined",
```suggestion
  "descriptionText": "When using kube-apiserver commands, the '--etcd-certfile' and '--etcd-keyfile' flags should be defined",
```

2022-04-05 14:56 UTC, rafaela-soares submitted a review, later dismissed
LGTM 🚀

2022-04-11 17:35 UTC, joaorufi approved these changes

2022-04-11 17:43 UTC, joaorufi requested changes

2022-04-11 17:43 UTC, joaorufi commented on assets/queries/k8s/etcd_tls_certificate_not_properly_configured/query.rego
> +}
Could you merge this two policies?

2022-04-12 13:50 UTC, merged