feat(query): Added Encryption Provider Not Properly Configured for Kubernetes
Checkmarx/kics pull request #5122
Opened 2022-04-04 10:31 UTC by cxMiguelSilva

**Proposed Changes**
- Added Encryption Provider Not Properly Configured for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-04-05 13:54 UTC, joaorufi requested changes

2022-04-05 13:54 UTC, joaorufi commented on assets/queries/k8s/encryption_provider_not_properly_configured/metadata.json
> +  "descriptionText": "The EncryptionConfiguration should configured to have at least one 'aescbc' provider",
```suggestion
  "descriptionText": "The EncryptionConfiguration should be configured to have at least one 'aescbc' provider",
```

2022-04-05 13:54 UTC, joaorufi commented on assets/queries/k8s/encryption_provider_not_properly_configured/query.rego
> +	not conatainsProvider(resource, "aescbc")
```suggestion
	not containsProvider(resource, "aescbc")
```

2022-04-05 13:54 UTC, joaorufi commented on assets/queries/k8s/encryption_provider_not_properly_configured/query.rego
> +conatainsProvider(resource, providerToCheck){
```suggestion
containsProvider(resource, providerToCheck){
```

2022-04-05 15:07 UTC, rafaela-soares requested changes

2022-04-05 15:07 UTC, rafaela-soares commented on assets/queries/k8s/encryption_provider_not_properly_configured/query.rego
> +	not containsProvider(resource, "aescbc")
Maybe we should also look for kms or secretbox

2022-04-11 10:06 UTC, rafaela-soares submitted a review, later dismissed
LGTM 🚀

2022-04-11 17:39 UTC, joaorufi approved these changes

2022-04-11 17:39 UTC, merged