feat(query): Added Terminated Pod Garbage Collector Threshold Not Properly Set for Kubernetes
Checkmarx/kics pull request #5123
Opened 2022-04-04 11:11 UTC by cxMiguelSilva

**Proposed Changes**
- Terminated Pod Garbage Collector Threshold Not Properly Set for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-04-05 13:57 UTC, joaorufi approved these changes

2022-04-11 09:33 UTC, rafaela-soares requested changes

2022-04-11 09:33 UTC, rafaela-soares commented on assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/metadata.json
> +  "descriptionText": "When using kube-controller-manager commands, the '--terminated-pod-gc-threshold' should be set to 10",
```suggestion
  "descriptionText": "When using kube-controller-manager commands, the '--terminated-pod-gc-threshold' should be set between 0 and 12501"
```

2022-04-11 09:34 UTC, rafaela-soares requested changes

2022-04-11 09:34 UTC, rafaela-soares commented on assets/queries/k8s/terminated_pod_garbage_collector_threshold_not_properly_set/query.rego
> +		"keyExpectedValue": "--terminated-pod-gc-threshold flag should be set to 10",
```suggestion
        "keyExpectedValue": "--terminated-pod-gc-threshold flag should be set between 0 and 12501",
```

2022-04-11 13:21 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-04-11 17:14 UTC, JoaoDanielRufino approved these changes

2022-04-11 17:15 UTC, joaorufi approved these changes

2022-04-11 17:15 UTC, merged