feat(query): Added Service Account Private Key File Not Defined for Kubernetes
Checkmarx/kics pull request #5126
Opened 2022-04-04 11:48 UTC by cxMiguelSilva

**Proposed Changes**
- Added Service Account Private Key File Not Defined for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-04-05 15:16 UTC, rafaela-soares requested changes

2022-04-05 15:16 UTC, rafaela-soares commented on assets/queries/k8s/service_account_private_key_file_not_defined/metadata.json
> +  "descriptionText": "When using kube-controller-manager commands, the '--terminated-pod-gc-threshold' should be set to 10",
```suggestion
  "descriptionText": "When using kube-controller-manager commands, the '--service-account-private-key-file' should be defined",
```

2022-04-11 09:37 UTC, rafaela-soares submitted a review, later dismissed
LGTM 🚀

2022-04-11 17:16 UTC, joaorufi approved these changes

2022-04-11 17:16 UTC, merged