feat(query): Added ETCD TLS Certificate Files Not Properly Set for Kubernetes
Checkmarx/kics pull request #5129
Opened 2022-04-04 14:26 UTC by cxMiguelSilva

**Proposed Changes**
- Added ETCD TLS Certificate Files Not Properly Set for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-04-05 15:38 UTC, rafaela-soares requested changes

2022-04-05 15:38 UTC, rafaela-soares commented on assets/queries/k8s/etcd_tls_certificate_files_not_properly_set/query.rego
> +		"issueType": "IncorrectValue",
```suggestion
        "issueType": "MissingAttribute",
```

2022-04-05 15:38 UTC, rafaela-soares commented on assets/queries/k8s/etcd_tls_certificate_files_not_properly_set/query.rego
> +		"issueType": "IncorrectValue",
```suggestion
        "issueType": "MissingAttribute",
```

2022-04-11 09:40 UTC, rafaela-soares requested changes

2022-04-11 09:40 UTC, rafaela-soares commented on assets/queries/k8s/etcd_tls_certificate_files_not_properly_set/query.rego
> +}
We could join these policies

2022-04-11 13:23 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-04-11 17:19 UTC, joaorufi approved these changes

2022-04-11 17:20 UTC, merged