Feat(Query): Container Traffic Not Bound to Host Interface
Checkmarx/kics pull request #5140
Opened 2022-04-05 15:20 UTC by cxAndreFelicidade

**Proposed Changes**
- Query:  Container Traffic Not Bound to Host Interface for docker compose.

I submit this contribution under the Apache-2.0 license.

2022-04-11 10:36 UTC, rafaela-soares requested changes

2022-04-11 10:36 UTC, rafaela-soares commented on assets/queries/dockerCompose/container_traffic_not_bound_to_host_interface/metadata.json
> +  "descriptionText": "Ports containing container traffic should be bound to a specific host IP address.",
```suggestion
  "descriptionText": "Incoming container traffic should be bound to a specific host interface",
```

2022-04-11 10:36 UTC, rafaela-soares commented on assets/queries/dockerCompose/container_traffic_not_bound_to_host_interface/query.rego
> +		"keyActualValue": "Docker compose file doesn't have 'ports' attribute bound to a host IP address.",
```suggestion
		"keyExpectedValue": "Docker compose file to have 'ports' attribute bound to a specific host interface.",
		"keyActualValue": "Docker compose file doesn't have 'ports' attribute bound to a specific host interface",
```

2022-04-11 10:53 UTC, rafaela-soares requested changes

2022-04-11 10:53 UTC, rafaela-soares commented on assets/queries/dockerCompose/container_traffic_not_bound_to_host_interface/query.rego
> +    	"debug":sprintf("%s", [port]),
```suggestion
```

2022-04-12 00:10 UTC, joaorufi requested changes

2022-04-12 00:10 UTC, joaorufi commented on assets/queries/dockerCompose/container_traffic_not_bound_to_host_interface/test/positive_expected_result.json
> +    "filename": "positive1.yaml"
```suggestion
    "fileName": "positive1.yaml"
```

2022-04-12 00:10 UTC, joaorufi commented on assets/queries/dockerCompose/container_traffic_not_bound_to_host_interface/test/positive_expected_result.json
> +    "filename": "positive2.yaml"
```suggestion
    "fileName": "positive2.yaml"
```

2022-04-12 00:10 UTC, joaorufi commented on assets/queries/dockerCompose/container_traffic_not_bound_to_host_interface/test/positive_expected_result.json
> +    "filename": "positive3.yaml"
```suggestion
    "fileName": "positive3.yaml"
```

2022-04-12 08:59 UTC, merged