feat(query): Added Insecure Port Not Properly Set for Kubernetes
Checkmarx/kics pull request #5149
Opened 2022-04-06 11:15 UTC by cxMiguelSilva

**Proposed Changes**
- Added Insecure Port Not Properly Set for Kubernetes

I submit this contribution under the Apache-2.0 license.

2022-04-11 10:00 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-04-12 00:16 UTC, joaorufi requested changes

2022-04-12 00:16 UTC, joaorufi commented on assets/queries/k8s/insecure_port_not_properly_set/test/positive_expected_result.json
> +    "filename": "positive1.yaml"
```suggestion
    "fileName": "positive1.yaml"
```

2022-04-12 00:16 UTC, joaorufi commented on assets/queries/k8s/insecure_port_not_properly_set/test/positive_expected_result.json
> +    "filename": "positive2.yaml"
```suggestion
    "fileName": "positive2.yaml"
```

2022-04-12 00:45 UTC, joaorufi approved these changes

2022-04-12 00:46 UTC, merged