Feat(Query): Volume Mounted In Multiple Containers for docker compose
Checkmarx/kics pull request #5152
Opened 2022-04-06 15:25 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: Volume Mounted In Multiple Containers for docker compose

I submit this contribution under the Apache-2.0 license.

2022-04-11 10:55 UTC, rafaela-soares requested changes

2022-04-11 10:55 UTC, rafaela-soares commented on assets/queries/dockerCompose/volume_mounted_in_multiple_containers/metadata.json
> +  "descriptionText": "Volume is mounted in multiple containers. Volume mounts should not be shared.",
```suggestion
  "descriptionText": "Volume mounts should not be shared, which means that 'propagation' should not be set to 'shared', 'rshared', 'slave', or 'rslave'",
```

2022-04-11 10:55 UTC, rafaela-soares commented on assets/queries/dockerCompose/volume_mounted_in_multiple_containers/query.rego
> +		"searchLine": common_lib.build_search_line(["services", name, "volumes", "bind", "propagation"], []),
```suggestion
        "searchLine": common_lib.build_search_line(["services", name, "volumes", v, "bind", "propagation"], []),
```

2022-04-11 10:55 UTC, rafaela-soares commented on assets/queries/dockerCompose/volume_mounted_in_multiple_containers/query.rego
> +    	"debug": sprintf("%s",[propagation]),
```suggestion
```

2022-04-11 14:20 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-04-12 00:19 UTC, joaorufi requested changes

2022-04-12 00:19 UTC, joaorufi commented on assets/queries/dockerCompose/volume_mounted_in_multiple_containers/test/positive_expected_result.json
> +      "filename": "positive1.yaml"
```suggestion
      "fileName": "positive1.yaml"
```

2022-04-12 00:19 UTC, joaorufi commented on assets/queries/dockerCompose/volume_mounted_in_multiple_containers/test/positive_expected_result.json
> +      "filename": "positive2.yaml"
```suggestion
      "fileName": "positive2.yaml"
```

2022-04-12 00:19 UTC, joaorufi commented on assets/queries/dockerCompose/volume_mounted_in_multiple_containers/test/positive_expected_result.json
> +      "filename": "positive3.yaml"
```suggestion
      "fileName": "positive3.yaml"
```

2022-04-12 00:19 UTC, joaorufi commented on assets/queries/dockerCompose/volume_mounted_in_multiple_containers/test/positive_expected_result.json
> +      "filename": "positive4.yaml"
```suggestion
      "fileName": "positive4.yaml"
```

2022-04-12 00:47 UTC, joaorufi approved these changes

2022-04-12 09:01 UTC, merged