Feat(Query): Default Seccomp Profile Disabled for docker compose
Checkmarx/kics pull request #5154
Opened 2022-04-07 10:03 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: Seccomp Disabled for docker compose

I submit this contribution under the Apache-2.0 license.

2022-04-11 11:04 UTC, rafaela-soares requested changes

2022-04-11 11:04 UTC, rafaela-soares commented on assets/queries/dockerCompose/seccomp_disabled/metadata.json
> +  "queryName": "Seccomp Disabled",
```suggestion
  "queryName": "Default Seccomp Profile Disabled",
```

Please, update the query folder name

2022-04-11 11:04 UTC, rafaela-soares commented on assets/queries/dockerCompose/seccomp_disabled/query.rego
> +		"searchLine": common_lib.build_search_line(["services", name, "security_opt"], []),
```suggestion
        "searchLine": common_lib.build_search_line(["services", name, "security_opt", a], []),
```

2022-04-11 15:17 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-04-12 00:19 UTC, joaorufi requested changes

2022-04-12 00:19 UTC, joaorufi commented on assets/queries/dockerCompose/default_seccomp_profile_disabled/test/positive_expected_result.json
> +      "filename": "positive1.yaml"
```suggestion
      "fileName": "positive1.yaml"
```

2022-04-12 00:19 UTC, joaorufi commented on assets/queries/dockerCompose/default_seccomp_profile_disabled/test/positive_expected_result.json
> +      "filename": "positive2.yaml"
```suggestion
      "fileName": "positive2.yaml"
```

2022-04-12 00:48 UTC, joaorufi requested changes

2022-04-12 00:48 UTC, joaorufi commented on assets/queries/dockerCompose/default_seccomp_profile_disabled/query.rego
> +		"keyExpectedValue": "Seccomp default profile is not being disabled.",
```suggestion
		"keyExpectedValue": "Seccomp default profile to not be disabled.",
```

2022-04-12 13:51 UTC, merged