Feat(Query): No New Privileges Not Set for docker compose
Checkmarx/kics pull request #5159
Opened 2022-04-07 14:37 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: No New Privileges Not Set for docker compose

I submit this contribution under the Apache-2.0 license.

2022-04-11 11:28 UTC, rafaela-soares requested changes

2022-04-11 11:28 UTC, rafaela-soares commented on assets/queries/dockerCompose/no_new_privileges_not_set/query.rego
> +    sec_opt[s] != "no-new-privileges"
The policy is verifying each index of security_opt (and should not). I think we should look if there is no security_opt set to "no-new-privileges:true". 

```suggestion
    not no_new_privileges(sec_opt)
```

```
no_new_privileges(sec_opt) {
    sec_opt[_] == "no-new-privileges:true"
}
```

2022-04-11 15:18 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-04-12 00:22 UTC, joaorufi requested changes

2022-04-12 00:22 UTC, joaorufi commented on assets/queries/dockerCompose/no_new_privileges_not_set/test/positive_expected_result.json
> +      "filename": "positive1.yaml"
```suggestion
      "fileName": "positive1.yaml"
```

2022-04-12 00:22 UTC, joaorufi commented on assets/queries/dockerCompose/no_new_privileges_not_set/test/positive_expected_result.json
> +      "filename": "positive2.yaml"
```suggestion
      "fileName": "positive2.yaml"
```

2022-04-12 00:50 UTC, joaorufi approved these changes

2022-04-12 09:03 UTC, merged