Feat(Query): Healthcheck Not Set for docker compose
Checkmarx/kics pull request #5160
Opened 2022-04-07 16:12 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: Healthcheck Not Set for docker compose

I submit this contribution under the Apache-2.0 license.

2022-04-11 11:37 UTC, rafaela-soares requested changes

2022-04-11 11:37 UTC, rafaela-soares commented on assets/queries/dockerCompose/healthcheck_not_set/query.rego
> +}
Not sure if we need this policy

2022-04-11 15:30 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-04-12 00:23 UTC, joaorufi requested changes

2022-04-12 00:23 UTC, joaorufi commented on assets/queries/dockerCompose/healthcheck_not_set/test/positive_expected_result.json
> +      "filename": "positive1.yaml"
```suggestion
      "fileName": "positive1.yaml"
```

2022-04-12 00:23 UTC, joaorufi commented on assets/queries/dockerCompose/healthcheck_not_set/test/positive_expected_result.json
> +      "filename": "positive2.yaml"
```suggestion
      "fileName": "positive2.yaml"
```

2022-04-12 00:23 UTC, joaorufi commented on assets/queries/dockerCompose/healthcheck_not_set/test/positive_expected_result.json
> +      "filename": "positive3.yaml"
```suggestion
      "fileName": "positive3.yaml"
```

2022-04-12 00:51 UTC, joaorufi approved these changes

2022-04-12 09:06 UTC, merged