Feat(Query): Networks Not Set for docker compose
Checkmarx/kics pull request #5164
Opened 2022-04-08 10:43 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: Networks Not Set for docker compose

I submit this contribution under the Apache-2.0 license.

2022-04-11 12:59 UTC, rafaela-soares requested changes

2022-04-11 12:59 UTC, rafaela-soares commented on assets/queries/dockerCompose/networks_not_set/metadata.json
> +  "category": "Resource Management",
```suggestion
  "category": "Networking and Firewall",
```

2022-04-11 15:19 UTC, rafaela-soares submitted a review, later dismissed
LGTM 🚀

2022-04-12 00:26 UTC, joaorufi requested changes

2022-04-12 00:26 UTC, joaorufi commented on assets/queries/dockerCompose/networks_not_set/query.rego
> +		"issueType": "IncorrectValue",
```suggestion
		"issueType": "MissingAttribute",
```

2022-04-12 00:26 UTC, joaorufi commented on assets/queries/dockerCompose/networks_not_set/test/positive_expected_result.json
> +      "filename": "positive1.yaml"
```suggestion
      "fileName": "positive1.yaml"
```

2022-04-12 00:26 UTC, joaorufi commented on assets/queries/dockerCompose/networks_not_set/test/positive_expected_result.json
> +      "filename": "positive2.yaml"
```suggestion
      "fileName": "positive2.yaml"
```

2022-04-12 13:53 UTC, merged

2023-11-27 10:35 UTC, pgassmann commented
@cxAndreFelicidade I don't understand the need for this check. Docker compose set up a separate network for each compose project, used by default if no specific network is specified for a service. It won't use the global default network on the host.

> By default Compose sets up a single [network](https://docs.docker.com/engine/reference/commandline/network_create/) for your app. Each container for a service joins the default network and is both reachable by other containers on that network, and discoverable by them at a hostname identical to the container name.

https://docs.docker.com/compose/networking/