Feat(Query): Docker Socket Mounted In Container for docker compose
Checkmarx/kics pull request #5166
Opened 2022-04-08 13:50 UTC by cxAndreFelicidade

**Proposed Changes**
- Docker Socket Mounted In Container for docker compose

I submit this contribution under the Apache-2.0 license.

2022-04-11 13:04 UTC, rafaela-soares submitted a review, later dismissed
LGTM 🚀

2022-04-12 00:30 UTC, joaorufi requested changes

2022-04-12 00:30 UTC, joaorufi commented on assets/queries/dockerCompose/docker_socket_mounted_in_container/query.rego
> +		"keyExpectedValue": "There is no docker socket named 'docker.sock' mounted in a volume",
```suggestion
		"keyExpectedValue": "To not have docker socket named 'docker.sock' mounted in a volume",
```

2022-04-12 00:30 UTC, joaorufi commented on assets/queries/dockerCompose/docker_socket_mounted_in_container/test/positive_expected_result.json
> +      "filename": "positive1.yaml"
```suggestion
      "fileName": "positive1.yaml"
```

2022-04-12 13:53 UTC, joaorufi approved these changes

2022-04-12 13:54 UTC, merged