update(query): Apt Get Install Pin Version Not Defined
Checkmarx/kics pull request #5176
Opened 2022-04-11 15:05 UTC by cxMiguelSilva

Closes #5117

**Proposed Changes**
- Update query Apt Get Install Pin Version Not Defined
- Added support for docker ; command separation in the query mentioned above
- Update dockerfile.rego functions to add support for docker ; command separation

I submit this contribution under the Apache-2.0 license.

2022-04-19 09:50 UTC, rafaela-soares requested changes

2022-04-19 09:50 UTC, rafaela-soares commented on assets/queries/dockerfile/apt_get_install_lists_were_not_deleted/query.rego
> +
```suggestion
options := {"&& ", "; "}

hasClean(resourceValue, aptGet) {
	res:= replace(resourceValue, "\t", "")
	listCommands := split(res, options[_])

	startswith(listCommands[install], aptGet)
	startswith(listCommands[clean], "apt-get clean")

	install < clean
} else {
	res:= replace(resourceValue, "\t", "")
	listCommands := split(res, options[_])

	startswith(listCommands[install], aptGet)
	startswith(listCommands[remove], "rm -rf")

	install < remove
}
```

2022-04-19 09:50 UTC, rafaela-soares commented on assets/queries/dockerfile/apt_get_install_lists_were_not_deleted/query.rego
> +
```suggestion
options := {"&& ", "; "}

hasClean(resourceValue, aptGet) {
	res:= replace(resourceValue, "\t", "")
	listCommands := split(res, options[_])

	startswith(listCommands[install], aptGet)
	startswith(listCommands[clean], "apt-get clean")

	install < clean
} else {
	res:= replace(resourceValue, "\t", "")
	listCommands := split(res, options[_])

	startswith(listCommands[install], aptGet)
	startswith(listCommands[remove], "rm -rf")

	install < remove
}
```

2022-04-19 09:52 UTC, rafaela-soares requested changes

2022-04-19 09:52 UTC, rafaela-soares commented on assets/queries/dockerfile/apt_get_install_pin_version_not_defined/test/positive2.dockerfile
> +FROM busybox4
Can you add a negative sample with `;` for `apt_get_install_pin_version_not_defined`, please?

2022-04-19 17:48 UTC, joaorufi approved these changes

2022-04-21 13:14 UTC, joaorufi submitted a review, later dismissed

2022-04-26 23:05 UTC, joaorufi approved these changes

2022-04-28 14:54 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-04-28 14:55 UTC, merged