Update/sns topic is publicly accessible for subscription
Checkmarx/kics pull request #5210
Opened 2022-04-19 09:46 UTC by cxMiguelSilva

Closes #5191, #5190, #5189

**Proposed Changes**
- Delete duplicated queries Open Access To Resources Through Api for CloudFormation and Terraform AWS
- Remove redundant check for SSEType in DynamoDB With Aws Owned CMK for CloudFormation
- Add support to AWS::SNS::Topic subscription reference in AWS::SNS::Subscription in SNS Topic is Publicly Accessible For Subscription for CloudFormation

I submit this contribution under the Apache-2.0 license.

2022-04-19 10:19 UTC, rafaela-soares requested changes

2022-04-19 10:19 UTC, rafaela-soares commented on assets/queries/cloudFormation/aws/sns_topic_is_publicly_accessible_for_subscription/query.rego
> +}
```suggestion
has_aws_SNS_Sub(input_document, name_SNS){
	resourceSNS := input_document.document[i].Resources
	resourceSNS[j].Type == "AWS::SNS::Subscription"
	topic := get_topic(resourceSNS[j].Properties.TopicArn) 
	topic == name_SNS
}

get_topic(topicArn) = topic {
   topic := topicArn.Ref
} else = topic {
   topic := topicArn
}
```

Please, add a YAML sample. The PARSER behaviour is different. Take a look:

```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  CarSalesTopic:
    Type: 'AWS::SNS::Topic'
  ERPSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref CarSalesTopic
      Endpoint: !GetAtt 
        - ERPIntegrationQueue
        - Arn
      Protocol: sqs
      RawMessageDelivery: 'true'
```

```
{
	"document": [
		{
			"AWSTemplateFormatVersion": "2010-09-09",
			"Resources": {
				"CarSalesTopic": {
					"Type": "AWS::SNS::Topic"
				},
				"ERPSubscription": {
					"Properties": {
						"Endpoint": [
							"ERPIntegrationQueue",
							"Arn"
						],
						"Protocol": "sqs",
						"RawMessageDelivery": "true",
						"TopicArn": "CarSalesTopic"
					},
					"Type": "AWS::SNS::Subscription"
				}
			},
			"id": "f819a69f-41fa-4773-a59e-55ee467774e9",
			"file": "C:\\CxCode\\CxKICS\\kics\\assets\\queries\\cloudFormation\\aws\\sns_topic_is_publicly_accessible_for_subscription\\test\\positive1.yaml"
		}
	]
}
```

2022-04-19 17:57 UTC, joaorufi approved these changes

2022-04-20 08:08 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-04-20 08:14 UTC, merged