fix(query): ALB Listening on HTTP for AWS CloudFormation
Checkmarx/kics pull request #5212
Opened 2022-04-19 16:14 UTC by cxMiguelSilva

**Proposed Changes**
- Fix incorrect line in result exposure
- Add positive sample

I submit this contribution under the Apache-2.0 license.

2022-04-19 18:02 UTC, joaorufi submitted a review, later dismissed

2022-04-22 14:29 UTC, rafaela-soares requested changes

2022-04-22 14:29 UTC, rafaela-soares commented on assets/queries/cloudFormation/aws/alb_listening_on_http/query.rego
> +		"searchLine": common_lib.build_search_line(["Resources", name, "Properties","Listeners","Protocol"], []),
```suggestion
"searchLine": common_lib.build_search_line(["Resources", name, "Properties","Listeners", l, "Protocol"], []),
```

Also change line 9, please:
`resource.Properties.Listeners[l].Protocol == "HTTP"`

2022-04-26 09:02 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-04-26 09:21 UTC, fjsnogueira commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx AST – Scan Summary & Details** – [2ce51a6c\-4e33\-4cc2\-aa8a\-38389f442a61](https://eu.ast.checkmarx.net/projects/0244d5f3-72f2-4c91-8775-654a746fd66f/scans?id=2ce51a6c-4e33-4cc2-aa8a-38389f442a61&branch=update%2Falb_listening_on_http)
### New Issues
Severity|Issue|File / Package|Scan Engine
---|---|---|---
HIGH|ALB Listening on HTTP|/assets/queries/cloudFormation/aws/alb\_listening\_on\_http/test/positive3\.yaml: [8](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/alb_listening_on_http/test/positive3.yaml#L8)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
HIGH|DynamoDB With Aws Owned CMK|/assets/queries/cloudFormation/aws/dynamodb\_with\_aws\_owned\_cmk/test/positive2\.yaml: [4](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/dynamodb_with_aws_owned_cmk/test/positive2.yaml#L4)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
HIGH|DynamoDB With Aws Owned CMK|/assets/queries/cloudFormation/aws/dynamodb\_with\_aws\_owned\_cmk/test/positive6\.json: [5](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/dynamodb_with_aws_owned_cmk/test/positive6.json#L5)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Endpoint Config is Not Private|/assets/queries/cloudFormation/aws/api\_gateway\_without\_content\_encoding/test/positive3\.yaml: [5](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/api_gateway_without_content_encoding/test/positive3.yaml#L5)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Endpoint Config is Not Private|/assets/queries/cloudFormation/aws/api\_gateway\_without\_content\_encoding/test/positive6\.json: [5](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/api_gateway_without_content_encoding/test/positive6.json#L5)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Endpoint Config is Not Private|/assets/queries/cloudFormation/aws/api\_gateway\_without\_content\_encoding/test/negative2\.json: [5](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/api_gateway_without_content_encoding/test/negative2.json#L5)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Endpoint Config is Not Private|/assets/queries/cloudFormation/aws/api\_gateway\_without\_content\_encoding/test/positive5\.json: [5](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/api_gateway_without_content_encoding/test/positive5.json#L5)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Endpoint Config is Not Private|/assets/queries/cloudFormation/aws/api\_gateway\_without\_content\_encoding/test/positive1\.yaml: [5](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/api_gateway_without_content_encoding/test/positive1.yaml#L5)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Endpoint Config is Not Private|/assets/queries/terraform/aws/api\_gateway\_without\_content\_encoding/test/positive\.tf: [4](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/terraform/aws/api_gateway_without_content_encoding/test/positive.tf#L4), [13](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/terraform/aws/api_gateway_without_content_encoding/test/positive.tf#L13), [24](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/terraform/aws/api_gateway_without_content_encoding/test/positive.tf#L24)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Endpoint Config is Not Private|/assets/queries/cloudFormation/aws/api\_gateway\_without\_content\_encoding/test/negative1\.yaml: [5](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/api_gateway_without_content_encoding/test/negative1.yaml#L5)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Endpoint Config is Not Private|/assets/queries/cloudFormation/aws/api\_gateway\_without\_content\_encoding/test/positive4\.json: [5](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/api_gateway_without_content_encoding/test/positive4.json#L5)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Endpoint Config is Not Private|/assets/queries/terraform/aws/api\_gateway\_without\_content\_encoding/test/negative\.tf: [4](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/terraform/aws/api_gateway_without_content_encoding/test/negative.tf#L4)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Endpoint Config is Not Private|/assets/queries/cloudFormation/aws/api\_gateway\_without\_content\_encoding/test/positive2\.yaml: [5](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/api_gateway_without_content_encoding/test/positive2.yaml#L5)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Method Does Not Contains An API Key|/assets/queries/cloudFormation/aws/open\_access\_to\_resources\_through\_api/test/positive2\.json: [5](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/open_access_to_resources_through_api/test/positive2.json#L5)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Method Does Not Contains An API Key|/assets/queries/cloudFormation/aws/open\_access\_to\_resources\_through\_api/test/negative2\.json: [5](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/open_access_to_resources_through_api/test/negative2.json#L5)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Method Does Not Contains An API Key|/assets/queries/terraform/aws/open\_access\_to\_resources\_through\_api/test/negative\.tf: [12](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/terraform/aws/open_access_to_resources_through_api/test/negative.tf#L12)|[CxKICS](https://eu.ast.checkmarx.net/results/2ce51a6c-4e33-4cc2-aa8a-38389f442a61/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)
MEDIUM|API Gateway Method Does Not Contains An API Key|/assets/queries/cloudFormation/aws/open\_access\_to\_resources\_through\_api/test/positive1\.yaml: [4](https://github.com/Checkmarx/kics/blob/update/alb_listening_on_http//assets/queries/cloudFormation/aws/open_access_to_resources_through_api/test/positive1.yaml#L4)| [...]

2022-04-26 09:59 UTC, merged