refactor(analyzer): analyzer usage when types flag is passed
Checkmarx/kics pull request #5222
Opened 2022-04-20 11:56 UTC by rafaela-soares

**Proposed Changes**
- Refactored analyzer: analyzer usage when types flag is passed
- Updated documentation related to release
- Updated documentation related to searchKey

I submit this contribution under the Apache-2.0 license.

2022-04-21 13:36 UTC, nunoocx approved these changes
LGTM

2022-04-21 14:46 UTC, joaorufi requested changes

2022-04-21 14:46 UTC, joaorufi commented on pkg/analyzer/analyzer.go
> +		if (typesFlag[0] != "" && utils.Contains(terraform, typesFlag)) || typesFlag[0] == "" {
```suggestion
		if typesFlag[0] == "" || utils.Contains(terraform, typesFlag) {
```

2022-04-21 14:46 UTC, joaorufi commented on pkg/analyzer/analyzer.go
> +		if (typesFlag[0] != "" && utils.Contains(grpc, typesFlag)) || typesFlag[0] == "" {
```suggestion
		if typesFlag[0] == "" || utils.Contains(grpc, typesFlag) {
```

2022-04-21 14:46 UTC, joaorufi commented on pkg/analyzer/analyzer.go
> +		if (typesFlag[0] != "" && utils.Contains(returnType, typesFlag)) || typesFlag[0] == "" {
```suggestion
		if typesFlag[0] == "" || utils.Contains(returnType, typesFlag) {
```

2022-04-22 15:26 UTC, joaorufi approved these changes

2022-04-26 08:05 UTC, merged