feat(query): Added NAS File System Without KMS for Alicloud
Checkmarx/kics pull request #5248
Opened 2022-04-26 10:04 UTC by cxMiguelSilva

**Proposed Changes**
- NAS File System Without KMS for Alicloud

I submit this contribution under the Apache-2.0 license.

2022-04-26 11:46 UTC, fjsnogueira commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx AST – Scan Summary & Details** – [9e5a6764\-72c6\-4b2a\-b149\-31efd4f1cbc4](https://eu.ast.checkmarx.net/projects/0244d5f3-72f2-4c91-8775-654a746fd66f/scans?id=9e5a6764-72c6-4b2a-b149-31efd4f1cbc4&branch=query%2Fnas_file_system_without_kms)

### Fixed Issues
Severity|Issue|File / Package|Scan Engine
---|---|---|---
HIGH|ALB Listening on HTTP|/assets/queries/cloudFormation/aws/alb\_listening\_on\_http/test/positive3\.yaml: [8](https://github.com/Checkmarx/kics/blob/query/nas_file_system_without_kms//assets/queries/cloudFormation/aws/alb_listening_on_http/test/positive3.yaml#L8)|[CxKICS](https://eu.ast.checkmarx.net/results/9e5a6764-72c6-4b2a-b149-31efd4f1cbc4/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)

2022-04-26 14:43 UTC, rafaela-soares requested changes

2022-04-26 14:43 UTC, rafaela-soares commented on assets/queries/terraform/alicloud/nas_file_system_without_kms/query.rego
> +}
I think we should rethink this query approach.

When `encrypt_type` is set to `2`, `kms_key_id `is required. So, the present policy can be considered as unnecessary.

I suggest two policies. One that verifies if `encrypt_type` is not set, which means that the resource is not encrypted. And another policy that verifies if `encrypt_type` is not set to `2`.

Please:
- Rethink the approach
- Include `searchLine`
- Improve query description to point that `encrypt_type` should be set to `2`

2022-04-26 17:10 UTC, fjsnogueira commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx AST – Scan Summary & Details** – [c64a066d\-323f\-4dcc\-93f4\-abec92af5846](https://eu.ast.checkmarx.net/projects/0244d5f3-72f2-4c91-8775-654a746fd66f/scans?id=c64a066d-323f-4dcc-93f4-abec92af5846&branch=query%2Fnas_file_system_without_kms)

### Fixed Issues
Severity|Issue|File / Package|Scan Engine
---|---|---|---
HIGH|ALB Listening on HTTP|/assets/queries/cloudFormation/aws/alb\_listening\_on\_http/test/positive3\.yaml: [8](https://github.com/Checkmarx/kics/blob/query/nas_file_system_without_kms//assets/queries/cloudFormation/aws/alb_listening_on_http/test/positive3.yaml#L8)|[CxKICS](https://eu.ast.checkmarx.net/results/c64a066d-323f-4dcc-93f4-abec92af5846/0244d5f3-72f2-4c91-8775-654a746fd66f/kics)

2022-04-26 17:30 UTC, rafaela-soares requested changes

2022-04-27 18:09 UTC, joaorufi approved these changes

2022-04-27 18:52 UTC, merged