feat(query): Added VPC Flow Logs Disabled for Terraform Alicloud
Checkmarx/kics pull request #5253
Opened 2022-04-26 13:35 UTC by cxMiguelSilva

**Proposed Changes**
- VPC Flow Logs Disabled for

I submit this contribution under the Apache-2.0 license.

2022-04-26 15:02 UTC, rafaela-soares requested changes

2022-04-26 15:02 UTC, rafaela-soares commented on assets/queries/terraform/alicloud/vpc_flow_logs_disabled/query.rego
> +}
We should check if the `resource_type` is not set to `VPC`

2022-04-26 15:02 UTC, rafaela-soares commented on assets/queries/terraform/alicloud/vpc_flow_logs_disabled/query.rego
> +}
This policy is unnecessary. `resource_id` is required.
```suggestion
```

2022-04-26 17:33 UTC, rafaela-soares requested changes

2022-04-26 17:33 UTC, rafaela-soares commented on assets/queries/terraform/alicloud/vpc_flow_logs_disabled/query.rego
> +		"keyActualValue": sprintf("alicloud_vpc[%s] is not the same as Flow Logs VPC resource id", [name_vpc]),
```suggestion
		"keyExpectedValue": sprintf("alicloud_vpc[%s] is not associated with an 'alicloud_vpc_flow_log'", [name_vpc]),
		"keyActualValue": sprintf("alicloud_vpc[%s] is associated with an 'alicloud_vpc_flow_log'", [name_vpc]),
```

2022-04-27 18:11 UTC, joaorufi approved these changes

2022-04-27 18:53 UTC, merged