Feat(Query): Log Retention Is Not Greater Than 90 Days for Alicloud Terraform
Checkmarx/kics pull request #5254
Opened 2022-04-26 16:13 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: Log Retention Is Not Greater Than 90 Days for Alicloud Terraform

I submit this contribution under the Apache-2.0 license.

2022-04-26 16:24 UTC, rafaela-soares commented on assets/queries/terraform/alicloud/log_retention_is_not_greater_than_90_days/metadata.json
> +  "descriptionText": "OSS Bucket should have logging enabled for longer than 90 days, for better visibility of resources and objects.",
```suggestion
  "descriptionText": "OSS Log Store should have logging enabled for longer than 90 days, for better visibility of resources and objects.",
```

2022-04-26 16:25 UTC, rafaela-soares commented on assets/queries/terraform/alicloud/log_retention_is_not_greater_than_90_days/query.rego
> +        "searchLine": common_lib.build_search_line(["resource", "alicloud_disk", name, "encrypted"], []),
```suggestion
        "searchLine": common_lib.build_search_line(["resource", "alicloud_log_store", name, "encrypted"], []),
```

2022-04-26 16:27 UTC, rafaela-soares requested changes

2022-04-26 16:41 UTC, fjsnogueira commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx AST – Scan Summary & Details** – [5e036028\-58b6\-4dda\-8428\-77fc0f920e90](https://eu.ast.checkmarx.net/projects/0244d5f3-72f2-4c91-8775-654a746fd66f/scans?id=5e036028-58b6-4dda-8428-77fc0f920e90&branch=log_retention_is_not_greater_than_90_days)
### No New Or Fixed Issues Found

2022-04-27 12:32 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-04-27 16:49 UTC, rafaela-soares requested changes

2022-04-27 16:49 UTC, rafaela-soares commented on assets/queries/terraform/alicloud/ros_stack_without_template/metadata.json
> +
Please, delete this query since PR #5262 covers it.

2022-04-28 11:28 UTC, rafaela-soares approved these changes

2022-04-28 14:26 UTC, joaorufi approved these changes

2022-04-28 14:29 UTC, merged