feat(query): Added No ROS Stack Policy for Terraform Alicloud
Checkmarx/kics pull request #5259
Opened 2022-04-27 13:16 UTC by cxMiguelSilva

**Proposed Changes**
- No ROS Stack Policy

I submit this contribution under the Apache-2.0 license.

2022-04-27 16:48 UTC, rafaela-soares submitted a review, later dismissed
LGTM 🚀

2022-04-27 19:31 UTC, joaorufi requested changes

2022-04-27 19:31 UTC, joaorufi commented on assets/queries/terraform/alicloud/no_ros_stack_policy/query.rego
> +		"keyExpectedValue": "The stack has the attribute 'stack_policy_body' or 'stack_policy_url' defined",
```suggestion
		"keyExpectedValue": "The stack should have the attribute 'stack_policy_body' or 'stack_policy_url' defined",
```

2022-04-27 19:31 UTC, joaorufi commented on assets/queries/terraform/alicloud/no_ros_stack_policy/query.rego
> +		"keyExpectedValue": "The stack has the attribute 'stack_policy_during_update_body' or 'stack_policy_during_update_url' defined",
```suggestion
		"keyExpectedValue": "The stack should have the attribute 'stack_policy_during_update_body' or 'stack_policy_during_update_url' defined",
```

2022-04-28 14:45 UTC, joaorufi approved these changes

2022-04-28 14:47 UTC, merged