Feat(Query): ROS Stack Without Template for Alicloud Terraform
Checkmarx/kics pull request #5262
Opened 2022-04-27 15:06 UTC by cxAndreFelicidade

**Proposed Changes**
- Query: ROS Stack Without Template for Alicloud Terraform

I submit this contribution under the Apache-2.0 license.

2022-04-27 16:29 UTC, rafaela-soares requested changes

2022-04-27 16:29 UTC, rafaela-soares commented on assets/queries/terraform/alicloud/ros_stack_without_template/query.rego
> +	not resource.template_url
```suggestion
    not common_lib.valid_key(resource, "template_body")
    not common_lib.valid_key(resource, "template_url")
```

Do not forget to import the common lib, please: `import data.generic.common as common_lib`

Please, also update in `kics\assets\queries\terraform\aws\stack_without_template\query.rego`

2022-04-27 16:29 UTC, rafaela-soares commented on assets/queries/terraform/alicloud/ros_stack_without_template/query.rego
> +	}
Add `searchLine`, please

2022-04-27 16:29 UTC, rafaela-soares commented on assets/queries/terraform/alicloud/ros_stack_without_template/metadata.json
> +  "queryName": "Ros Stack Without Template",
```suggestion
  "queryName": "ROS Stack Without Template",
```

(for standard propuses)

2022-04-27 19:33 UTC, joaorufi requested changes

2022-04-27 19:33 UTC, joaorufi commented on assets/queries/terraform/alicloud/ros_stack_without_template/query.rego
> +		"keyExpectedValue": "Attribute 'template_body' or Attribute 'template_url' is set",
```suggestion
		"keyExpectedValue": "Attribute 'template_body' or Attribute 'template_url' to be set",
```

2022-04-28 14:42 UTC, rafaela-soares approved these changes
LGMT 🚀

2022-04-28 14:48 UTC, merged