feat(query): Added SLB Policy With Insecure Tls Version In Use for Terraform Alicloud
Checkmarx/kics pull request #5271
Opened 2022-04-28 09:38 UTC by cxMiguelSilva

**Proposed Changes**
- SLB Policy With Insecure Tls Version In Use

I submit this contribution under the Apache-2.0 license.

2022-04-28 11:03 UTC, rafaela-soares requested changes

2022-04-28 11:03 UTC, rafaela-soares commented on assets/queries/terraform/alicloud/slb_policy_with_insecure_tls_version_in_use/metadata.json
> +  "descriptionText": "SLB Policy should not support insecure versions of Tls protocol",
```suggestion
  "queryName": "SLB Policy With Insecure TLS Version In Use",
  "severity": "MEDIUM",
  "category": "Encryption",
  "descriptionText": "SLB Policy should not support insecure versions of TLS protocol",
```

for standard purposes

2022-04-28 14:10 UTC, joaorufi approved these changes

2022-04-28 14:10 UTC, joaorufi commented on assets/queries/terraform/alicloud/slb_policy_with_insecure_tls_version_in_use/query.rego
> +		"keyExpectedValue": sprintf("alicloud_slb_tls_cipher_policy[%s].tls_versions uses secure TLS versions", [name]),
```suggestion
		"keyExpectedValue": sprintf("alicloud_slb_tls_cipher_policy[%s].tls_versions to use secure TLS versions", [name]),
```

2022-04-28 14:10 UTC, joaorufi commented on assets/queries/terraform/alicloud/slb_policy_with_insecure_tls_version_in_use/test/positive_expected_result.json
> +]
Could you add `fileName` ?

2022-04-28 14:11 UTC, joaorufi requested changes

2022-04-28 14:11 UTC, joaorufi commented on assets/queries/terraform/alicloud/slb_policy_with_insecure_tls_version_in_use/query.rego
> +		"keyExpectedValue": sprintf("alicloud_slb_tls_cipher_policy[%s].tls_versions uses secure TLS versions", [name]),
```suggestion
		"keyExpectedValue": sprintf("alicloud_slb_tls_cipher_policy[%s].tls_versions to use secure TLS versions", [name]),
```

2022-04-28 14:11 UTC, joaorufi commented on assets/queries/terraform/alicloud/slb_policy_with_insecure_tls_version_in_use/test/positive_expected_result.json
> +]
Could you add `fileName` ?

2022-04-28 14:55 UTC, joaorufi approved these changes

2022-04-29 14:11 UTC, rafaela-soares approved these changes

2022-04-29 14:11 UTC, merged