update(query): Update category and severities according with issue 5220
Checkmarx/kics pull request #5292
Opened 2022-05-02 14:21 UTC by cxMiguelSilva

Closes #5220 

**Proposed Changes**
- Update category and severities
- Update SNS Topic is Publicly Accessible For Subscription implementation for cloudFormation, ansible and terraform aws
- Update CloudTrail Log Files Not Encrypted name

I submit this contribution under the Apache-2.0 license.

2022-05-02 15:14 UTC, rafaela-soares requested changes

2022-05-02 15:14 UTC, rafaela-soares commented on assets/queries/terraform/aws/iam_password_without_uppercase_letter/metadata.json
> +  "category": "Best Practices",
What about `kics\assets\queries\terraform\alicloud\ram_password_security_policy_not_require_at_least_one_uppercase_character` ?

2022-05-02 15:14 UTC, rafaela-soares commented on assets/queries/ansible/aws/sns_topic_is_publicly_accessible/query.rego
> +	statement := policies.Statement[i]
```suggestion
    st := common_lib.get_statement(common_lib.get_policy(policy))
	statement := st[_]
```

2022-05-02 15:14 UTC, rafaela-soares commented on assets/queries/cloudFormation/aws/sns_topic_is_publicly_accessible/query.rego
> +		"searchLine": common_lib.build_search_line(["Resource", name, "Properties", "PolicyDocument","Statement"], []),
```suggestion
                "searchLine": common_lib.build_search_line(["Resource", name, "Properties", "PolicyDocument"], []),
```

2022-05-02 15:14 UTC, rafaela-soares commented on assets/queries/cloudFormation/aws/sns_topic_is_publicly_accessible/query.rego
> +		"searchKey": sprintf("Resources.%s.Properties.PolicyDocument.Statement", [name]),
```suggestion
                "searchKey": sprintf("Resources.%s.Properties.PolicyDocument", [name]),
```

2022-05-03 09:52 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-05-03 15:40 UTC, joaorufi approved these changes

2022-05-04 08:39 UTC, merged