update(query):  StatefulSet Without Service Name for Kubernetes
Checkmarx/kics pull request #5303
Opened 2022-05-04 10:06 UTC by cxMiguelSilva

**Proposed Changes**
- Modify check for matched labels between Headless service and StatefulSet

I submit this contribution under the Apache-2.0 license.

2022-05-04 12:58 UTC, kaplanlior commented
This PR fixes a problem reported at https://github.com/Checkmarx/kics/discussions/5137

2022-05-05 08:36 UTC, rafaela-soares requested changes

2022-05-05 08:36 UTC, rafaela-soares commented on assets/queries/k8s/statefulset_without_service_name/query.rego
> +package Cx
Please, also update the query `kics\assets\queries\terraform\kubernetes\statefulset_without_service_name`

If possible, also improve the query description, please

2022-05-05 08:36 UTC, rafaela-soares commented on assets/queries/k8s/statefulset_without_service_name/query.rego
>  }
```suggestion
match_labels(serviceLabels, statefulsetLabels) {
    count({x | label := serviceLabels[x]; label == statefulsetLabels[_]}) == count(serviceLabels)
}
```

2022-05-05 08:36 UTC, rafaela-soares commented on assets/queries/k8s/statefulset_without_service_name/query.rego
> +            	not unmatchedLabels( resource.spec.selector, statefulset.spec.template.metadata.labels)
```suggestion
                match_labels(resource.spec.selector, statefulset.spec.template.metadata.labels)
```

2022-05-05 12:11 UTC, joaorufi requested changes

2022-05-05 12:11 UTC, joaorufi commented on assets/queries/k8s/statefulset_without_service_name/query.rego
>  		"keyExpectedValue": sprintf("metadata.name=%s.spec.serviceName refers to a Headless Service", [metadata]),
```suggestion
		"keyExpectedValue": sprintf("metadata.name=%s.spec.serviceName should refer to a Headless Service", [metadata]),
```

Please, also update on the terraform query

2022-05-05 13:43 UTC, rafaela-soares requested changes

2022-05-05 13:43 UTC, rafaela-soares commented on assets/queries/k8s/statefulset_without_service_name/metadata.json
> +  "descriptionText": "StatefulSets should have a headless 'serviceName'. The headless service labels should also be implemented on StatefulSets labels.",
```suggestion
  "descriptionText": "StatefulSets should not have a headless 'serviceName'. The headless service labels should be implemented on StatefulSets labels.",
```

2022-05-05 13:43 UTC, rafaela-soares requested changes

2022-05-05 13:43 UTC, rafaela-soares commented on assets/queries/terraform/kubernetes/statefulset_without_service_name/metadata.json
> +  "descriptionText": "StatefulSets should have a headless 'serviceName'. The headless service labels should also be implemented on StatefulSets labels.",
```suggestion
  "descriptionText": "StatefulSets should not have a headless 'serviceName'. The headless service labels should be implemented on StatefulSets labels.",
```

2022-05-06 07:53 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-05-06 12:57 UTC, joaorufi approved these changes

2022-05-06 12:57 UTC, merged