update(query): Remote Desktop Port Open To Internet and HTTP Port Open To Internet
Checkmarx/kics pull request #5307
Opened 2022-05-05 11:22 UTC by cxMiguelSilva

Closes #5276

**Proposed Changes**
- Change AWS open ports queries names and description in Terraform, CloudFormation and Ansible
- Update Terraform library function name

I submit this contribution under the Apache-2.0 license.

2022-05-05 12:12 UTC, joaorufi requested changes

2022-05-05 12:12 UTC, joaorufi commented on assets/queries/terraform/aws/remote_desktop_port_open_to_internet/test/positive_expected_result.json
> +]
Please, add the `fileName` attribute

2022-05-05 13:59 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-05-06 12:58 UTC, joaorufi approved these changes

2022-05-06 12:58 UTC, merged