feat(query): CNI Plugin Does Not Support Network Policies for Kubernetes
Checkmarx/kics pull request #5370
Opened 2022-05-18 18:03 UTC by cx-miguel-dasilva

**Proposed Changes**
- CNI Plugin Does Not Support Network Policies for Kubernetes
- Add support to CNI files in the analyzer 

I submit this contribution under the Apache-2.0 license.

2022-05-19 10:19 UTC, rjegoncalves reviewed
The severity and category LGTM.
The description should be better aligned with the CIS description (_5.3.1 Ensure that the CNI in use supports Network Policies_).

2022-05-20 08:26 UTC, rafaela-soares requested changes

2022-05-20 08:26 UTC, rafaela-soares commented on assets/queries/k8s/cni_plugin_does_not_support_network_policies/query.rego
> +	}
Please, add `searchLine`:

`"searchLine": common_lib.build_search_line(["plugins", j, "type"], []),`

2022-05-20 14:33 UTC, joaorufi requested changes

2022-05-20 14:33 UTC, joaorufi commented on assets/queries/k8s/cni_plugin_does_not_support_network_policies/query.rego
> +		"keyActualValue": sprintf("Plugins contains a plugin that does not support Network Policies", []),
```suggestion
		"keyExpectedValue": "Plugins should not contain a plugin that does not support Network Policies",
		"keyActualValue": "Plugins contains a plugin that does not support Network Policies",
```

2022-05-20 14:33 UTC, joaorufi commented on assets/queries/k8s/cni_plugin_does_not_support_network_policies/query.rego
> +		"keyActualValue": sprintf("Plugins contains a plugin that does not support Network Policies", []),
```suggestion
		"keyExpectedValue": "Plugins should not contain a plugin that does not support Network Policies",
		"keyActualValue": "Plugins contains a plugin that does not support Network Policies",
```

2022-05-23 14:10 UTC, joaorufi approved these changes

2022-05-23 14:37 UTC, merged