fix(queries): align descriptionText to similar queries across different platforms #2
Checkmarx/kics pull request #5460
Opened 2022-06-08 16:52 UTC by roi-orca

align descriptionText to similar queries across different platforms #2

**Proposed Changes**
- align descriptionText to similar queries across different platforms

I submit this contribution under the Apache-2.0 license.

2022-06-09 09:02 UTC, kaplanlior commented
Follow up to #5446 (tagging for future reference).

Thanks @roi-orca 
Please also include the common criteria for the queries in each PR (just so we can differentiate them over time).

2022-06-09 10:02 UTC, kaplanlior commented
A list of queries would help differentiate between PRs (without looking at the files themselves).
e.g.

Aligned description of similar quires:
- API Gateway With Invalid Compression
- API Gateway Without SSL Certificate
- Automatic Minor Upgrades Disabled

2022-06-13 06:17 UTC, roi-orca commented
@rafaela-soares can you approve please? :)

2022-06-13 10:24 UTC, rafaela-soares requested changes
Hello, @roi-orca!

Thank you so much for continuing to improve the descriptions 🚀

I only have a few suggestions. Let me know what you think about them, please 😊

2022-06-13 10:24 UTC, rafaela-soares commented on assets/queries/ansible/aws/automatic_minor_upgrades_disabled/metadata.json
> +  "descriptionText": "RDS instance should have automatic minor upgrades enabled",
```suggestion
  "descriptionText": "RDS instance should have automatic minor upgrades enabled, which means the attribute 'auto_minor_version_upgrade' must be set to true.",
```

2022-06-13 10:24 UTC, rafaela-soares commented on assets/queries/terraform/aws/automatic_minor_upgrades_disabled/metadata.json
> +  "descriptionText": "RDS instance should have automatic minor upgrades enabled",
```suggestion
  "descriptionText": "RDS instance should have automatic minor upgrades enabled, which means the attribute 'auto_minor_version_upgrade' must be set to true.",
```

2022-06-13 10:24 UTC, rafaela-soares commented on assets/queries/cloudFormation/aws/cloudfront_logging_disabled/metadata.json
> +  "descriptionText": "AWS Cloudfront distributions must have logging enabled",
```suggestion
  "descriptionText": "AWS Cloudfront distributions must have logging enabled, which means the attribute 'DistributionConfig.Logging' must be defined",
```

2022-06-13 10:24 UTC, rafaela-soares commented on assets/queries/ansible/aws/cloudtrail_multi_region_disabled/metadata.json
> +  "descriptionText": "CloudTrail multi region should be enabled",
```suggestion
  "descriptionText": "CloudTrail multi region should be enabled, which means attribute 'is_multi_region_trail' should be set to true",
```

2022-06-13 10:24 UTC, rafaela-soares commented on assets/queries/ansible/aws/redshift_not_encrypted/metadata.json
> +  "descriptionText": "AWS Redshift Cluster should be encrypted. Check if 'encrypted' field is false or undefined (default is false)",
Can you also update for `kics\assets\queries\cloudFormation\aws\redshift_not_encrypted\metadata.json`, please?

2022-06-13 10:24 UTC, rafaela-soares commented on assets/queries/cloudFormation/aws/api_gateway_with_invalid_compression/metadata.json
> +  "descriptionText": "API Gateway should have valid compression, which means attribute 'MinimumCompressionSize' should be set and it's value should be greater than -1 and smaller than 10485760.",
```suggestion
  "descriptionText": "API Gateway should have valid compression, which means attribute 'MinimumCompressionSize' should be set and its value should be greater than -1 and smaller than 10485760.",
```

2022-06-13 10:24 UTC, rafaela-soares commented on assets/queries/terraform/aws/api_gateway_with_invalid_compression/metadata.json
> +  "descriptionText": "API Gateway should have valid compression, which means attribute 'minimum_compression_size' should be set and it's value should be greater than -1 and smaller than 10485760.",
```suggestion
  "descriptionText": "API Gateway should have valid compression, which means attribute 'minimum_compression_size' should be set and its value should be greater than -1 and smaller than 10485760.",
```

2022-06-13 10:24 UTC, rafaela-soares commented on assets/queries/cloudFormation/aws/rds_storage_not_encrypted/metadata.json
> +  "descriptionText": "RDS Storage should be encrypted",
```suggestion
  "descriptionText": "RDS Storage should be encrypted, which means the attribute 'StorageEncrypted' should be set to 'true'",
```

2022-06-13 10:43 UTC, roi-orca commented
@rafaela-soares resolved comments 👍

2022-06-13 10:45 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-06-13 11:02 UTC, roi-orca commented
@rafaela-soares how I can re-run the check that failed?
`Warning:  uploadChunk (start: 100663296, end: 134217727) failed: Cache service responded with 503`
https://github.com/Checkmarx/kics/runs/6859677716?check_suite_focus=true

2022-06-13 11:24 UTC, merged

2022-06-20 07:56 UTC, rafaela-soares commented
Hello, @roi-orca!

Yes, of course! The new release probably will be this wednesday😊