feat(scan): consider .gitignore to automatically exclude paths by default
Checkmarx/kics pull request #5506
Opened 2022-06-21 14:47 UTC by rafaela-soares

Issue #4584 will be closed when the branch `release/1.6` is merged into the master.

**Proposed Changes**
- consider `.gitignore` to automatically exclude paths by default

I submit this contribution under the Apache-2.0 license.

2022-06-23 07:43 UTC, roi-orca commented
@rafaela-soares I would suggest having the default behavior as of today, meaning .gitignore content will be taken into consideration as part of the scan, and the newly added flag, which can be called `"--include-gitignore"` will exclude the content from the scan.

If we do that, we do not break the current usage of the CLI, and we are having a "strict by default" approach

2022-06-23 18:10 UTC, nunoocx requested changes
Please review the suggestions

2022-06-23 18:10 UTC, nunoocx commented on docs/commands.md
> +By default, KICS now automatically excludes paths according to the .gitignore file. If you want to disable this behavior, you use the flag `--add-gitignore`.
Change to
By default, KICS excludes paths specified in the .gitignore file in the root of the repository. To disable this behavior, use flag `--add-gitignore`.

2022-06-23 18:10 UTC, nunoocx commented on docs/dockerhub.md
> +      --add-gitignore                 disables the usage of .gitignore file to automatically exclude paths
disables the exclusion of paths specified within .gitignore file

2022-06-23 18:10 UTC, nunoocx commented on e2e/fixtures/assets/scan_help
> +      --add-gitignore                 disables the usage of .gitignore file to automatically exclude paths
same as above

2022-06-23 18:10 UTC, nunoocx commented on internal/console/assets/scan-flags.json
> +    "usage": "disables the usage of .gitignore file to automatically exclude paths"
same as above

2022-07-19 08:59 UTC, rafaela-soares commented
> @rafaela-soares I would suggest having the default behavior as of today, meaning .gitignore content will be taken into consideration as part of the scan, and the newly added flag, which can be called `"--include-gitignore"` will exclude the content from the scan.
> 
> If we do that, we do not break the current usage of the CLI, and we are having a "strict by default" approach

Hello, @roi-orca!

Thank you so much for being involved in this question and for your suggestion.

It was a product decision to exclude paths specified within .gitignore file by default. A few users suggested that since the .gitignore file presents the files that will be not committed. Since it can be considered a breaking change, this new behavior will be only included from version 1.6. To disable this behavior, you can use flag `--add-gitignore`.

2022-07-28 14:56 UTC, nunoocx requested changes

2022-07-28 14:56 UTC, nunoocx commented on docs/commands.md
> +      --add-gitignore                 disables the exclusion of paths specified within .gitignore file
Hi @rafaela-soares , revisiting this, the flag add-gitignore sounds misleading.
Taking the suggestion from @roi-orca (and considering that the default will be to include gitignore) WDYT if we change to `--exclude-gitignore` ?
If agreed, please make the remainder of the code consistent to that new naming.

2022-07-28 15:44 UTC, nunoocx approved these changes
Great work!

2022-07-29 10:11 UTC, merged