Add wafv2 to query incl. negative test
Checkmarx/kics pull request #5529
Opened 2022-06-24 11:44 UTC by AlexEndris

Closes #5480

**Proposed Changes**
-
-
-

I submit this contribution under the Apache-2.0 license.

2022-06-27 06:29 UTC, kaplanlior commented
Hi @AlexEndris, 

The PR template has a declaration about the contribution license:
"I submit this contribution under the Apache-2.0 license."
Your PR is missing it. 

Please write this clearly in a comment so we'll be able to accept this PR.
Thanks.

2022-06-27 08:47 UTC, AlexEndris commented
@kaplanlior I submit this contribution under the Apache-2.0 license. :)

2022-06-27 08:52 UTC, rafaela-soares requested changes
Hello, @AlexEndris!

Thank you so much for contributing to KICS 🚀 

Please, take a look at my suggestion to fix the "typo":

2022-06-27 08:58 UTC, AlexEndris commented on assets/queries/terraform/aws/api_gateway_without_waf/query.rego
> +    targetResources := {"aws_wafregional_web_acl_association", "aws_wafv2_web_acl_association")
Was just going to look at it. Incoming :)

2022-06-29 18:25 UTC, AlexEndris commented on assets/queries/terraform/aws/api_gateway_without_waf/query.rego
> +    targetResources := {"aws_wafregional_web_acl_association", "aws_wafv2_web_acl_association")
@rafaela-soares Was the change in the brackets enough or did I miss anything else?

2022-06-30 07:58 UTC, rafaela-soares approved these changes
LGTM 🚀 Thank you so much, @AlexEndris!

2022-06-30 07:58 UTC, merged

2022-06-30 08:02 UTC, rafaela-soares commented on assets/queries/terraform/aws/api_gateway_without_waf/query.rego
> +    targetResources := {"aws_wafregional_web_acl_association", "aws_wafv2_web_acl_association")
Yes, it was enough. I already approved and merged it! Once again, thank you so much, @AlexEndris 🚀