Added Image Must Be Defined query #555
Checkmarx/kics pull request #556
Opened 2020-11-30 15:46 UTC by joelcarvalhocheckmarx

Image must be defined and not be empty or equal to latest.

Closes #555

2020-12-08 12:26 UTC, joaomartinscx requested changes

2020-12-08 12:26 UTC, joaomartinscx commented on assets/queries/k8s/resource_with_allow_privilege_escalation/image_defined/query.rego
> +                "keyActualValue": 	sprintf("spec.containers[%d].image is undefined", [c])
Add metadata tags

2020-12-08 12:26 UTC, joaomartinscx commented on assets/queries/k8s/resource_with_allow_privilege_escalation/image_defined/query.rego
> +                "keyActualValue": 	sprintf("spec.containers[%d].image is null, empty or latest", [c])
Same thing here

2020-12-09 16:03 UTC, joaomartinscx reviewed
Everything looks good to me, I recommend the approval and merge of this PR

2020-12-09 18:52 UTC, ruigomescx approved these changes

2020-12-09 18:52 UTC, merged