fix(keyExpectedValue): cloudformation-aws queries convert to a recommendation rather than a current status - stage 2
Checkmarx/kics pull request #5647
Opened 2022-07-28 14:32 UTC by liorj-orca

…endation rather than a current status - stage 2

Closes #

**Proposed Changes**
-
-
-

I submit this contribution under the Apache-2.0 license.

2022-07-28 16:07 UTC, rafaela-soares requested changes
Hello again, @liorj-orca!

Thank you so much for another PR 🚀

This PR is also failing in the E2E tests. If you need any help, let me know 😊

2022-07-28 16:07 UTC, rafaela-soares commented on assets/queries/cloudFormation/aws/directory_service_microsoft_ad_password_set_to_plaintext_or_default_ref/query.rego
> +		"keyExpectedValue": sprintf("Parameters.%s.Default should not defined", [paramName]),
```suggestion
"keyExpectedValue": sprintf("Parameters.%s.Default should not be defined", [paramName]),
```

2022-07-28 16:07 UTC, rafaela-soares commented on assets/queries/cloudFormation/aws/ec2_permissive_network_acl_protocols/query.rego
> +		"keyExpectedValue": sprintf("'Resources.%s.Properties.Protocol' should be either 6 (for TCP), 17 (for UDP), 1 (for ICMP), or 58 (for ICMPv6, which must include an IPv6 CIDR block, ICMP type, and co
I notice a typo in keyActualValue. Can you fix it, please? Thank you so much, in advance.

"protocol different **then** 6" to "protocol different **than** 6"

2022-08-19 10:50 UTC, gabriel-cx commented
Hello, @liorj-orca!
Feel free to ping me if you need something from our side in order to close this PR! ⛵
If you prefer, we can close it in our side.

2022-08-22 15:18 UTC, cxMiguelSilva approved these changes
LGTM

2022-08-23 08:05 UTC, cxMiguelSilva approved these changes

2022-08-23 08:06 UTC, rafaela-soares approved these changes

2022-08-23 08:07 UTC, merged