fix(queries): add check for ec2messages actions for iam policy grants full permissions
Checkmarx/kics pull request #5728
Opened 2022-08-23 14:08 UTC by cxMiguelSilva

Closes #5714 

**Proposed Changes**
- add check for ec2messages actions for IAM policy grants full permissions due to only ec2messages only support wildcard in resources
- add negative samples

I submit this contribution under the Apache-2.0 license.

2022-08-23 16:50 UTC, rafaela-soares requested changes

2022-08-23 16:50 UTC, rafaela-soares commented on assets/queries/ansible/aws/iam_policy_grants_full_permissions/query.rego
> +	common_lib.not_only_ec2messages_actions(statement.Action)
I think we should look to the CF query approach and implement it in ANS and TF query

2022-08-25 15:00 UTC, rafaela-soares requested changes

2022-08-30 16:29 UTC, gabriel-cx approved these changes
LGTM

2022-08-30 16:34 UTC, merged