fix(query): change s3 bucket with all permissions security query
Checkmarx/kics pull request #5781
Opened 2022-09-09 16:42 UTC by cxMiguelSilva

**Proposed Changes**
- fix  s3 bucket with all permissions security query
- delete duplicate query

I submit this contribution under the Apache-2.0 license.

2022-09-15 11:23 UTC, gabriel-cx approved these changes
LGTM

2022-09-20 10:52 UTC, rafaela-soares requested changes

2022-09-20 10:52 UTC, rafaela-soares commented on assets/queries/terraform/aws/s3_bucket_with_all_permissions/query.rego
> +		"keyActualValue": "'policy.Statement' allows all actions to any principal",
```suggestion
		"keyExpectedValue": "'policy.Statement' should not allow all actions to all principal",
		"keyActualValue": "'policy.Statement' allows all actions to all principal",
```

2022-09-20 10:52 UTC, rafaela-soares commented on assets/queries/terraform/aws/s3_bucket_with_all_permissions/query.rego
> +		"keyActualValue": "'policy.Statement' allows all actions to any principal",
```suggestion
		"keyExpectedValue": "'policy.Statement' should not allow all actions to all principal",
		"keyActualValue": "'policy.Statement' allows all actions to all principal",
```

2022-09-20 10:52 UTC, rafaela-soares commented on assets/queries/ansible/aws/s3_bucket_with_all_permissions/query.rego
> +	common_lib.containsOrInArrayContains(statement.Principal, "*")
Please, add more info in `keyExpectedValue` and `keyActualValue`

2022-09-20 10:52 UTC, rafaela-soares commented on assets/queries/terraform/aws/s3_bucket_with_all_permissions/query.rego
> +	common_lib.containsOrInArrayContains(statement.Principal, "*")
I think we should also look to `aws_s3_bucket_policy` as `assets\queries\terraform\aws\s3_bucket_allows_all_actions_from_all_principals` was doing

2022-09-20 10:52 UTC, rafaela-soares commented on assets/queries/cloudFormation/aws/s3_bucket_with_all_permissions/metadata.json
> +  "descriptionText": "S3 Buckets should not have all permissions, as to prevent leaking private information to the entire internet or allow unauthorized data tampering / deletion. This means the 'Eff
The query implementation approach for CF is different. IMHO, we should use a unique approach

2022-09-22 16:40 UTC, rafaela-soares requested changes

2022-09-22 16:40 UTC, rafaela-soares commented on paylaod.json
> +{
Please, delete this file

2022-09-23 10:49 UTC, rafaela-soares requested changes

2022-09-23 10:49 UTC, rafaela-soares commented on assets/queries/terraform/aws/s3_bucket_with_all_permissions/query.rego
> +		"resourceType": res_type,
Please, update resourceName: 

`"resourceName": tf_lib.get_specific_resource_name(resource, res_type, name),`

2022-09-23 11:32 UTC, rafaela-soares approved these changes
LGTM 🚀

2022-09-23 11:51 UTC, merged