feat: ingress ipv6 security group
Checkmarx/kics pull request #6079
Opened 2023-01-11 10:02 UTC by dim-ops

### Context
There is currently no limitation on IPV6 security groups in ingress. So I propose rules to avoid opening to everything.

### Proposed Changes
Add the same IPV4 rules with ipv6 settings

### How to test
I created :
- 4 negative tests : `negative5.tf`, `negative6.tf`, `negative7.tf`, `negative8.tf`
- 5 positive tests : `postive6.tf`, `positive7.tf`, `positive8.tf`, `positive9.tf`, `positive10.tf`

I submit this contribution under the Apache-2.0 license.

2023-01-11 12:07 UTC, cxMiguelSilva requested changes
Hi @dim-ops, hope you are doing great!
Happy new year 🎉
Thank you so much for this amazing contribution!! 
All the policies that you have created and the added samples LGTM.
I have just one request, could you update all the `keyExpectedValue` to use "should not be equal to"?

2023-01-11 12:12 UTC, dim-ops commented on assets/queries/terraform/aws/unrestricted_security_group_ingress/query.rego
> +		"keyExpectedValue": "One of 'rule.ipv6_cidr_blocks' not equal '::/0'",
I'm going to do this :)

2023-01-11 15:32 UTC, dim-ops commented
> Hi @dim-ops, hope you are doing great! Happy new year 🎉 Thank you so much for this amazing contribution!! All the policies that you have created and the added samples LGTM. I have just one request, could you update all the `keyExpectedValue` to use "should not be equal to"?

It's done :) and happy new year too !

2023-01-16 09:28 UTC, cxMiguelSilva approved these changes
Great!!
Thank you so much for this amazing contribution!

2023-01-16 10:54 UTC, merged