feat(tf-gcp-auth): check for legacy authentication enabled
Checkmarx/kics pull request #6205
Opened 2023-03-01 23:23 UTC by meldaravaniel

related to #91

Google now recommends against using Client Certificates as authentication and they automatically configure OAuth on all clusters.  For new clusters, master_auth can be left undefined.  For existing clusters, it can be undefined or set the issue_cert to false (probably just prefer `master_auth` undefined, but that might be too opinionated?).  Unless I'm mistaken, all clusters have OAuth enabled, even those that had client certs issued.  

You can't remove a client cert if it's already there, so they recommend making sure nothing in the cluster is allowed to use it anymore and the cluster has RBAC enabled.  More detail [here](https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication#disabling_authentication_with_a_client_certificate).  

More info [in the GCloud docs](https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication). 

**Proposed Changes**
- repurpose the "client certificate disabled" query into "legacy auth enabled"
- clusters should either not define the `master_auth` block, or they should set `master_auth.client_certificate_config.issue_client_certificate` to false
- updates tests, docs, and text in the metadata file

I submit this contribution under the Apache-2.0 license.

2023-03-01 23:29 UTC, meldaravaniel commented on assets/queries/terraform/gcp/legacy_auth_enabled/test/negative.tf
> -    username = ""
also removed these because they're not allowed in current versions of GKE

2023-03-01 23:34 UTC, meldaravaniel commented
Setting to draft because I thought it would be a good idea to branch of my master...so this includes the changes from my first PR...

If/when that one gets accepted, will update this accordingly.

2023-03-13 09:54 UTC, cxMiguelSilva requested changes
Hi @meldaravaniel, 
Thank you for another outstanding contribution!
Regarding the proposed changes, I would like to ask you to update the Security Query name to go accordingly to our Application Security team review of this PR.

2023-03-13 09:54 UTC, cxMiguelSilva commented on assets/queries/terraform/gcp/legacy_auth_enabled/metadata.json
> +  "queryName": "Legacy Auth Enabled",
```suggestion
  "queryName": "Legacy Client Certificate Auth Enabled",
```

2023-03-14 10:04 UTC, cxMiguelSilva approved these changes

2023-03-14 10:04 UTC, merged