Add Kubernetes Service Account Binding is Default query for Terraform #626
Checkmarx/kics pull request #628
Opened 2020-12-04 15:28 UTC by pedro-mimoso

The default namespace should not be used #626

2020-12-07 12:30 UTC, jorge-cruz requested changes

2020-12-07 12:30 UTC, jorge-cruz commented on assets/queries/k8s/default_service_account_binding/metadata.json
> +  "queryName": "Kubernetes Service Account Binding is Default",
I think "Kubernetes" is not necessary. A better name could be "Role Binding To Default Service Account"

2020-12-07 12:30 UTC, jorge-cruz commented on assets/queries/k8s/default_service_account_binding/metadata.json
> +  "descriptionText": "The default namespace should not be used",
Change the description to "The default service account should not be used"

2020-12-07 12:30 UTC, jorge-cruz commented on assets/queries/k8s/default_service_account_binding/query.rego
> +                "keyActualValue": 	sprintf("subjects.name=%s is default", [subjects[c].name])
Change the keys to:
```
"keyExpectedValue": "subjects.kind=ServiceAccount.name is not default",
"keyActualValue": "subjects.kind=ServiceAccount.name is default"
```

2020-12-07 16:07 UTC, jorge-cruz requested changes

2020-12-07 16:07 UTC, jorge-cruz commented on assets/queries/k8s/default_service_account_binding/metadata.json
> +  "descriptionText": "The default namespace should not be used",
Or maybe "No role nor cluster role should bind to a default service account"

2020-12-10 16:14 UTC, ruigomescx approved these changes

2020-12-10 16:14 UTC, merged