Add allow_privilege_escalation Closes #630
Checkmarx/kics pull request #631
Opened 2020-12-04 16:12 UTC by rafaela-soares

For this query, it is necessary to check if attribute 'allowPrivilegeEscalation' is undefined or set a true, since it is supposed to be set a false

Closes #630

2020-12-07 17:56 UTC, Ruben-Silva requested changes

2020-12-07 17:56 UTC, Ruben-Silva commented on assets/queries/k8s/allow_privilege_escalation/metadata.json
> +  "queryName": "Allow Privilege Escalation",
Change the query name to something like "Privilege Escalation Allowed"

2020-12-07 17:56 UTC, Ruben-Silva commented on assets/queries/k8s/allow_privilege_escalation/metadata.json
> +  "descriptionText": "Containers should not run with allowPrivilegeEscalation in order to prevent gain more privileges than their parent process",
"Containers should not run with allowPrivilegeEscalation in order to prevent them from gaining more privileges than their parent process"

2020-12-07 17:56 UTC, Ruben-Silva commented on assets/queries/k8s/allow_privilege_escalation/test/positive_expected_result.json
> +		"queryName": "Allow Privilege Escalation",
Change the query name to something like "Privilege Escalation Allowed"

2020-12-07 17:56 UTC, Ruben-Silva commented on assets/queries/k8s/allow_privilege_escalation/test/positive_expected_result.json
> +		"queryName": "Allow Privilege Escalation",
Change the query name to something like "Privilege Escalation Allowed"

2020-12-11 11:49 UTC, joelsou5a approved these changes

2020-12-11 11:50 UTC, merged