feature query amazon dm publicly accessible
Checkmarx/kics pull request #6352
Opened 2023-05-04 13:10 UTC by cx-henriqueAlvelos

**Proposed Changes**
- Added query for Publicly Accessible Amazon DMS
- Added positive, negative and positive_expect_results
- Added metadata

I submit this contribution under the Apache-2.0 license.

2023-05-19 16:07 UTC, pereiramarco011 requested changes

2023-05-19 16:07 UTC, pereiramarco011 commented on assets/queries/cloudFormation/aws/amazon_dms_replication_instance_is_publicly_accessible/query.rego
> +		"issueType": "MissingAttribute",
This should be incorrectValeu instead of MissingAttribute as the attribute is present but has the wrong value

2023-05-26 10:15 UTC, gabriel-cx approved these changes

2023-06-01 11:38 UTC, gabriel-cx approved these changes

2023-06-01 14:31 UTC, pereiramarco011 approved these changes
LGTM

2023-06-01 14:40 UTC, merged