Added SearchLine in 2 queries
Checkmarx/kics pull request #6447
Opened 2023-06-15 13:19 UTC by cx-henriqueAlvelos

Closes #6433 

**Proposed Changes**
- Added SearchLine in 2 queries

I submit this contribution under the Apache-2.0 license.

2023-06-21 09:36 UTC, gabriel-cx approved these changes

2023-06-21 10:06 UTC, cxMiguelSilva approved these changes

2023-06-26 13:28 UTC, gabriel-cx approved these changes

2023-06-30 09:35 UTC, pereiramarco011 approved these changes
LGTM!! 😄

2023-06-30 09:51 UTC, pereiramarco011 requested changes
There seems to be modifications from a different branch, awaiting fix

2023-07-03 12:48 UTC, pereiramarco011 approved these changes
LGTM 😄!!

2023-07-03 14:26 UTC, merged