FIx reference check in json resolver
Checkmarx/kics pull request #6511
Opened 2023-07-11 15:54 UTC by cxMiguelSilva

Closes #

**Proposed Changes**
-
-
-

I submit this contribution under the Apache-2.0 license.

2023-07-13 10:23 UTC, gabriel-cx requested changes
kindly add tests

2023-07-17 12:52 UTC, pereiramarco011 approved these changes
LGTM 😄

2023-07-18 10:44 UTC, p3pijn commented
Maybe good to add logging that allows users to see on which file the analysis choked if any parsing issues remain. That will make troubleshooting a lot easier for future parsing-related issues. As can be seen in #6513, the stacktrace did not provide any helpful information on which file the analysis broke. Would make future troubleshooting a lot more efficient.

2023-07-18 11:35 UTC, pereiramarco011 approved these changes

2023-07-18 11:54 UTC, gabriel-cx commented
@p3pijn , you right! we will add your idea into our future implementations! thanks for your input!

2023-07-18 13:44 UTC, merged