Kics/892
Checkmarx/kics pull request #6516
Opened 2023-07-13 08:54 UTC by cx-henriqueAlvelos

**Proposed Changes**
- Parser for Ansible Inventory
- Tests

I submit this contribution under the Apache-2.0 license.

2023-07-21 09:04 UTC, pereiramarco011 requested changes
The template query should be removed as it is simply an example to test the new feature and not a real vulnerability.

Along with that I have added a few nitpick comments that are optional 😄

2023-07-31 09:58 UTC, pereiramarco011 approved these changes
LGTM 😄

2023-08-04 17:18 UTC, cxMiguelSilva requested changes
Hi @cx-henriqueAlvelos, 
The proposed changes to add the ini parser  LGTM 🚀
Please remove the Test print on the unit test file.

2023-08-04 17:18 UTC, cxMiguelSilva commented on pkg/parser/ansible/ini/comments/comments_test.go
> +				fmt.Println("olaola")
```suggestion
```
Remove test Print

2023-08-04 17:52 UTC, cxMiguelSilva submitted a review, later dismissed

2023-08-08 08:56 UTC, pereiramarco011 approved these changes
LGTM 😄

2023-08-08 09:29 UTC, merged