fix(query): Change ExpectedValue and ActualValue
Checkmarx/kics pull request #6543
Opened 2023-07-24 17:15 UTC by cx-henriqueAlvelos

Closes #6453

**Proposed Changes**
- Changed ExpectedValue and ActualValue

I submit this contribution under the Apache-2.0 license.

2023-07-25 08:54 UTC, cxMiguelSilva requested changes
Hi @cx-henriqueAlvelos,
For the proposed changes LGTM, I would just ask to update the policy file to not contain lines with huge numbers or characters in order to improve readability.

2023-07-26 13:14 UTC, pereiramarco011 submitted a review, later dismissed

2023-07-31 10:06 UTC, pereiramarco011 approved these changes

2023-08-01 14:56 UTC, pereiramarco011 approved these changes

2023-08-02 08:23 UTC, pereiramarco011 approved these changes

2023-08-02 08:33 UTC, merged