fix(workflows): fixed community label being added to bots prs and pr titles in other workflows
Checkmarx/kics pull request #6597
Opened 2023-08-03 13:28 UTC by freitasmillena

**Proposed Changes**
- Added dependabot as member
- Fixed pr titles on _prepare-release_ and _update_software_versions_ workflow.

I submit this contribution under the Apache-2.0 license.

2023-08-08 10:36 UTC, cx-henriqueAlvelos requested changes

2023-08-08 10:36 UTC, cx-henriqueAlvelos commented on .github/workflows/validate-issues.yaml
> +    - name: Fail the workflow
Hi @freitasmillena.
This name sounds a bit awkward. Could you change it to "Workflow failed" (for example)?

2023-08-08 10:36 UTC, cx-henriqueAlvelos commented on .github/workflows/validate-prs.yaml
> +    - name: Fail the workflow
Hi @freitasmillena .
Same issue here

2023-08-08 10:56 UTC, cx-henriqueAlvelos approved these changes

2023-08-08 14:07 UTC, cx-henriqueAlvelos submitted a review, later dismissed

2023-08-17 10:00 UTC, cxMiguelSilva submitted a review, later dismissed

2023-08-17 10:19 UTC, pereiramarco011 approved these changes

2023-08-18 08:44 UTC, merged