feat(CLI): add new flag --max-file-size to controle the max file size…
Checkmarx/kics pull request #6670
Opened 2023-08-27 10:31 UTC by tomk-orca

… allwed to scan

Closes #

**Proposed Changes**
-
-
-

I submit this contribution under the Apache-2.0 license.

2023-09-07 06:23 UTC, kaplanlior commented on internal/console/flags/scan_flags.go
> +	MaxFileSizeFlag        = "max-file-size" // orca-specifics
When the PR is merged, the comment wouldn't be true any more (:

2023-09-07 09:55 UTC, pereiramarco011 requested changes
Left a couple of comments, other than that, and [Lior's comment](https://github.com/Checkmarx/kics/pull/6670/files#r1318135867) LGTM 😄 

Keep up the good work 👍

2023-09-07 09:55 UTC, pereiramarco011 commented on internal/console/assets/scan-flags.json
> +    "usage": "max file size that allowed to scan in MB"
the description contains an error. I would advise changing it to "max scannable file size, in MB" or "max file size that will be scanned, in MB" or "max file size that is allowed to be scanned, in MB"

2023-09-07 09:55 UTC, pereiramarco011 commented on e2e/fixtures/assets/scan_help
> +      --max-file-size int             max file size that allowed to scan in MB (default 5)
change the description here too to pass the e2e tests

2023-12-12 15:15 UTC, JoaoCxMartins commented
Hi @tomk-orca, any update on this pull request?

2023-12-12 22:59 UTC, JoaoCxMartins approved these changes

2023-12-13 09:26 UTC, gabriel-cx requested changes
@JoaoCxMartins kindly add this new command in this [file](https://github.com/Checkmarx/kics/blob/master/docs/commands.md), so the users can check it in our doc webpage.

2023-12-13 11:15 UTC, gabriel-cx approved these changes

2023-12-13 17:44 UTC, pereiramarco011 commented on internal/console/pre_scan.go
> +	log.Info().Msgf("Max file size: %d Mb", flags.GetIntFlag(flags.MaxFileSizeFlag))
I dont like the english on that and other references, it looks weird. I used chatgpt to give a few suggestions, here is the best:

Max file size permitted for scanning

what do you think? tis could be replaced on other references like the description of the flag and so on

2023-12-14 09:08 UTC, JoaoCxMartins submitted a review, later dismissed

2023-12-14 09:45 UTC, gabriel-cx requested changes

2023-12-14 09:45 UTC, gabriel-cx commented on docs/commands.md
> +      --max-file-size int             max file size that is allowed to be scanned, in MB (default 5)
```suggestion
      --max-file-size int             max file size permitted for scanning, in MB (default 5)
```

2023-12-14 09:45 UTC, gabriel-cx commented on e2e/fixtures/assets/scan_help
> +      --max-file-size int             max file size that is allowed to be scanned, in MB (default 5)
```suggestion
      --max-file-size int             max file size permitted for scanning, in MB (default 5)
```

2023-12-14 09:45 UTC, gabriel-cx commented on internal/console/assets/scan-flags.json
> +    "usage": "max file size that is allowed to be scanned, in MB"
```suggestion
    "usage": "max file size permitted for scanning, in MB"
```

2023-12-14 09:47 UTC, gabriel-cx submitted a review, later dismissed

2023-12-14 10:08 UTC, JoaoCxMartins submitted a review, later dismissed

2023-12-14 10:18 UTC, pereiramarco011 approved these changes

2023-12-19 11:48 UTC, asofsilva commented
Hi @tomk-orca,

could you please add an E2E test where you can scan a file larger than 5MB to ensure that the file is not scanned? You can also ensure that, when using --max-file-size flag, the file is scanned. 

Thank you :)

2023-12-19 11:52 UTC, kaplanlior commented
> Hi @tomk-orca,
> 
> could you please add an E2E test where you can scan a file larger than 5MB to ensure that the file is not scanned? You can also ensure that, when using --max-file-size flag, the file is scanned.
> 
> Thank you :)

We should add them for now, as he is probably unenviable for the E2E tests.

Please don't block due to this, we can even add a task to complete those as a separate issue.

2023-12-19 15:54 UTC, cxMiguelSilva approved these changes

2023-12-20 10:16 UTC, cxMiguelSilva approved these changes

2023-12-20 10:17 UTC, merged