fix(query): ca certificate identifier is outdated tf aws
Checkmarx/kics pull request #6683
Opened 2023-08-30 08:49 UTC by freitasmillena

Closes #6680 

**Proposed Changes**
- Added allowed list of certificates according to [this document](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html)

I submit this contribution under the Apache-2.0 license.

2023-08-30 15:20 UTC, cx-henriqueAlvelos approved these changes
LGTM 🚀

2023-08-30 15:22 UTC, cx-henriqueAlvelos requested changes
All the changes look good to me. However, descriptionText should be updated also

2023-09-05 11:46 UTC, pereiramarco011 approved these changes
LGTM 😄 

What do you think of changing the descriptionUrl to the one added in the DescriptionText? it doesn't seem good to have 2 urls, I want to know your opinion on it 😄

2023-09-05 13:12 UTC, pereiramarco011 submitted a review, later dismissed

2023-09-05 14:27 UTC, cx-henriqueAlvelos approved these changes

2023-09-05 14:48 UTC, merged