feat(results): update cyclonedx reports to support v1.5
Checkmarx/kics pull request #6841
Opened 2023-12-29 10:18 UTC by ArturRibeiro-CX

**Proposed Changes**
-update cyclonedx reports to support v.1.5 from v.1.3

I submit this contribution under the Apache-2.0 license.

2024-01-01 09:04 UTC, kaplanlior submitted a review, later dismissed

2024-01-01 09:14 UTC, kaplanlior commented
The change looks minimal & clean. Thanks.

Do we need to change anything in the report itself in addition the schema reference?

For example - v1.5 support critical severity
https://cyclonedx.org/docs/1.5/xml/#type_severityType

https://github.com/Checkmarx/kics/blob/2afa90f7d7c466496a49abdd186a7de786d94391/pkg/report/model/cyclonedx.go#L19-L24

2024-01-10 09:52 UTC, pereiramarco011 requested changes
Please, also update the Documentation [here](https://github.com/Checkmarx/kics/blob/79b1631deb787da6469c3255ecafbd51cabd81fe/docs/results.md?plain=1#L621C1-L621C1) to make sure it references the new current version being used instead of the old one

Other than that looks good to me

2024-01-10 11:28 UTC, pereiramarco011 submitted a review, later dismissed

2024-01-16 17:19 UTC, gabriel-cx approved these changes

2024-01-17 10:21 UTC, merged