feat(cwe): add cwe into sarif report and KICS CLI results
Checkmarx/kics pull request #6845
Opened 2024-01-04 12:20 UTC by ArturRibeiro-CX

**Proposed Changes**

- add cwe into sarif report and KICS CLI results.

I submit this contribution under the Apache-2.0 license.

2024-01-08 14:49 UTC, JoaoCxMartins requested changes
remove development of cyclonedx to another branch

2024-01-08 14:49 UTC, JoaoCxMartins commented on pkg/report/model/cyclonedx_test.go
> +	XMLNS:        "http://cyclonedx.org/schema/bom/1.5",
remove this development to another branch

2024-01-08 16:59 UTC, JoaoCxMartins commented on pkg/report/model/cyclonedx.go
> +	// Update cycloneDX version to 1.5 (from 1.3 to 1.5 nothing needed to change since we only create 1 bom at a time,
Remove these comment lines

2024-01-09 10:06 UTC, JoaoCxMartins approved these changes

2024-01-09 17:06 UTC, gabriel-cx commented on pkg/report/model/sarif.go
> +	CWE               string          `json:"cwe,omitempty"`
do we really need this item?

2024-01-09 18:41 UTC, gabriel-cx approved these changes

2024-01-26 10:01 UTC, gabriel-cx requested changes

2024-01-26 10:01 UTC, gabriel-cx commented on Dockerfile
> +COPY --from=build_env /app/assets/cwe_csv/* /app/bin/assets/cwe_csv
kindly perform this same update into this [dockerfiles](https://github.com/Checkmarx/kics/tree/master/docker) if needed

2024-01-29 09:00 UTC, Jeeppler commented
Relates to: https://github.com/Checkmarx/kics/issues/6373

2024-01-29 09:05 UTC, JoaoCxMartins submitted a review, later dismissed

2024-01-29 12:06 UTC, cxMiguelSilva approved these changes
Awesome work @ArturRibeiro-CX 🙌
Just make sure the dockerfiles work as expected for the ones not tested in workflows as @gabriel-cx  mentioned.

2024-01-29 18:04 UTC, gabriel-cx approved these changes

2024-02-06 16:02 UTC, merged