feat(query): Added CBS Disk Without Encrypted for TencentCloud
Checkmarx/kics pull request #6904
Opened 2024-02-23 12:19 UTC by hellertang

**Proposed Changes**
- CBS Disk Without Encrypted for TencentCloud

I submit this contribution under the Apache-2.0 license.

2024-02-26 09:43 UTC, hellertang commented
Already add new cloudProvider : `tencentcloud` in `.github/scripts/queries-validator/metadata-schema.json`. Please check and run again.  Thanks.

2024-02-26 17:14 UTC, gabriel-cx requested changes

2024-02-26 17:14 UTC, gabriel-cx commented on assets/queries/terraform/tencentcloud/disk_encryption_disabled/metadata.json
> +}
Kindly add `"experimental": "true"` in this `metadata.json` file.
[Check this as an example](https://github.com/Checkmarx/kics/blob/master/assets/queries/terraform/nifcloud/computing_instance_has_common_private/metadata.json#L11).

2024-02-27 09:48 UTC, hellertang commented
Why does the e2e-debian-tests fail? I can’t seem to see the detailed error message.
Please tell me how to fix.
Thanks.

2024-02-27 11:54 UTC, gabriel-cx commented
> Why does the e2e-debian-tests fail? I can’t seem to see the detailed error message. Please tell me how to fix. Thanks.

Hi @hellertang ,

In this case we just need to rerun the test. The issue is not related to your PR's changes, do not worry :D

2024-02-27 12:20 UTC, hellertang commented
> > Why does the e2e-debian-tests fail? I can’t seem to see the detailed error message. Please tell me how to fix. Thanks.
> 
> Hi @hellertang ,
> 
> In this case we just need to rerun the test. The issue is not related to your PR's changes, do not worry :D

Thanks.  We sincerely hope that KICS can support the inspection of Tencent Cloud's Terraform resources. I aspire for this PR to be integrated, as a testament to the feasibility of this path. In doing so, we can strive to contribute more inspection rules pertinent to the Tencent Cloud Provider.

2024-02-27 12:34 UTC, gabriel-cx commented
> > > Why does the e2e-debian-tests fail? I can’t seem to see the detailed error message. Please tell me how to fix. Thanks.
> > 
> > 
> > Hi @hellertang ,
> > In this case we just need to rerun the test. The issue is not related to your PR's changes, do not worry :D
> 
> Thanks. We sincerely hope that KICS can support the inspection of Tencent Cloud's Terraform resources. I aspire for this PR to be integrated, as a testament to the feasibility of this path. In doing so, we can strive to contribute more inspection rules pertinent to the Tencent Cloud Provider.

Nice to know! Thank you again for this amazing contribution!

Kindly be aware that, since this is a new _cloud provider support (tencentcloud)_, in order to run this new queries you need to use the KICS flag `--experimental-queries`.
After merging this PR, we will update our documentation as well, so we can mention Tencent Cloud as a new support, under our [Beta Features section.](https://github.com/Checkmarx/kics?tab=readme-ov-file#beta-features)

2024-02-27 12:36 UTC, gabriel-cx commented
@hellertang kindly add a line for tencentcloud [here](https://github.com/Checkmarx/kics/blob/master/test/main_test.go#L43) as well. So the unit tests can run against tencentcloud queries.

2024-02-27 14:41 UTC, gabriel-cx commented
thanks @hellertang !

kindly be aware of this failing unit test:
![image](https://github.com/Checkmarx/kics/assets/111127232/ad9f5121-12dc-4a01-bbf7-ef7575839d49)

2024-02-28 05:12 UTC, hellertang commented
> thanks @hellertang !
> 
> kindly be aware of this failing unit test: ![image](https://private-user-images.githubusercontent.com/111127232/308210356-ad9f5121-12dc-4a01-bbf7-ef7575839d49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTcyMjcsIm5iZiI6MTcwOTA5NjkyNywicGF0aCI6Ii8xMTExMjcyMzIvMzA4MjEwMzU2LWFkOWY1MTIxLTEyZGMtNGEwMS1iYmY3LWVmNzU3NTgzOWQ0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwNTA4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzUxN2VmNzk2NTAwY2E0YzIzOTUzYzFmM2VjNWE2ODU1NTJjZTEzZWJjNjU3MDQ1NzJkYThlMmMzYTgyNjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4b6UpPaza6ydNNSJL559kHo3_XmhQ3fhCymvt1Bu5Y4)

Thanks @gabriel-cx . Already fix it just now.

I have discerned that if 'experimental' is set to true, 'Remediation' cannot be established in 'query.go', as this would result in the unit test not being able to execute successfully. So I remove it.

2024-02-28 08:45 UTC, gabriel-cx approved these changes

2024-02-28 08:45 UTC, merged

2024-02-28 08:48 UTC, gabriel-cx commented
Thank you @hellertang !
This week we will release a new KICS version (v1.7.13) and Tencent Cloud support will be part of it!

2024-05-22 17:53 UTC, gabriel-cx commented
Hi @hellertang  ,

I'm happy to let you know that your tencentcloud queries are now part of the KICS 'official queries'!
This means, tencentcloud queries will run by default when KICS detects terraform files.
This functionality will start to be available in the next KICS version (v2.1.0).

Thank you again for all your help on this!