feat(query): add new query for tencentcloud CDB resource
Checkmarx/kics pull request #7134
Opened 2024-06-14 10:14 UTC by SevenEarth

Hello, There is something new query for TencentCloud TKE resource:

cdb_instance_internet_service_enabled
cdb_instance_using_default_intranet_port
cdb_instance_without_backup_policy

Please help review the PR
Thanks

I submit this contribution under the Apache-2.0 license.

2024-06-14 10:17 UTC, SevenEarth commented
This is my local test
<img width="1302" alt="image" src="https://github.com/Checkmarx/kics/assets/45937856/1008747c-2f69-42ad-b9f3-d3900604da78">

2024-06-17 02:28 UTC, SevenEarth commented
Hello
Please help review the PR
Thanks

2024-06-17 10:35 UTC, gabriel-cx requested changes

2024-06-17 10:35 UTC, gabriel-cx commented on assets/queries/terraform/tencentcloud/cdb_instance_using_default_intranet_port/query.rego
> +		"keyExpectedValue": sprintf("[%s] 'intranet_port' should be set and the value cannot byt 3306",[name]),
```suggestion
		"keyExpectedValue": sprintf("[%s] 'intranet_port' should be set and the value should not be 3306",[name]),
```

2024-06-17 10:35 UTC, gabriel-cx commented on assets/queries/terraform/tencentcloud/cdb_instance_without_backup_policy/query.rego
> +		"keyExpectedValue": sprintf("tencentcloud_mysql_instance[%s] should has 'tencentcloud_mysql_backup_policy'", [name]),
```suggestion
		"keyExpectedValue": sprintf("tencentcloud_mysql_instance[%s] should have 'tencentcloud_mysql_backup_policy'", [name]),
```

2024-06-17 10:36 UTC, gabriel-cx commented
@SevenEarth thanks for the contribution! kindly take a look into the code review.

2024-06-17 14:57 UTC, ArturRibeiro-CX requested changes
Hey @SevenEarth, thanks for your contribution so far! 
Kindly review the requested changes please.

2024-06-17 14:57 UTC, ArturRibeiro-CX commented on assets/queries/terraform/tencentcloud/cdb_instance_internet_service_enabled/query.rego
> +		"keyExpectedValue": sprintf("[%s] has 'internet_service' set to 0 or undefiend", [name]),
```suggestion
		"keyExpectedValue": sprintf("[%s] has 'internet_service' set to 0 or undefined", [name]),
```

2024-06-18 11:32 UTC, ArturRibeiro-CX approved these changes

2024-06-18 14:47 UTC, merged

2024-06-19 01:47 UTC, SevenEarth commented
> 嘿@SevenEarth，感谢您迄今为止的贡献！ 请检查所请求的更改。

Thank you all, I will notice this issue in the next development