feat(query): add new query for tencentcloud TKE resource
Checkmarx/kics pull request #7138
Opened 2024-06-17 03:01 UTC by SevenEarth

ello, There is something new query for TencentCloud TKE resource:

tke_cluster_has_public_access
tke_cluster_log_disabled
tke_cluster_encryption_protection_disabled

Please help review the PR
Thanks

I submit this contribution under the Apache-2.0 license.

2024-06-17 03:27 UTC, SevenEarth commented
This is test
<img width="932" alt="image" src="https://github.com/Checkmarx/kics/assets/45937856/ea538bf0-d310-4756-a7d0-9f3f9144518f">

2024-06-17 16:37 UTC, ArturRibeiro-CX requested changes
Hi @SevenEarth, thanks for the amazing contributions so far! 
Kindly see my code review with some changes to the phrasing used, so far so good!

2024-06-18 11:31 UTC, ArturRibeiro-CX approved these changes

2024-06-18 13:49 UTC, merged

2024-06-19 01:43 UTC, SevenEarth commented
@ArturRibeiro-CX Thank you very much for pointing out the issues described in my code correctly. I will use this as the standard for developing the code in the future