Added new query Validate_ACM_Certitificate_DomainName
Checkmarx/kics pull request #741
Opened 2020-12-09 11:51 UTC by soniantao

2020-12-11 16:53 UTC, rogeriopeixotocx commented
Closes #739

2020-12-14 12:15 UTC, ruigomescx requested changes

2020-12-14 12:15 UTC, ruigomescx commented on assets/queries/cloudFormation/Validate_ACM_Certitificate_DomainName/metadata.json
> +  "queryName": "Verify_ACM_Certificate_DomainName",
Better name could be: Wildcard In ACM Certificate Domain Name

2020-12-14 12:15 UTC, ruigomescx commented on assets/queries/cloudFormation/Validate_ACM_Certitificate_DomainName/metadata.json
> +  "category": null,
Category missing: **Encryption and Key Management**

2020-12-14 18:33 UTC, ruigomescx approved these changes

2020-12-14 18:34 UTC, merged