Feature/add query ecs task defenition healthcheck disabled
Checkmarx/kics pull request #743
Opened 2020-12-09 13:53 UTC by joaoReigota1

Closes #742

2020-12-14 15:36 UTC, Ruben-Silva requested changes

2020-12-14 15:36 UTC, Ruben-Silva commented on assets/queries/cloudFormation/ecs_task_defenition_healthcheck_missing/metadata.json
> +  "queryName": "ECS Task Defenition HealthCheck Missing",
Fix a typo. 
 "id": "ECS_task_definition_healthcheck_missing",
  "queryName": "ECS Task Definition HealthCheck Missing",

2020-12-14 15:36 UTC, Ruben-Silva commented on assets/queries/cloudFormation/ecs_task_defenition_healthcheck_missing/metadata.json
> +  "descriptionText": "The HealthCheck property specifies an object representing a container health check",
The description should explain more about the vulnerability and not the property itself. Try something like "Amazon ECS must have the HealthCheck property defined to give more control over monitoring the health of tasks."

2020-12-15 15:39 UTC, ruigomescx approved these changes

2020-12-15 15:40 UTC, merged