Added Security Groups Not VPC #709
Checkmarx/kics pull request #744
Opened 2020-12-09 14:35 UTC by joelcarvalhocheckmarx

Security Groups must have VPC.

Closes #709

2020-12-15 22:21 UTC, joaomartinscx requested changes

2020-12-15 22:21 UTC, joaomartinscx commented on assets/queries/cloudFormation/security_groups_not_vpc/metadata.json
> +  "queryName": "Security Groups Not VPC",
"Security Groups Do Not Have VPC"

2020-12-15 22:21 UTC, joaomartinscx commented on assets/queries/cloudFormation/security_groups_not_vpc/query.rego
> +   default_name
Why is a SecurityGroup having "default" as GroupName is a failure?

2020-12-15 22:21 UTC, joaomartinscx commented on assets/queries/cloudFormation/security_groups_not_vpc/query.rego
> +   not_exists_vpc := check_exists_vpc(resources)
When a SecurityGroup has the name "default" doesn't need VPC

2020-12-15 22:21 UTC, joaomartinscx commented on assets/queries/cloudFormation/security_groups_not_vpc/query.rego
> +   not_exists_vpc := check_exists_vpc(resources)
To improve readability, make *check_exists_vpc* return true when vpc **does** exist and apply the not operator outside.

2020-12-15 22:21 UTC, joaomartinscx commented on assets/queries/cloudFormation/security_groups_not_vpc/query.rego
> +                "issueType":		   "IncorrectValue",
When an attribute is not defined, the issueType should be "MissingAttribute"

2020-12-17 12:37 UTC, joaomartinscx reviewed
Everything looks good to me, I recommend the approval and merge of this PR

2020-12-18 12:25 UTC, joelsou5a approved these changes

2020-12-18 12:25 UTC, merged