Added Default Security Groups Deny Traffic #746
Checkmarx/kics pull request #747
Opened 2020-12-09 15:33 UTC by joelcarvalhocheckmarx

Security Groups set as default must be denied traffic.

Closes #746

2020-12-15 22:39 UTC, joaomartinscx requested changes

2020-12-15 22:39 UTC, joaomartinscx commented on assets/queries/cloudFormation/default_security_groups_deny_traffic/metadata.json
> +  "queryName": "Default Security Groups Deny Traffic",
The queryName should define the problem, in this case, something like: "Default SecurityGroups Allow Traffic"

2020-12-17 12:35 UTC, joaomartinscx reviewed
Everything looks good to me, I recommend the approval and merge of this PR.

2020-12-18 12:27 UTC, joelsou5a approved these changes

2020-12-18 12:27 UTC, merged