Add Sec. Groups Allows egress access query #748
Checkmarx/kics pull request #751
Opened 2020-12-09 16:21 UTC by joelcarvalhocheckmarx

It is important that no security group allows unrestricted egress access.

Closes #748

2020-12-15 22:43 UTC, joaomartinscx requested changes

2020-12-15 22:43 UTC, joaomartinscx commented on assets/queries/cloudFormation/security_groups_allows_unrestricted_outbound_traffic/query.rego
> +   properties := resources.Properties
Just for sanity sake, check the resource if its a SecurityGroup, in case some resource attributes change

2020-12-17 12:33 UTC, joaomartinscx reviewed
Everything looks good to me, I recommend the approval and merge of this PR.

2020-12-18 12:28 UTC, joelsou5a approved these changes

2020-12-18 12:28 UTC, merged