add ECS Task Defenition Invalid Cpu or Memory #754
Checkmarx/kics pull request #755
Opened 2020-12-09 16:53 UTC by joaoReigota1

Closes #754

2020-12-14 15:47 UTC, Ruben-Silva requested changes

2020-12-14 15:47 UTC, Ruben-Silva commented on assets/queries/cloudFormation/ecs_task_defenition_invalid_cpu_or_memory/metadata.json
> +  "queryName": "ECS Task Defenition Invalid Cpu or Memory",
Fix typo and missing underscore.
"id": "ECS_Task_definition_invalid_cpu_or_memory",
  "queryName": "ECS Task Definition Invalid Cpu or Memory",

2020-12-14 15:47 UTC, Ruben-Silva commented on assets/queries/cloudFormation/ecs_task_defenition_invalid_cpu_or_memory/test/positive_expected_result.json
> +		"queryName": "ECS Task Defenition Invalid Cpu or Memory",
Fix typo
"queryName": "ECS Task Definition Invalid Cpu or Memory"

2020-12-14 15:47 UTC, Ruben-Silva commented on assets/queries/cloudFormation/ecs_task_defenition_invalid_cpu_or_memory/test/positive_expected_result.json
> +		"queryName": "ECS Task Defenition Invalid Cpu or Memory",
Fix typo
"queryName": "ECS Task Definition Invalid Cpu or Memory"

2020-12-15 18:22 UTC, ruigomescx approved these changes

2020-12-15 18:28 UTC, merged