Feature/add new query dynamo db with aws owned cmk
Checkmarx/kics pull request #762
Opened 2020-12-09 18:13 UTC by cataraujo190

Description: 
AWS DynamoDb should be encrypted using AWS Managed CMK, instead of AWS-owned CMK. To verify this, SSEType should be CMK and SSEEnabled must be verified if false for AWS-owned CMK or true for AWS-Managed CMK. Default value is false.

#761

2020-12-15 23:32 UTC, joaomartinscx requested changes

2020-12-15 23:32 UTC, joaomartinscx commented on assets/queries/cloudFormation/DynamoDB_with_AWS_Owned_CMK/metadata.json
> +  "category": null,
Missing the category, it should be "Encryption and Key Management"

2020-12-17 12:30 UTC, joaomartinscx reviewed
Everything looks good to me, I recommend the approval and merge of this PR

2020-12-18 12:31 UTC, joelsou5a approved these changes

2020-12-18 12:32 UTC, merged