Feature/cdn disable
Checkmarx/kics pull request #768
Opened 2020-12-10 10:15 UTC by soniantao

2020-12-15 23:56 UTC, joaomartinscx requested changes

2020-12-15 23:56 UTC, joaomartinscx commented on assets/queries/cloudFormation/disable_CDN/metadata.json
> +  "queryName": "CDN_missing_configuration",
queryName should have a verb to easily identify  the resource and the wrong action, in this case, something like: "CDN Configuration Is Missing"

2020-12-15 23:56 UTC, joaomartinscx commented on assets/queries/cloudFormation/disable_CDN/query.rego
> +  distributionConfig := properties.Enabled
Should check the resource type, if it "AWS::CloudFront::Distribution"

2020-12-15 23:56 UTC, joaomartinscx commented on assets/queries/cloudFormation/disable_CDN/query.rego
> +  object.get(properties, "Origins", "undefined") == "undefined"
What if only one of these checks is true, shouldn't also be caught?

2020-12-17 12:28 UTC, joaomartinscx requested changes

2020-12-17 12:28 UTC, joaomartinscx commented on assets/queries/cloudFormation/disable_CDN/query.rego
> +  object.get(properties, "Origins", "undefined") == "undefined"
This still hasn't been addressed. The check finds a failure when Not (Enabled Is True and Origins Is Defined), meaning, Enabled Is Not True or Origins Is Not Defined

2020-12-21 15:26 UTC, joaomartinscx reviewed
Everything looks good to me, I recommend the approval and merge of this PR

2020-12-21 16:09 UTC, ruigomescx approved these changes

2020-12-21 16:12 UTC, merged