S3 Bucket Logging Disabled  #789
Checkmarx/kics pull request #790
Opened 2020-12-10 17:03 UTC by joaoReigota1

Closes #789

2020-12-14 15:58 UTC, Ruben-Silva requested changes

2020-12-14 15:58 UTC, Ruben-Silva commented on assets/queries/cloudFormation/s3_bucket_logging_disabled/metadata.json
> +  "descriptionText": "S3 Bucket should have server access logging enabled",
In the description, try something like "Server Access Logging must be enabled on S3 Buckets so that all changes are logged and trackable"

2020-12-14 15:58 UTC, Ruben-Silva commented on assets/queries/cloudFormation/s3_bucket_logging_disabled/query.rego
> +                "issueType":		"MissingAttribute",  #"MissingAttribute" / "RedundantAttribute"
Remove the comments (" #"MissingAttribute" / "RedundantAttribute"")

2020-12-15 18:32 UTC, ruigomescx approved these changes

2020-12-15 18:43 UTC, merged