added Query ElastiCache with disabled at Rest Encryption
Checkmarx/kics pull request #819
Opened 2020-12-11 14:00 UTC by cataraujo190

Description:
In order to protect sensitive data, AWS ElastiCache Redis clusters should be encrypted rest. Encryption of data at rest prevents unauthorized access to your sensitive data stored on AWS ElastiCache Redis clusters and associated cache storage.

2020-12-14 18:13 UTC, ruigomescx requested changes

2020-12-14 18:13 UTC, ruigomescx commented on assets/queries/cloudFormation/elasticache_with_disabled_at_rest_encryption/query.rego
> +
At what types of resource does this query check? Type: 'AWS::Route53::RecordSet' and AWS::ElastiCache::ReplicationGroup? If so, we should check for the type to restrict the number of query results

2020-12-14 18:13 UTC, ruigomescx commented on assets/queries/cloudFormation/elasticache_with_disabled_at_rest_encryption/query.rego
> +                "searchKey": 	    sprintf("Resources.%s.properties", [key]),
can we refine our searchKey to point to the exact line? By checking the type of resource, we should be able to navigate to this field

2020-12-14 18:13 UTC, ruigomescx commented on assets/queries/cloudFormation/elasticache_with_disabled_at_rest_encryption/test/negative.yaml
> +AWSTemplateFormatVersion: '2010-09-09'
The sample is too big, can we cut to only display the important parts?

2020-12-14 18:13 UTC, ruigomescx commented on assets/queries/cloudFormation/elasticache_with_disabled_at_rest_encryption/test/positive.yaml
> +AWSTemplateFormatVersion: '2010-09-09'
The sample is too big, can we cut to only display the important parts?

2020-12-18 13:15 UTC, joelsou5a approved these changes

2020-12-18 13:15 UTC, merged