Add viewer_protocol_only_https_compliant query Closes #800. Some typos and errors fixes
Checkmarx/kics pull request #873
Opened 2020-12-14 09:14 UTC by NunoAraujoCX

Closes #800 

Checks if Viewer Protocol is only compliant with the HTTPS Protocol.
Corrected some typos and errors.

2020-12-18 12:33 UTC, jorge-cruz requested changes

2020-12-18 12:33 UTC, jorge-cruz commented on assets/queries/cloudFormation/viewer_protocol_only_https_compliant/metadata.json
> +  "queryName": "Viewer Protocol Only HTTPS Compliant",
The name should reflect the vulnerability. A more suitable name would be: "Viewer Protocol Policy Allows HTTP Protocol"

2020-12-18 12:33 UTC, jorge-cruz commented on assets/queries/cloudFormation/viewer_protocol_only_https_compliant/query.rego
> +  resources.Properties.DistributionConfig.CacheBehaviors.ViewerProtocolPolicy != "https-only"
Cache Behaviors is a list. Replace with:
`resources.Properties.DistributionConfig.CacheBehaviors[_].ViewerProtocolPolicy != "https-only"`

2020-12-18 12:33 UTC, jorge-cruz commented on assets/queries/cloudFormation/viewer_protocol_only_https_compliant/query.rego
> +                "searchKey": 	        sprintf("Resources.%s.Properties.DistributionConfig.CacheBehaviors.ViewerProtocolPolicy", [name]),
Replace with:
` "searchKey": 	        sprintf("Resources.%s.Properties.DistributionConfig.CacheBehaviors", [name]),`

2020-12-18 12:33 UTC, jorge-cruz commented on assets/queries/cloudFormation/viewer_protocol_only_https_compliant/test/positive.yaml
> +              LambdaFunctionARN: examp
CacheBehaviors is a list. Replace with:
```
          - ViewerProtocolPolicy: allow-all
            LambdaFunctionAssociations:
              - EventType: viewer-request
                LambdaFunctionARN: examp
```

2020-12-18 12:33 UTC, jorge-cruz commented on assets/queries/cloudFormation/viewer_protocol_only_https_compliant/test/positive_expected_result.json
> +		"line": 30
I think this will change to 29

2020-12-21 12:28 UTC, ruigomescx approved these changes

2020-12-21 12:28 UTC, merged