Add SageMaker Without VPC query #854
Checkmarx/kics pull request #877
Opened 2020-12-14 09:35 UTC by joelcarvalhocheckmarx

SageMaker must have the VPC defined.

Closes #854

2020-12-18 16:35 UTC, jorge-cruz requested changes

2020-12-18 16:35 UTC, jorge-cruz commented on assets/queries/cloudFormation/sage_maker_without_vpc/query.rego
> +}
I think a better approach would be checking if the field `Properties.DirectInternetAccess` is defined and set to "Disabled" (default is "Enabled"). This forces the notebook instance to access resources only through VPC.

2020-12-18 16:35 UTC, jorge-cruz commented on assets/queries/cloudFormation/sage_maker_without_vpc/metadata.json
> +  "queryName": "SageMaker Without VPC",
A more suitable name would be "SageMaker Notebook Not Placed In VPC"

2020-12-18 16:35 UTC, jorge-cruz commented on assets/queries/cloudFormation/sage_maker_without_vpc/metadata.json
> +  "descriptionText": "SageMaker must have the VPC defined.",
Change description to: "SageMaker Notebook must be placed in a VPC"

2020-12-21 09:09 UTC, joelsou5a approved these changes

2020-12-21 09:30 UTC, merged