Add API Gateway V2 Stage Not Access Log query #885
Checkmarx/kics pull request #886
Opened 2020-12-14 11:06 UTC by joelcarvalhocheckmarx

API Gateway V2 Stage should have Access Logging Settings defined.

Closes #885

2020-12-18 17:47 UTC, jorge-cruz requested changes

2020-12-18 17:47 UTC, jorge-cruz commented on assets/queries/cloudFormation/api_gateway_v2_stage_not_access_logging_settings/query.rego
> +   not exists_access_log
It would be simpler:
```
object.get(resource.Properties, "AccessLogSettings", "undefined") == "undefined"
```

2020-12-18 17:47 UTC, jorge-cruz commented on assets/queries/cloudFormation/api_gateway_v2_stage_not_access_logging_settings/query.rego
> +                "searchKey":        sprintf("Resources.%s.Properties.AccessLogSettings", [name]),
If there is a result, that means "AcessLogSettings" isn't defined and can't be in the searchKey.
Replace with:
`"searchKey":        sprintf("Resources.%s.Properties", [name]),`

2020-12-18 17:47 UTC, jorge-cruz commented on assets/queries/cloudFormation/api_gateway_v2_stage_not_access_logging_settings/metadata.json
> +  "queryName": "API Gateway V2 Stage Not Access Logging Settings",
A more suitable name would be "API Gateway V2 Stage Access Logging Settings Not Defined"

2020-12-21 12:47 UTC, ruigomescx approved these changes

2020-12-21 12:48 UTC, merged