Add API Gateway W/Out UsagePlan query #929
Checkmarx/kics pull request #930
Opened 2020-12-14 14:53 UTC by joelcarvalhocheckmarx

API Gateway Deployment should have API Gateway UsagePlan defined and associated.

Closes #929

2020-12-21 17:12 UTC, joaomartinscx requested changes

2020-12-21 17:12 UTC, joaomartinscx commented on assets/queries/cloudFormation/api_gateway_deployment_without_api_gateway_usage_plan_associated/query.rego
> +  find_api_stages(resource[_].Properties.ApiStages, restApiId, stageName)
you should use an index accessing the UsagePlan, to make sure its the same one

2020-12-22 11:57 UTC, joaomartinscx reviewed
Everything looks good, I recommend the approval and merge of this PR.

2020-12-22 15:20 UTC, ruigomescx approved these changes

2020-12-22 15:24 UTC, merged