Add pin_versions_in_gem_install Closes #983
Checkmarx/kics pull request #986
Opened 2020-12-15 12:35 UTC by NunoAraujoCX

Closes #983 

Check if we are using 'gem install <gem>:<version>' instead of 'gem install <gem>'

2020-12-23 16:53 UTC, joaoReigota1 requested changes

2020-12-23 16:53 UTC, joaoReigota1 commented on assets/queries/dockerfile/pin_versions_in_gem_install/metadata.json
> +  "queryName": "Pin Versions In Gem Install",
The query name should reflect the vulnerability, not the fix

2020-12-28 09:10 UTC, joaoReigota1 reviewed
Approved

2020-12-28 10:29 UTC, joelsou5a approved these changes

2020-12-28 10:30 UTC, merged